### ISSUE TITLE
[UX/UI] Switch button added automatically on no datas line 

### ISSUE THREAD

**Issue by lusebille** [gristlabs/grist-core#1008]
Because another line is added automattically to the last one in the table , when user choose 'boleen' , 'switch button' an unselected switch button appear on the last line , it shouldnt as it's an empty line 

<img width="400" alt="Capture d’écran 2024-05-30 à 10 56 39" src="https://github.com/gristlabs/grist-core/assets/170542975/0d0b61ab-9fba-4938-8c80-3eaca123a83c">

and user 'switch' the button each time a new line appear and we could have something like that : 
<img width="400" alt="Capture d’écran 2024-05-30 à 11 05 45" src="https://github.com/gristlabs/grist-core/assets/170542975/6ef3098e-124f-416e-80c6-63324dcd7133">

**Comment by vviers** [comment]
This feature can actually be useful for power users as this can allow powerful workflows (with trigger formulas for exemple)

**Comment by vviers** [comment]
Closing this ticket and adding it as context to #366
