### ISSUE TITLE
 BUG window.crypto.randomUUID is not a function

### ISSUE THREAD

**Issue by ebdavison** [gristlabs/grist-core#1062]
I get this error when trying to open the admin settings on my self-hosted grist instance:

`
window.crypto.randomUUID is not a function
`

![image](https://github.com/gristlabs/grist-core/assets/549431/c4507b18-5a7e-40d6-8b9f-a8f320929292)

**Comment by paulfitz** [comment]
Is this across http rather than https? If so, I think this problem has been recently fixed and upgrading your docker image may resolve it https://github.com/gristlabs/grist-core/pull/1024

**Comment by ebdavison** [comment]
I am currently using http but plan to move to https. 

I will pull an update and restart and then try again.

**Comment by paulfitz** [comment]
Thanks @ebdavison, if it still doesn't work please do ping me.

**Comment by ebdavison** [comment]
Yes, I can get to the admin panel after doing a `docker pull` for the latest version.

Thank you very much!
