### ISSUE TITLE
[cosmetic] Display action menu on any cell of the row on right-click

### ISSUE THREAD

**Issue by asitemade4u** [gristlabs/grist-core#108]
This one is purely cosmetic and could be the result of Grist being an hybrid between databases and spreadsheets.
When I want to delete a row/record in a Grist Document, I naturally right-click on the row to display an action popup menu but nothing happens.
Instead, I have to click on the little (currently **invisible**) arrow in the row number cell.
I feel the natural way to go would be to right-click on the row instead. And if the action must be performed on a cell, then double-click to enter the cell.

**Comment by georgegevoian** [comment]
Hi @asitemade4u, that sounds like a really useful feature to have. We've gone ahead and started tracking it internally. Thank you for the suggestion!

**Comment by alexmojaki** [comment]
> Instead, I have to click on the little (currently invisible) arrow in the row number cell.

Right-clicking anywhere in the row number cell works, not just the arrow.

I do agree that right-click should work on any cell in the row, particularly because "Copy anchor link" actually links to the currently selected cell (as opposed to the whole row) but you wouldn't know it from the fact that you have to use the row-level menu.

**Comment by asitemade4u** [comment]
You are right, but that really feels like the natural way to manage the row.

**Comment by asitemade4u** [comment]
@paulfitz mentioned, in aother context (manually reordering the rows) that one could grab the row number.
My feeling is that the row number is too small and not highlighted in any way (eg. handle bars), so not obvious as an actionable UX item.

**Comment by paulfitz** [comment]
There is a right-click menu for cells now :ballot_box_with_check:
