### ISSUE TITLE
[idea] Pre-defined way to order records in a table

### ISSUE THREAD

**Issue by asitemade4u** [gristlabs/grist-core#110]
This one might seem a bit of an overreach for a database but would have a lot of use cases: todo lists, prioritization, etc.
I also get that it is probably easy to implement using formulas and sort order (then, please, create one in the documentation).
The idea is:

1. add a specific type of column to a table; it could be called, for example, _column index_
2. from then on, any drag and drop of row in the table inputs the index in the column in question
3. and the rows stick to the position assigned to them

However Sorting using other criteria still works but does not impact the "column index" which can be restored at any time.

**Comment by asitemade4u** [comment]
Thinking qabout the idea, I think it would be the perfect candidate for some sort of **plugin**: not everybody needs it, but if needed, it can be implementged as a new type of column -- thus not being a burden to other users who do not need it.

**Comment by paulfitz** [comment]
Tables in Grist have an unadvertised hidden column called `manualSort` that may be related to what you want. If you click on a row, you can then drag its row number around to reorder it. The `manualSort` for that row will change such that ordering the rows by it will give the desired order (exactly how this works is a bit complicated).

https://user-images.githubusercontent.com/118367/145282397-79f510d7-a6c2-4bc3-9aae-ce150ac4d01b.mov

When you sort rows by some column, and then save that order, it is saved by updating `manualSort`.

**Comment by asitemade4u** [comment]
Well, you see, I had missed that one...

**Comment by asitemade4u** [comment]
> When you sort rows by some column, and then save that order, it is saved by updating manualSort.

I am not sure though that this should be the standard behavior because, ultimately, you lose the manual order when it should IMO _coexist_ with the automated order.

**Comment by asitemade4u** [comment]
And now I understand the reason for the Filter bar...

**Comment by asitemade4u** [comment]
Actually, I haver tested the Filter bar and clicking on the Validation green button on the Filter bar does NOT rewrite the `$manualSort` column.
Are there THREE different levels of row sorting then??

**Comment by dsagal** [comment]
$manualSort stores desired order in the data. The options to filter and to sort by one or more columns apply at the presentation level. These options can be changed in the UI and saved (using the green checkmark) to apply by default.

So in a way, there are 3 levels: the order that applies when no column sort is in effect (determined by manualSort); the column sort that's saved as a widget setting; and the column sort that you can tweak in the UI without saving.

**Comment by asitemade4u** [comment]
Yes, I get it now. Find it useful but a tad complex, mostly because I did not find the 3-level-sorting idea explained anywhere in the doc.
