### ISSUE TITLE
Allow configuring start of the week to either Sunday or Monday

### ISSUE THREAD

**Issue by mpsijm** [gristlabs/grist-core#1104]
Hi, I love using Grist for time tracking instead of my old spreadsheet. However, there's a slight inconvenience regarding filters and weekdays. When I want to see the hours that I made in the past week, I cannot create a date range filter between "Monday of last week" and "Sunday of last week", because Grist assumes that Sunday is the first day of the week, rather than Monday, like [roughly half of the world](https://www.timeanddate.com/calendar/days/first-day-of-the-week.html). It would be nice if this could be configured in Grist somehow, or be picked up from the current locale (or both).

Environment: I'm using the [AUR package](https://aur.archlinux.org/packages/grist-desktop-bin) for the standalone [grist-desktop](https://github.com/gristlabs/grist-desktop), version 0.2.10.

**Comment by fflorent** [comment]
Hello @mpsijm!

Thanks for the report. Could it be a duplicate of https://github.com/gristlabs/grist-core/issues/443?

**Comment by mpsijm** [comment]
Indeed, it looks like it! Thanks for pointing it out, it did not show up when querying for "start of week" :smile:
