### ISSUE TITLE
EACCES: permission denied (container restart cyclically after update from 15.07.2024 for latest tag)

### ISSUE THREAD

**Issue by Vladimir-Va** [gristlabs/grist-core#1108]
Hello, I can’t understand what the problem is, I updated the container on 07/15/2024 for latest tag and I get a cyclic reboot of the container. How can this be fixed?
```
2024/07/16   23:45:34,stdout,    at step   (/opt/yarn-v1.22.19/lib/cli.js:310:30)
--
2024/07/16 23:45:34,stdout,    at Generator.next (<anonymous>)
2024/07/16 23:45:34,stdout,    at /opt/yarn-v1.22.19/lib/cli.js:88756:56
2024/07/16 23:45:34,stdout,    at getRcConfigForCwd   (/opt/yarn-v1.22.19/lib/cli.js:56965:74)
2024/07/16 23:45:34,stdout,    at Object.findRc   (/opt/yarn-v1.22.19/lib/cli.js:97407:10)
2024/07/16 23:45:34,stdout,    at parseRcPaths   (/opt/yarn-v1.22.19/lib/cli.js:97393:78)
2024/07/16 23:45:34,stdout,    at Array.map (<anonymous>)
2024/07/16 23:45:34,stdout,    at /opt/yarn-v1.22.19/lib/cli.js:97395:58
2024/07/16 23:45:34,stdout,    at readFileSync (node:fs:464:35)
2024/07/16 23:45:34,stdout,    at Object.openSync (node:fs:596:3)
2024/07/16 23:45:34,stdout,"Error:   EACCES: permission denied, open '/root/.config/yarn'
```

**Comment by Vladimir-Va** [comment]
> Are you running it as a non-root user? If so, how are you setting the user?

I've had my container running as root (admin) for over a year now.
There were no problems before.
Need to set a user for docker persist folders? What UID:GID number should I set for the folder?

> Are you using docker or podman?

docker

> Have you modified the container in any way?
No, latest from gristlabs/grist

**Comment by Spoffy** [comment]
Could you tell me what volumes you're mounting persistently? It might be something in there. I'm just checking the best permissions settings to use.

**Comment by Vladimir-Va** [comment]
@Spoffy thank you for support.

> Could you tell me what volumes you're mounting persistently

/persist
and GRIST_DATA_DIR path.

> More docker log would also be useful. I'm curious why it's trying to run yarn.

That's all, this group of messages in the log is repeated cyclically.

**Comment by Spoffy** [comment]
Try using this image. It's built with a likely fix in, so should solve your problem:
https://hub.docker.com/layers/spoffy/grist/docker-home-fix/images/sha256-235fef78fe6e313fc44cdc9e29a05a20e7a7a1ba331aeb31e7fb4b678b25d231?context=explore

It'll take a bit longer to get it rolled out to our main images :)

**Comment by Spoffy** [comment]
The fix is merged now, it should be in `gristlabs/grist:experimental` within the next 24 hours I think. :)

**Comment by Vladimir-Va** [comment]
Thank you.
I rolled back the gristlabs/grist:1.1.15 version and it works fine.
According to the [announcement](https://community.getgrist.com/t/june-2024-newsletter-research-templates-running-rootless-and-community-contributions/5482), perhaps I need to do this on host:
`chown 1001:1001 /persist`
