### ISSUE TITLE
What is the best way to establish a hierarchical relation within a table?

### ISSUE THREAD

**Issue by asitemade4u** [gristlabs/grist-core#111]
I would like to develop a Grist document to help me manage the assets we have here: computers, electronic components, etc.
The way I would naturally do it is to create a table of all components and assets alike then link them hierarchically within the table.
For example:

> RAM --> computer <-- HDD

and so on. 
Of course, there would be no limit to how many levels one can manage the relations. For example:
> HDD --> HDD Enclosure --> computer

Is it possible to have a recursive relation in a Grist table?

**Comment by paulfitz** [comment]
Yes, a Grist table can have a reference to itself, for example see this goat pedigree table https://docs.getgrist.com/iqhzhQM66qg7/Pedigree-Example/m/fork :goat:. Here's a shot at doing what you describe: https://docs.getgrist.com/6iLb6VB9Zspp/Inventory/m/fork - is that along the right lines?

**Comment by asitemade4u** [comment]
This is great (and I love the goat example, when I was younger I spent my vacations in a goat farm in Alpes de Haute Provence in France and they were clever as hell...0.
