### ISSUE TITLE
[request] Allow populating the linked table of a Reference column on the fly

### ISSUE THREAD

**Issue by asitemade4u** [gristlabs/grist-core#113]
This one seems kind of useful to me as I have been compelled to backtrack several times while copying-pasting data into a new Grist document. 
1. I have a list of cities with their contries attached in LibreOffice, which I Copy:

![image](https://user-images.githubusercontent.com/11460106/145278503-6dfff8c3-7306-4387-bf1d-6d556e0f68b9.png)

1. I create a new Grist document
2. I name the default table Cities
1. I paste the list > OK

Now I want the Country to be a Reference list from another table, Countries. So:

1. I create a new table Countries
2. I name the first column Name > OK and the table is currently empty
2. I go back to the Cities and transform the 2nd column to a Reference, choosing the reference table as Counntries and the displayed column as Name
3. When I click Apply, the column turns red to show there is an error
4. Also, the column Name in the table Countries is not populated

![image](https://user-images.githubusercontent.com/11460106/145279834-4b60632a-cde7-46ca-8eae-ebce04d8b9a7.png)

I think there should at least be a question asked to the user if he/she wants to add unique values from the column Cities:country to the table Countries.
Otherwise, as it is currently, the process is _really_ tedious:

1. in LibreOffice I get all unique values in the column Country and copy them
2. I create the table Countries in Grist
3. I paste the column Country from LibreOffice in the newly created table Countries in Grist
4. I go back to LibreOffice and copy the whole table this time
4. I go back to the Cities table in Grist
5. I paste the two columns (city and country)
6. I then transform the Country column into a Reference column

Phew...

**Comment by dsagal** [comment]
Converting a column type allows creating an association between two tables of data, but you are right that there is no option currently to move data around as part of this conversion. I've also run into cases when I'd like some option like it, but usually the need is a bit more involved.

For this example, imagine that for each row contains another column with the country's language (e.g. "French" for the first three rows, and "German" for the next three). Ideally, if the list of unique countries moves to a new table, I'd like languages to move along with it. But then a checkbox isn't enough.

There is actually a way to do what you want (though still not so quick or easy):

1. Add Widget to Page > Cities [Summarize] > Group By: Country
2. In Creator Panel > Table > Data for the new summary table, select [Detach](https://support.getgrist.com/summary-tables/#detaching-summary-tables)
3. This creates a new table of countries: rename it to Countries.
4. Optionally, remove things you don't need: the `count` column, the `group` column (which you'd need to unhide first), and the "Countries" widget from the first page.
5. Now, transform the Country column into a Reference column.

**Comment by asitemade4u** [comment]
Thanks for the procedure. Also, I understand your point about the multiple possible choices of Reference columns.
All well thought, I guess this is a fringe need as it mostly happens once: when switching from another source to Grist.
