### ISSUE TITLE
[improvement] Display bubbles over page initials when the left sidebar is collapsed

### ISSUE THREAD

**Issue by asitemade4u** [gristlabs/grist-core#114]
When collapsed, the left sidebar shows the initials of each page.
Often, the initials are the same and it would be helpful to display a bubble with the full-length name of the page on hover.

Expanded state:

![image](https://user-images.githubusercontent.com/11460106/145589250-ad3ca7c0-87ec-4aca-b702-99dc1d702347.png)

Collapsed state = no way to know which is which:

![image](https://user-images.githubusercontent.com/11460106/145589332-cc246226-5922-4a34-930d-57306356c6b2.png)

**Comment by paulfitz** [comment]
It is a good idea. Using emoji as the first letter can help too:

<img width="351" alt="Screen Shot 2021-12-13 at 1 48 45 PM" src="https://user-images.githubusercontent.com/118367/145870556-fe41528a-ef96-4014-b20d-f5dfe52169f6.png">

**Comment by yohanboniface** [comment]
cc @louisdelbosc :)

**Comment by LouisDelbosc** [comment]
I think this issue is obsolete. Here a video to show you. I'll let you close the issue 🙂

https://user-images.githubusercontent.com/11460746/183599843-a5f9f812-13d3-4fa8-9f51-a56d38917486.mov

**Comment by paulfitz** [comment]
Good catch @LouisDelbosc, this behavior was added by @cpind recently (in https://github.com/gristlabs/grist-core/commit/80f31bffc299aa9f2601228e93a85fa5c7a02bdf)

**Comment by asitemade4u** [comment]
Great, your development team rocks!
