### ISSUE TITLE
[improvement] Allow row duplication using the local menu 

### ISSUE THREAD

**Issue by asitemade4u** [gristlabs/grist-core#116]
It would be really practical to be able to duplicate a row using the current row menu (under the row number).

**Comment by paulfitz** [comment]
Just stumbled across this thread, realized it has been implemented in the meantime :)
![Screenshot from 2023-06-07 22-56-42](https://github.com/gristlabs/grist-core/assets/118367/2aa8f662-5fb1-4394-bd67-84527d06d47d)
