### ISSUE TITLE
Cannot destructure property 'buildNameConfig' of 'e.FieldConfig' as it is undefined

### ISSUE THREAD

**Issue by yuturiy** [gristlabs/grist-core#1164]
### Describe the current behavior

Get error 
> Cannot destructure property 'buildNameConfig' of 'e.FieldConfig' as it is undefined

while open column tab after bumping self-hosted grist from 1.1.13 to 1.1.17

<img width="1249" alt="image" src="https://github.com/user-attachments/assets/633fd888-ba94-46a6-ad13-de63de93e372">

### Steps to reproduce

1. Setup self-hosted grist with 1.1.13
2. Create any table
3. Switch grist version to 1.1.17
4. Open table

### Describe the expected behavior

No errors. See column tab.

### Where have you encountered this bug?

- [ ] On [docs.getgrist.com](https://docs.getgrist.com)
- [X] On a self-hosted instance

### Instance information (when self-hosting only)

* Grist instance:
  * Version: 1.1.17
  * URL (if it's OK for you to share it):
  * Installation mode: docker
  * Architecture: multi-workers

* Browser name, version and platforms on which you could reproduce the bug: MacOS, Chrome 127.0.6533.120 amd64
* Link to browser console log if relevant:
* Link to server log if relevant:

**Comment by dsagal** [comment]
I followed the steps, but did not get the error, all worked properly. The error has to do with loading JS bundles.

Does the error happen after reloading the browser page (after switching grist version), or if the page isn't reloaded?

If you can reproduce it, could you check please in the browser's network console if there are errors fetching any JS files?
