### ISSUE TITLE
References should keep styling from original data list

### ISSUE THREAD

**Issue by lusebille** [gristlabs/grist-core#1223]
### Describe the problem

Today when user create a list in a table and use it in another table / widget as a reference/or multiple reference, style is not keeped.
For exemple if the orginal list is a choice list with colored tags it tooked him time to do, he will loose all benefit of that landing with a white or grey list.

Notice than in a few days already 4 users complain about it ( 5 including myself ).

I'm joining screenshot and a Grist file.
In the exemple 'Tags' column is used a a references for 'Keyword' column

<img width="976" alt="Capture d’écran 2024-09-23 à 15 42 40" src="https://github.com/user-attachments/assets/25b10291-c013-44c6-8fa2-19979dde137b">
<img width="1621" alt="Capture d’écran 2024-09-23 à 15 42 44" src="https://github.com/user-attachments/assets/6ddd9bf3-aa99-4470-b75c-4e231b7a5301">

[Styling references_OK.grist.zip](https://github.com/user-attachments/files/17099205/Styling.references_OK.grist.zip)

### Additional information

* Grist version:
* Grist instance URL:
* SSO solution used and its version (if relevant):
* S3 storage solution and its version (if relevant):
* Docker version (if relevant):
* NodeJS version (if relevant):
* Redis version (if relevant):
* PostgreSQL version (if relevant):

**Comment by vviers** [comment]
Closing as duplicate (#1222 )
