### ISSUE TITLE
[OIDC] `post_logout_redirect_uri` is wrong when `ORG_IN_PATH=true`

### ISSUE THREAD

**Issue by vviers** [gristlabs/grist-core#1235]
### Describe the current behavior

The URL after loging out of Grist is `https://{URL}/o/{ORG}/signed-out` when it should be something like `https://{URL}/signed-out` 

Indeed, [the OIDC spec](https://openid.net/specs/openid-connect-rpinitiated-1_0.html) states that  `post_logout_redirect_uri` "MUST have been previously registered with the OP, either using the post_logout_redirect_uris Registration parameter or via another mechanism."

However, it is impossible to register all possible, orgs-specific, logout urls. You **can't** register a wildcarded URL either such as `https://{URL}/o/*/signed-out`

### Steps to reproduce

1. Create a Grist instance with `ORG_IN_PATH` set to `true`
2. Log in
3. Navigate to a team site
4. Log out

### Describe the expected behavior

Logout URL should not depend on which team site you sign out from.

`https://{URL}/signed-out` seems sensible as a value.

### Where have you encountered this bug?

- [ ] On [docs.getgrist.com](https://docs.getgrist.com)
- [X] On a self-hosted instance

### Instance information (when self-hosting only)

* Grist instance:
  * Version: 1.1.18
  * Installation mode: k8s
  * Architecture: multi-workers

**Comment by fflorent** [comment]
The fix seems straightforward to me: we may simply change `getOrgUrl` to `getOriginUrl` here:
https://github.com/gristlabs/grist-core/blob/932a04aa63a618e57011317b40c2e84fe03017ab/app/server/lib/FlexServer.ts#L1289

However, I *think* fixing this would introduce a breaking change 😱. Indeed, people who are not aware of the new logout URL may have the bad surprise to find logging out leads to an error page, as the new URL does not match anymore the `post_logout_redirect_uri` they defined previously (please correct me if I am wrong).

We may: 
- introduce a new env variable flag (another one 😬) to actually produce that behavior;
- remove that flag and make this behavior the default when we release a new version with breaking changes (if we follow [semver](https://semver.org/), we may do that in a new major version?)

But it still feels like a bit cumbersome to me. Better ideas are welcome.

**Comment by vviers** [comment]
> However, I think fixing this would introduce a breaking change 😱. Indeed, people who are not aware of the new logout URL may have the bad surprise to find logging out leads to an error page, as the new URL does not match anymore the post_logout_redirect_uri they defined previously (please correct me if I am wrong).

My thinking is that :
- if users have `ORG_IN_PATH` set to false (which I believe is the default) then this will not break anything on their end since `getOrgUrl` is the same thing as `getOriginUrl` (if not, we can check what `ORG_IN_PATH` is set to in order to build the URL)
- if users have `ORG_IN_PATH` set to true, it's unlikely that they set up `post_logout_redirect_uri` well anyways (that's why this ticket exists)

WDYT ? I'll open a PR since it's so small anyways

**Comment by jonathanperret** [comment]
Note that while it's true that the OIDC spec prohibits using wildcards when specifying allowed `post_logout_redirect_uri`s, it seems common for them to be allowed, e.g. Keycloak lets you do it without even a warning, while `node-oidc-provider` has some support even though they strongly discourage it (https://github.com/panva/node-oidc-provider/blob/main/recipes/redirect_uri_wildcards.md).

Besides users who might have connected an OIDC provider with flexible logout URI policy (I doubt there is a significant number of those), changing the logged-out page from `/o/my-team/signed-out` to `/signed-out` also impacts non-OIDC users. For example, I just tested that if you sign in again from `/o/my-team/signed-out` you do end up in `/o/my-team/`, so some context is lost by going to `/signed-out`.

Not that I think it is a very significant impact, but I don't have the data to decide.

I can think of an alternative implementation from #1246 that would satisfy both the OIDC requirement of a stable logout URI and the desire to end up on an org-specific post-logout URI: we could use the `state` parameter of the RP-initiated logout and give the OIDC provider a fixed logout URI which would be another callback that redirects to the actual signed-out page. This is more work though, and again I don't know whether it's worth it.

**Comment by georgegevoian** [comment]
@jonathanperret's proposal to use `state` and a fixed logout URI is how the SaaS version of Grist handled logouts a few years ago (back when it still used Cognito's login page): there was a `/logout-ok` callback that received `state` containing a redirect URL to the signed out page (e.g. `/o/:oid/signed-out`).

For working with `state`, we've used the permit store in the past (see `Permit.ts`). You can call `setPermit` to store some values to remember, which gives you back a key. You can pass that key around (like `state`), and call `getPermit` with it to get back the stored values. You can set a reasonable TTL on permits, and manually clean them up with `removePermit`.

I recall `SamlConfig.ts` made use of it if you'd like an example to look at. The SaaS version of Grist also uses it, for redirecting logins to the previous page the user was on. For the latter, the code isn't in this repo, but here's a relevant snippet:

```javascript
/**
 * A Permit that contains login-related state. Used for remembering the
 * URL a user was redirected from before login (`url`), and protecting against
 * request forgery during the Google Sign-In flow (`sessionId`).
 */
interface LoginStatePermit {
  url: string;
  sessionId: string;
}

/**
 * The hosted Grist login API.
 *
 * Encompasses all login-related endpoints, including account login and registration
 * (Google or Cognito), password change or reset, MFA, and more.
 */
class Login implements GristLoginMiddleware {
  ...
  private readonly _gristServer: GristServer;
  ...
  /**
   * Retrieves a login state permit with key `state`, if it exists.
   */
  private async _getLoginStatePermit(state: string): Promise<LoginStatePermit | null> {
    const permitStore = this._gristServer.getExternalPermitStore();
    const prefix = permitStore.getKeyPrefix();
    return await permitStore.getPermit(prefix + state) as LoginStatePermit | null;
  }

  /**
   * Sets a new login state permit. Returns a key that can be passed to
   * `_getLoginStatePermit` to retrieve the permit.
   */
  private async _setLoginStatePermit(permit: LoginStatePermit): Promise<string> {
    const permitStore = this._gristServer.getExternalPermitStore();
    const permitKey = await permitStore.setPermit(permit, 1000 * 60 * 60 * 24);
    return permitKey.replace(permitStore.getKeyPrefix(), '');
  }

  /**
   * Removes a login state permit with key `state`.
   */
  private _removeLoginStatePermit(state: string): Promise<void> {
    const permitStore = this._gristServer.getExternalPermitStore();
    return permitStore.removePermit(permitStore.getKeyPrefix() + state);
  }
  ...
}
```

**Comment by vviers** [comment]
@georgegevoian just to clarify, do you expect us to implement what you propose, or is the PR ok as it is ?

**Comment by georgegevoian** [comment]
> @georgegevoian just to clarify, do you expect us to implement what you propose, or is the PR ok as it is ?

If you're comfortable with the changes in the PR, they're ok with me too.

It looks like we've narrowed down the possible corner cases, and I'd agree that it seems like impact will only be to a minimal subset of users. It'd be good to test these, and make sure remediation steps work as expected, as part of the review before merging, just to test our assumptions.

It would be worth following up on this at some point in the future - in particular, to try to preserve more context during the signup flow (for mitigating all the possible issues pointed out). On a related note, I wonder if there's a more general approach we could come up with for redirects that would be agnostic to the authentication mechanism (maybe some reusable hook).

**Comment by vviers** [comment]
@georgegevoian if you like @jonathanperret 's solution better (https://github.com/gristlabs/grist-core/commit/6021a344e597fe1fc660e05fd650e3c6585fa7a6) I'm happy to use this instead :)

**Comment by georgegevoian** [comment]
> @georgegevoian if you like @jonathanperret 's solution better ([6021a34](https://github.com/gristlabs/grist-core/commit/6021a344e597fe1fc660e05fd650e3c6585fa7a6)) I'm happy to use this instead :)

Let's go with @jonathanperret's approach. Thank you both!
