### ISSUE TITLE
Make it more obvious that breadcrumb items are editable

### ISSUE THREAD

**Issue by manuhabitela** [gristlabs/grist-core#1250]
### Describe the problem to be solved

:wave:

Hey, small thing here but I feel it's not really obvious that the document name and page name are editable in the breadcrumbs in the top. I feel like the fact that it's a breadcrumb, we are not used that such UI elements can be edited.

So there is some questioning at first: how do I rename my document?

Then I hover my mouse on the name and I'd admit I feel the UI is also here a bit hard to directly understand we can modify it. The cursor changes to an editable but again, we are not used to being able to edit normal text as it, visually I feel it could be more explicit.

### Describe the solution you would like

I feel we could be more explicit that this is the place to edit the document name:

- maybe by adding an icon next to editable content. I admit this could make the UI a little more noisy all the time for just this, maybe not what we want, but at least it's 100% explicit now,
- or at least having the hover effect be more explicit that this is editable content, by having something more visually looking like an input when hovering/focusing

![image](https://github.com/user-attachments/assets/8152b68b-5e74-4a56-9bcc-7923a603687a)
![image](https://github.com/user-attachments/assets/2ea38a34-9895-439c-9739-4b06e91049e3)

What do you think? :)

**Comment by lusebille** [comment]
Linked to ticket #1171

**Comment by manuhabitela** [comment]
Oh sorry I didn't see the earlier issue. I guess we can close this?

**Comment by dsagal** [comment]
@manuhabitela , could you review the design in #1171 for accessibility? That one's marked as "ready to dev", so if looks OK from a11y standpoint, then I propose adding the `Accessibility` label to #1171 and closing this issue as a duplicate.

**Comment by manuhabitela** [comment]
You are right, left a small comment on it but yeah, this issue is not necessary anymore.
