### ISSUE TITLE
New homepage : use DSFR color theme everywhere

### ISSUE THREAD

**Issue by lusebille** [gristlabs/grist-core#1267]
In the new homepage some styling colors are missing , actually somes elements are still green, please use light blue #E3E3FD for background (tutorial progress bar,' start a new document' block ) instead of light green.
By the way, I'm attaching to these tickets good svgs for 'webinar' block icon and 'more ressources' block.
Please tell me if something is missing @hexaltation @fflorent 

In prod : 
![Image](https://github.com/user-attachments/assets/af415dda-0f0f-4372-8b8c-f40c7f68ffc9)

In figma :
![Image](https://github.com/user-attachments/assets/e63dff39-2f97-47c5-a7be-d906bc95e5f6)

[illustrations.zip](https://github.com/user-attachments/files/17391614/illustrations.zip)

**Comment by hexaltation** [comment]
Hello @lusebille ,

I think it's the wrong place for this issue which only concerns DINUM.
Can you put it on right project ?

https://github.com/numerique-gouv/dockerfiles

Thanks
