### ISSUE TITLE
Help with host url

### ISSUE THREAD

**Issue by kekonn** [gristlabs/grist-core#129]
Hi,

I installed the official unRaid version and I host it behind a reverse proxy. I have an issue with the url the app detects though. It sees the local port of the docker container, but not the port from the reverse proxy, thus it generates the wrong urls. 

Which env vars should I set tot fix this? The documentation wasn't entirely clear. I am looking for something like BASE_URL, but proper reverse proxy detection would be even better.

It seems the static resources load fine, but the urls that start with /o don't (they include the docker port).

I've tried setting GRIST_ADAPT_DOMAIN, GRIST_DOMAIN and GRIST_SERVE_SAME_ORIGIN with no luck.

**Comment by acupofjose** [comment]
Agreed - in the meantime, this comment seemed to address the issue for me:

https://github.com/gristlabs/grist-core/issues/44#issuecomment-1019269857

**Comment by paulfitz** [comment]
Agree we could do better here. The environment variables APP_DOC_URL and APP_HOME_URL are the key ones to set, as @acupofjose pointed to. I'm not a user of unRaid, would you happen to have a pointer to the default configuration it uses for Grist? Is it this: https://github.com/bonedrums/unraid-templates/blob/main/unraid-grist/grist.xml

**Comment by kekonn** [comment]
For some reason after I make those changes, it starts redirecting to one of my other services.

**Comment by paulfitz** [comment]
Maybe your case is now like #130? If so, setting `GRIST_SINGLE_ORG=docs` may help. Grist can serve multiple "team sites" identified with different domains, plus a special "personal site", and it looks like we haven't nailed turning all that off for self-hosting.

**Comment by kekonn** [comment]
Oh right. I already have a docs subdomain. I am hosting grist on grist.domain.tld and I would like it to see that domain as the top domain, so docs should be docs.grist.domain.tld. Would the single org setting fix that?

**Comment by georgegevoian** [comment]
Hey @kekonn. The single org setting makes it so that grist.domain.tld implicitly points to docs as the site, with your URLs no longer including mentions of docs (in either the subdomain, or in the path after /o/). You shouldn't see URLs like docs.grist.domain.tld anymore when single org is set, and it should hopefully clear up the redirect issue.

**Comment by kekonn** [comment]
FYI, just setting those vars didn't do it for me, but there was an update this week and that in combination with the vars did fix it.
