### ISSUE TITLE
Python 2 gvisor sandboxes are broken

### ISSUE THREAD

**Issue by jonathanperret** [gristlabs/grist-core#1298]
### Describe the current behavior

Since Grist 1.2.1, when using the `gvisor` sandbox flavor, documents that use the Python 2 engine can't be edited anymore.

### Steps to reproduce

1. Launch Grist 1.2.1 using the `gvisor` sandbox flavor:
```
$ docker run --rm -ti -p 8484:8484 -e GRIST_SANDBOX_FLAVOR=gvisor gristlabs/grist:1.2.1
```
2. Navigate to http://localhost:8484, create a document, go into its settings and change the Python version to `python2`.
3. Reload the document
4. Observe the dreaded `PipeToSandbox is closed` error message.

Alternatively, here's an automated test for the issue, that can be run from a clone of https://github.com/gristlabs/grist-core:

```
$ GREP_TESTS='should support basic editing' \
   TEST_IMAGE='-e GRIST_SANDBOX_FLAVOR=gvisor -e PYTHON_VERSION_ON_CREATION=2 gristlabs/grist:1.2.1' \
   yarn test:docker
```

Substituting `1.2.0` for the version number causes this test to pass.

### Describe the expected behavior

The document should keep being editable when Python 2 is selected.

### Where have you encountered this bug?

- [ ] On [docs.getgrist.com](https://docs.getgrist.com)
- [X] On a self-hosted instance

**Comment by fflorent** [comment]
@jonathanperret Shouldn't this PR be closed now that #1300 is merged?
