### ISSUE TITLE
Filtering possible values in reference lists

### ISSUE THREAD

**Issue by torwag** [gristlabs/grist-core#133]
Sometimes, one would like to create a reference but only enable the selection of a subset of that reference. 
This becomes particular useful if the list is otherwise very large. It would be nice, if one could assign a filter to that list first, so hat the entire list gets shorten.
Example:
In the table project, I would like to assign one or more managers to a project. I create a "Managers" column and make a reference list which points to my employee table. However, in that table, all employees and their different roles are listed. Obviously I do not want to assign Bob, the 17-year-old intern, to become the manager of a project. So what I need is to say

Create a reference list from the table employee show name, but only if in table employee the column role is "manager".

**Comment by dsagal** [comment]
You can accomplish that today by adding to the `Employees` table another column, say, `Name_If_Manager` with a formula like `$Full_Name if $Role == "manager" else ""`. This will duplicate the `Full_Name` column but only for managers.

Then in the `Projects` table, set your `Managers` column to point to table `Employees` and for "SHOW COLUMN" select `Name_If_Manager`. This will limit the dropdown to non-empty values, which happen to be only the managers.

**Comment by torwag** [comment]
Indeed, that looks like a good workaround. Thanks

**Comment by NetLancer** [comment]
How about dependent dropdowns, where (my case) the previous column dictates (should filter out) the resulting dropdown list on the next column ? 
Somehow the lookupRecords formula didn't work for me..
Below is a bit simplified scheme:
[![Construction-Sites-table3.png](https://i.postimg.cc/g0gmC9wt/Construction-Sites-table3.png)](https://postimg.cc/yJ3MRby0)

**Comment by NetLancer** [comment]
The upper table's the one to implement dependent dropdown on "Building" field which depens on "Contractor"
