### ISSUE TITLE
Markdown field not updating display value inside Card on standalone version

### ISSUE THREAD

**Issue by daniti** [gristlabs/grist-core#1330]
### Describe the current behavior

Markdown fields don't always update the display value on the standalone version in MacOS.
I prepared an example at this link: https://docs.getgrist.com/3WqtcrkeNs7S/Markdown-Bug?utm_id=share-doc

John and Jane both have interactions linked to them. Jake doesn't.
From the Contacts page, you can switch between contacts and the interactions show correctly.
If you download the document and open it in the standalone version on MacOS, when switching between John or Jane to Jake, the interaction will still show the value linked to the previously selected contact.
For example, going from John to Jake, the field should be empty, but you will see the interaction "John 2".

### Steps to reproduce

1. Download the example at https://docs.getgrist.com/3WqtcrkeNs7S/Markdown-Bug?utm_id=share-doc
2. Open it in the standalone app on MacOS
3. Switch between John and Jake
4. The interaction card will show an interaction linked to the wrong record

### Describe the expected behavior

The field should show the correct record. Empty in this case.

### Where have you encountered this bug?

- [ ] On [docs.getgrist.com](https://docs.getgrist.com)
- [ ] On a self-hosted instance

### Instance information (when self-hosting only)

* Grist instance:
  * Version:
  * URL (if it's OK for you to share it):
  * Installation mode: docker/kubernetes/...
  * Architecture: single-worker/multi-workers

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant:

**Comment by dsagal** [comment]
I can confirm this is an issue in Grist Desktop 0.3.0, but it's been fixed upstream (i.e. here in `grist-core`) since then. (I am guessing this is the commit in grist-core which fixes it: https://github.com/gristlabs/grist-core/commit/89468bd9f0a8befe6f419f3857006990111d37c6). So fixing it in Grist Desktop is a matter of releasing a fresher version.

Cc'ing @Spoffy who may know when the next Grist Desktop release is planned.
