### ISSUE TITLE
Grist behind Nginx Reverse Proxy not working -> There was an error: no workers.

### ISSUE THREAD

**Issue by onyxkyr** [gristlabs/grist-core#142]
Hello,

I am currently trying to setup a docker-deployed grist behind an nginx reverse proxy.
I got grist working locally, but I can't get it to work behind my nginx reverse proxy. The website loads, but I can't open any documents.
When trying to create documents, it get the following error -> 
`There was an error: no workers.`
![grist_no workers](https://user-images.githubusercontent.com/75786462/154848901-6a88e08c-e81f-4fbf-a076-805a910cf614.png)

Following are my docker-compose config, and the relevant part of the nginx reverse proxy config.
###MYDOMAIN.tld### is a placeholder.

## docker compose
version: '3.3'
services:
  grist:
    image: gristlabs/grist
    environment:
      - DEBUG=1
      - GRIST_SINGLE_ORG=docs
      - APP_DOC_URL=https://grist.###MYDOMAIN.tld###
      - APP_HOME_URL=https://grist.###MYDOMAIN.tld###
      - GRIST_DEFAULT_EMAIL=test@###MYDOMAIN.tld###
    ports:
      - '8484:8484'
    volumes:
      - /var/grist:/persist

## nginx cfg

location / {
        # redirect all HTTP traffic
        proxy_pass http://INTERNAL-IP:8484;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        #proxy_set_header Connection "upgrade";
        proxy_set_header Connection $http_connection;
    }

**Comment by paulfitz** [comment]
Sorry for this problem @onyxkyr. This could happen if, within the container, the `APP_DOC_URL` is not reachable. If there is a url that will work within the container (but not from a visitor's browser), such as http://localhost:8484, you can set it with `APP_DOC_INTERNAL_URL`.

(These `APP_*_URL`s are only really useful for large deployments and just add complexity when everything is in the same container. Will work on simplifying this.)

**Comment by onyxkyr** [comment]
Thank you very much @paulfitz , that fixed the problem for me :)
