### ISSUE TITLE
[Feature Request]: Continue posting docker images with tags

### ISSUE THREAD

**Issue by stavros-k** [gristlabs/grist-core#155]
I can see on Github that there is a `0.7.4` tag, but on dockerhub there last is `0.7.3`.

Is there a reason `0.7.4` is not there?
Or it's just the fact that `0.7.4` is not "done" yet?

Thanks

**Comment by paulfitz** [comment]
Hi @stavros-k, thanks for pointing this out. I backfilled `0.7.4` on dockerhub, and added an up-to-date `0.7.5`.

**Comment by stavros-k** [comment]
> Hi @stavros-k, thanks for pointing this out. I backfilled `0.7.4` on dockerhub, and added an up-to-date `0.7.5`.

Thanks for the quick response!

Is there a CI in place for automated image builds? If there is we can close this issue :)

If not, any plans to do so?
Thanks!

**Comment by paulfitz** [comment]
There is an automation for updating `latest`, which currently serves a little idiosyncratically as a nightly build https://github.com/gristlabs/grist-core/blob/main/.github/workflows/docker_latest.yml

There is an automation for adding tagged images when releases are published https://github.com/gristlabs/grist-core/blob/main/.github/workflows/docker.yml. We don't yet have any particular policy about when releases are published.

I'd expect at some point that what we currently push to `latest` will instead go to a `nightly` tag, and that `latest` would be tied to the latest published release.

**Comment by stavros-k** [comment]
I think then it can be closed, unless you want to keep it on for some kind of reminder to move the latest builds to nightly and link latest to the actual releases.
