### ISSUE TITLE
error and feature request: choose column type when import a CSV file

### ISSUE THREAD

**Issue by helmut72** [gristlabs/grist-core#157]
my CSV looks something like this:

```CSV
name, hwversion, description
server1, vmx-15, some notes
server2, vmx-12, other notes
...

```
When I want to import this file, column "hwversion" will be converted automatically to type "date", vmx-15 becomes 2015-01-01.

This looks like an error. All at all it would be cool to choose the column type at this stage.

Thank you :)

**Comment by paulfitz** [comment]
Hi @helmut72, the date guessing is embarrassing (more examples of Grist getting this wrong: https://community.getgrist.com/t/importing-data-from-google-sheets-alphanumeric-fields-being-converted-to-dates/606). There are significant improvements in the works.

**Comment by paulfitz** [comment]
I believe this is fixed in the latest version of Grist. Imports are still not configurable, but should be lossless. `hwversion` would no longer be treated as a date.

**Comment by helmut72** [comment]
Thanks, will try it soon!
