### ISSUE TITLE
[Feature Request]: organized page by folder

### ISSUE THREAD

**Issue by tendertree** [gristlabs/grist-core#158]
<img src="https://i.imgur.com/77jMhXd.png" width="500">

it would be help to give a folder to manger page.
I think it could help when pages increase more and more

**Comment by dsagal** [comment]
@tendertree, this is actually already possible, just a bit differently, see https://support.getgrist.com/page-widgets/#pages:

<img width="366" alt="rename_pages1" src="https://user-images.githubusercontent.com/1091143/156453169-4606b086-1294-42c5-8a68-e360de57d79f.png">

The trick to creating this nesting is to hold one page over another when dragging -- that makes a nested group. The only difference with your suggestion is that the "folder" is itself a page.
