### ISSUE TITLE
Unauthorized Origin response for WebExtensions

### ISSUE THREAD

**Issue by encima** [gristlabs/grist-core#16]
Creating a POST API request from the background script of a Chrome Extension (have not tested in FF yet) results in an Unauthorized Origin response. I assume this is because of the function referenced below.

Webextensions cannot make POST requests from their `content_scripts` anymore and the `background` script is the only way moving forward. That does mean that origin is set to the ID of the extension (i.e. `chrome://fcdlpgnheghipfpjodagagpdfejijfoi`) and I believe this fails the trust check. Could the handlers for extensions also be added to the trusted domains?

https://github.com/gristlabs/grist-core/blob/9f234b758d034ff258c85e715b432d79e9823a08/app/server/lib/FlexServer.ts#L1531

**Comment by paulfitz** [comment]
What kind of POST requests are you looking to make? Do they have a document id in them? We do have a plan to allow custom origins for document requests. If there were an option to add a list of trusted domains to a specific document, would that meet your need?
