### ISSUE TITLE
Download button not working

### ISSUE THREAD

**Issue by mrtolkien** [gristlabs/grist-core#164]
Running Grist locally, none of the export options seem to work.

I get an `auth_interrupted` error when trying to use any of those functions. The rest of the webapp works perfectly.

**Comment by paulfitz** [comment]
Thanks for reporting this @mrtolkien. How do you run Grist? Via docker or built from source? Any special configuration? 

I'd expect that error message for Google Drive exports only. To use Google Drive exports, you'll need a `GOOGLE_CLIENT_SECRET` variable configured. I can talk you through that if other export options (e.g. csv, download) are working. If those options aren't working, something bigger is wrong.

**Comment by mrtolkien** [comment]
After doing some more testing, I managed to make it work:
- Downloading was not working in Chrome on Mac OS
- It's working on Chrome in Windows and Linux

I'm unsure as to why that was the case and I'll take another look tonight on Mac OS.
