### ISSUE TITLE
Column rules do not apply to new rows

### ISSUE THREAD

**Issue by MHOOO** [gristlabs/grist-core#167]
When using the bottom row of any table to insert a new entry into a table, column rules are not applied.
### Example

* This simple rule on a tables only column
![2022-03-12_21-12-50_grist-core-restrictions](https://user-images.githubusercontent.com/296456/158033555-6e2ab5ed-529c-4a04-a486-c5572dbc5334.png)
* Still allows for the following state, when simply clicking on the toggle at the bottom row
![2022-03-12_21-12_grist_core-bug](https://user-images.githubusercontent.com/296456/158033591-a8a3ae46-e6dd-4613-8f89-48ae47e4ec35.png)
* This also happens with any other restriction/data type, so it is not specific to the checkbox

**Comment by paulfitz** [comment]
Hi @MHOOO, for inserting new entries, the rules related to creation (C) are the ones enforced. So you could achieve your desired result with:
![Screenshot from 2022-03-14 09-47-56](https://user-images.githubusercontent.com/118367/158185528-85195290-bd41-4997-96e6-c50180736b5a.png)
Or just:
![Screenshot from 2022-03-14 09-50-47](https://user-images.githubusercontent.com/118367/158185787-6e394db5-e734-4668-afdb-105de32bbbe0.png)
I can see why that is confusing though.

**Comment by MHOOO** [comment]
Oh, I see. I've now restricted the creation of a new row using the dummy row at the bottom, by only allowing the user to write in one particular column. This way, I can prevent them from accidentally putting a row into an invalid state. It still feels like a workaround, but I can live with this one.
Thanks for clearing that up!
