### ISSUE TITLE
Remove Brackets from Choice List Field in the Custom Invoice

### ISSUE THREAD

**Issue by nittygrittytechy** [gristlabs/grist-core#188]
Hello,

I hope this is the right place to ask this question. 
https://community.getgrist.com/t/remove-brackets-from-choice-list-field-in-the-custom-invoice/888

Can you please help me with this.

Thank you
Jennifer

**Comment by paulfitz** [comment]
Hi @nittygrittytechy, looks like someone has answered in the forum.
