### ISSUE TITLE
No Deduction or Taxes added in .js code for Custom Invoice

### ISSUE THREAD

**Issue by nittygrittytechy** [gristlabs/grist-core#189]
Hello,

I noticed on your custom invoice within the invoice.js file, it does not provide the calculations to deduct the Deduction Column and add taxes under the Taxes column.

https://support.getgrist.com/examples/2020-08-invoices/#preparing-invoices

Can you please provide coding for the Deduction and Taxes Column.

That way, when a deduction is added, it takes away from the total.
If taxes are added, it adds to the Total.
Or if Deductions and Taxes are added, then the Total changes to reflect the new amount owed.

![image](https://user-images.githubusercontent.com/72896149/163683138-0f895d19-ca4d-4693-81bc-64193209002b.png)

Thank you
Jennifer

**Comment by paulfitz** [comment]
Good point. I think https://github.com/gristlabs/grist-widget/pull/22 will fix this. You can try it with a custom widget URL of https://deploy-preview-22--boisterous-sunburst-a5c941.netlify.app/invoices/
