### ISSUE TITLE
is there way to get reference list in fomula?

### ISSUE THREAD

**Issue by tendertree** [gristlabs/grist-core#191]
<img src="https://i.imgur.com/d4UenML.png">
I try to use random function by fomula to get some variation value. 
and I try to choice one thing randomly in the list of [a,b,c,d]

but I don't know how to get reference list in fomula 
I try to access by using [table1], but it doesn't work 
```
import random
list = [Table1].lookupRecords([A]=$[B])
random.choice(list)
```

is there a good way to get "list" from reference info ? or directly access other pages name list? ``

**Comment by dsagal** [comment]
Try this:
```
import random
records = Table1.lookupRecords(A=$B)
random.choice(list(records))
```
I am assuming the square brackets are for illustration purposes; in real code you shouldn't have them. The other issue is that the result of `lookupRecords` is a special object that's not a valid argument for choice, but turning it into a list (the `list(records)` bit in my example) should make it work.

**Comment by tendertree** [comment]
thanks ! it work :)
