### ISSUE TITLE
Document Page "Not Connected"

### ISSUE THREAD

**Issue by oc7opu5** [gristlabs/grist-core#226]
Hi I have set up grist [self host] but my document page shows "Lost Connection" screenshot attached. I am using nginx reverse proxy, and accessing grist with my domain [https://grist.mydomain.com], the issue causes in document page.
my settings are:

```

> DEBUG=1
> GRIST_SINGLE_ORG=docs
> GRIST_HOST=0.0.0.0
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> NODE_VERSION=14.20.0
> YARN_VERSION=1.22.19
> PYTHON_VERSION_ON_CREATION=3
> GRIST_ORG_IN_PATH=true
> GRIST_SINGLE_PORT=true
> GRIST_SERVE_SAME_ORIGIN=true
> GRIST_DATA_DIR=/persist/docs
> GRIST_INST_DIR=/persist
> GRIST_SESSION_COOKIE=grist_core
> GVISOR_FLAGS=-unprivileged -ignore-cgroups
> GRIST_SANDBOX_FLAVOR=unsandboxed
> TYPEORM_DATABASE=/persist/home.sqlite3
> GRIST_DEFAULT_EMAIL=myemail@gmail.com
> PORT=8484
> APP_DOC_INTERNAL_URL=https://grist.mydomain.com
> APP_DOC_URL=https://grist.mydomain.com
> APP_HOME_URL=https://grist.mydomain.com

```

Please Help.

![grist document issue](https://user-images.githubusercontent.com/98937790/180866860-42faebb7-b181-46d5-8c1b-2b233e884194.png)

**Comment by paulfitz** [comment]
I'd guess that websocket connections are not getting through your reverse proxy. Can you check if you've enabled support for them?

**Comment by oc7opu5** [comment]
Thank you so so much. That's the only thing I kept off, damn! You are a
savior man.

By the way, can you please help me with setting up 0auth? I never done that
before, so I am struggling with that. Also wanted to keep multiple members.

It will be a great help too.

Thanks Again.

**Comment by paulfitz** [comment]
Auth issue seems to be covered in https://github.com/gristlabs/grist-core/issues/227
