### ISSUE TITLE
Unexpected place for "Document settings" menu

### ISSUE THREAD

**Issue by yohanboniface** [gristlabs/grist-core#232]
Hi again :)

User feedback: I've not been able to find by myself the "Document Settings" menu, which is now under the "User" icon:

![image](https://user-images.githubusercontent.com/146023/181754162-70d34c17-2997-45a5-921d-b9ec7894da46.png)

I'd have expected a classic [cogwheel](https://thenounproject.com/search/icons/?iconspage=1&q=cogwheel) directly visible on the document page.

My 2 cents :)

**Comment by paulfitz** [comment]
More evidence that "Document Settings" dialog is hard to find: https://github.com/gristlabs/grist-core/issues/271#issuecomment-1253433978

**Comment by vviers** [comment]
Should we add a `needs_design` tag ? Seem like this issue is very much a UX/I one

**Comment by dsagal** [comment]
Actually, I think this task is done: there is now a `⚙️ Settings` page under Tools in the left-side panel, which opens document settings. This was added in January.
