### ISSUE TITLE
UX improvement: allow user to change page with with a click on the label

### ISSUE THREAD

**Issue by LouisDelbosc** [gristlabs/grist-core#235]
We would like to allow users to rename the page from the interface using a click like it can be done with columns inside.

As I would like to contribute more to grist-core, I will soon open a PR for this issue.

**Comment by anaisconce** [comment]
Ooh, I've been wanting this, too! Thank you, Louis!

**Comment by LouisDelbosc** [comment]
Yes I plan to do it like this 🙂
