### ISSUE TITLE
Create table over API

### ISSUE THREAD

**Issue by Razikus** [gristlabs/grist-core#250]
Hello, is there possibility to crate table over Grist API?

**Comment by paulfitz** [comment]
Yes, it is possible. We've been remiss in not creating a friendly documented endpoint for it, but you can see it done in a testcase here: https://github.com/gristlabs/grist-core/blob/4554de661eb7373d27814973907f471c95792f30/test/server/lib/DocApi.ts#L651-L661

POST to this endpoint `.../api/docs/<docId>/apply` with the following kind of JSON body:
```
[ 
  ["AddTable", "TableName", [{id: 'Column1Name'}, {id: 'Column2Name'}]]
]
```
You can specify types of columns, and initialize formulas, see e.g. https://github.com/gristlabs/grist-core/blob/4554de661eb7373d27814973907f471c95792f30/sandbox/grist/testscript.json#L1224-L1227

**Comment by Razikus** [comment]
Ok okay! I see now how to do it!
I was inspecting a websocket also so i can extract all messages from WS, and then apply by this endpoint

Cool!

**Comment by paulfitz** [comment]
Update: there is dedicated API support for creating tables and columns now:
  * [POST /tables](https://support.getgrist.com/api/#tag/tables/paths/~1docs~1%7BdocId%7D~1tables/post)
  *  [POST /columns](https://support.getgrist.com/api/#tag/columns/paths/~1docs~1%7BdocId%7D~1tables~1%7BtableId%7D~1columns/post)
