### ISSUE TITLE
Autocomplete emails with known members

### ISSUE THREAD

**Issue by yohanboniface** [gristlabs/grist-core#253]
Hi,

When managing members, I think it would be very helpful to have an autocomplete with emails of known members.

![image](https://user-images.githubusercontent.com/146023/186137542-e132cd13-8ed6-49f7-abde-55e25e0fbfc9.png)

So not only users that are already members, but any user already in the system, or in the team maybe. This may be a configuration, as I guess in getgrist.com you'll not want to have all emails exposed to anybody of course.

This is something that we could work on if you think it is worth it.

**Comment by anaisconce** [comment]
That's a great idea and something we've been itching for, too! If you're willing, I'd be thrilled to see it. To be clear, are you talking about adding team members to a team, or to a document? 

### If to a team...

Are you envisioning pulling a list of emails that are part of the same email domain, such as @something.gouv.fr ?

### If to a document...

> So not only users that are already members, but any user already in the system, or in the team maybe.

Any user in the team makes sense to me.

> This may be a configuration, as I guess in getgrist.com you'll not want to have all emails exposed to anybody of course.

This is something we've discussed internally before. If there were a configuration, it would be at the team site level to determine whether or not someone who creates a document should have access to the list of team members when managing their documents' users.

I wonder if we're over thinking this. Only **document owners** can manage the document's users. Document editors and viewers cannot see the "manage users" dialog. While it's true that document owners may not be team owners, I wonder if this difference is as sensitive as we think. In most team collaboration tools, the desire is for easy collaboration within the team, and typically the entire team is exposed to facilitate this.  If we wanted to protect emails, we could expose the team member list as user names, and not emails. In that case, the document owner could select from a list of team member names, or add a new email to invite someone external.

If only people with permission to create documents (team editors and owners) can see team member names, maybe that's fine. 

Curious what @dsagal and @paulfitz think, too.

Related, we have ideas to make sharing permissions clearer and more flexible. So we could include this configuration in the near future if there is a desire for it.

**Comment by dsagal** [comment]
I am glad to see this PR, and I am extra glad for your offer to work on it. Definitely worth it.

Let me share a couple of pointers to the code for implementation:
- [app/client/lib/autocomplete.ts](https://github.com/gristlabs/grist-core/blob/main/app/client/lib/autocomplete.ts) - the main `Autocomplete` class. It's templated, and you provide it with options for how to turn typed search text into a list of items, and how to render each item.
- [app/client/lib/ACIndex.ts](https://github.com/gristlabs/grist-core/blob/main/app/client/lib/ACIndex.ts) - you construct an index with a list of items, and give its `search` method to the `Autocomplete` constructor. It also contains a `buildHighlitedDom()` function, which works in conjunction with `Autocomplete` to highlight matching bits of text in the list of autocomplete suggestions.
- [app/client/ui/UserItem.ts](https://github.com/gristlabs/grist-core/blob/main/app/client/ui/UserItem.ts) - styling for DOM to render a user (what items in the autocomplete should probably look like).

You can see how `Autocomplete`, `ACIndex`, and `buildHighlightedDom` pieces are put together in [app/client/lib/ACSelect.ts](https://github.com/gristlabs/grist-core/blob/main/app/client/lib/ACSelect.ts).

As for what items to offer up, I believe that currently all users of the org (team site) are available in the browser when the Manage Users dialog is open, whether for a doc, a workspace, or the full team site. So right now, any document _owner_ (i.e. one who can open the Manage Users dialog) is able to get a list of all team site members and guests (guests are people with whom some document in the team site is shared at the document level, but who are not members  of the team site). In many cases, this is perfect. I'd say it's fine to use this list for autocomplete -- that's really its intended purpose.

But it means that giving someone _owner_ role might expose a bigger list of names and emails than expected (via the browser console today; via the autocomplete once its implemented). As @anaisconce said, we may want to adjust that, or add some controls at the site level. But that can be a separate change, unrelated to the autocomplete implementation.

**Comment by yohanboniface** [comment]
Thanks @anaisconce for yoru answer, and thanks @dsagal for your detailed inputs! :)

> If to a document...

In this case, I'd say that we allow searching in all team members, without the need of a setting. WDYT?

> If to a team...

This one if indeed more tricky, and that why I'd suggest a setting, but maybe at the "instance level", so it may only be an env var that could decide if when adding someone to a team, we could search in all members or not. Does that can be a first step ?

**Comment by LouisDelbosc** [comment]
Since I'm exploring team's right on grist I have a question (a bit related).

When having a workspace or document private by default, the only way to add a team is by sending an invite email. Why not having the same interface than others rights, and just having one which is `no rights` (or w/e) meaning the team cannot see or interact with the workspace/document ?

**Comment by anaisconce** [comment]
> In this case, I'd say that we allow searching in all team members, without the need of a setting. WDYT?

I agree, that's sensible!

>  so it may only be an env var that could decide if when adding someone to a team, we could search in all members or not. Does that can be a first step ?

Good question for @dsagal 

That's an interesting idea, @LouisDelbosc . If I am understanding correctly, you're suggesting that the full list of team members should always be shown. If a team member does not have access to a workspace/doc, simply say so.

Thinking out loud, if it remains a list view, it might be helpful to group members by access level first, then alphabetically. It may be easier to parse. Currently the way it sorts is a bit mysterious.

> Ben - no access
> Ana - owner
> Carla - editor
> Eugene - viewer
> Figaro - no access
> Dean - owner
> Georgette - viewer

^ That's harder for me to parse. 

> Ana - owner
> Dean - owner
>
> Carla - editor
>
> Eugene - viewer
> Georgette - viewer
>
> Ben - no access
> Figaro - no access

^ Easier to understand quickly who has access to what. The drawback is if I don't know Georgette's access, I have to hunt for her. Future improvements could make that better. Grouping and separating "no access" members in the list seems especially useful.

**Comment by anaisconce** [comment]
Thinking about it more, @LouisDelbosc  The issue with listing everyone who has no access is that in large orgs the list becomes very long and not helpful. 

It might be better to only serve the no-access team list while searching for a name, using auto complete. Here's a screenshot of what it could look like.

![image](https://user-images.githubusercontent.com/69366135/186227767-f269b220-0b8e-4892-8e74-26c5f59f381f.png)
 
In this example, the Manage Users pop-up would still only show all users who have owner/editor/viewer access to the document as it does today.

What's missing in that screenshot is the ability to add a new email. Could re-use the current UI and place it at the bottom of the list -- the way reference columns work. This is how the "add new email" UI element currently looks. 

![image](https://user-images.githubusercontent.com/69366135/186228203-d5085cf3-90a6-472d-9379-d5ad099918e7.png)

**Comment by LouisDelbosc** [comment]
@anaisconce it's look like a good idea.

To summarise:
1. have the input autocomplete team members with an `add email` at the end
2. sort by access rights then name in the list of available team member

Is there anything else we want to improve on this input ?

**Comment by LouisDelbosc** [comment]
Hello @dsagal, I'm trying my best to make change the simple input in [UserManager](https://github.com/gristlabs/grist-core/blob/main/app/client/ui/UserManager.ts#L549) but I need some help.

Seing [app/client/lib/ACSelect.ts](https://github.com/gristlabs/grist-core/blob/main/app/client/lib/ACSelect.ts), I suspect I have to modify the [MemberEmail](https://github.com/gristlabs/grist-core/blob/main/app/client/ui/UserManager.ts#L525) to be an AutoCompleteMemberEmail. I tried to make an external function (like ACSelect) but failed.

With @yohanboniface we thought maybe we could directly use *ACSelect* calling `buildACSelect` function. Do you think it is possible ?

What are the interface needed for an AutoComplete ? I need `ACUser` ?

Can you show me an example of the minimal AutoComplete possible ? I struggle to have this base to iterate over.

Thanks

**Comment by LouisDelbosc** [comment]
I need some help @dsagal.

Here my autocomplete input inspired by ACSelect followed by the component calling it:

```ts
function buildACMemberEmail(
  owner: IDisposableOwner,
  options: {
    acIndex: ACIndex<ACUserItem>,
    emailObs: Observable<string>,
    save: (value: string, item: ACUserItem|undefined) => Promise<void>|void
  },
  ...args: DomElementArg[]
) {
  const {acIndex, emailObs, save} = options;
  const acHolder = Holder.create<Autocomplete<ACUserItem>>(owner);
  let emailInput: HTMLInputElement;

  const isOpen = () => !acHolder.isEmpty();
  const acOpen = () => acHolder.isEmpty() && Autocomplete.create(acHolder, emailInput, acOptions);
  const acClose = () => acHolder.clear();
  const finish = () => { acClose(); emailInput.blur(); };
  const revert = () => { emailInput.value = emailObs.get(); finish(); };
  const commitOrRevert = async () => { (await commitIfValid()) || revert(); };

  const commitIfValid = async () => { /* stuff */ };

  const onMouseDown = (ev: MouseEvent) => { /* stuff */ };

  const acOptions: IAutocompleteOptions<ACUserItem> = {
    menuCssClass: `${menuCssClass} test-acselect-dropdown`,
    search: async (term: string) => acIndex.search(term),
    renderItem: (item, highlightFunc) =>
      cssSelectItem(buildHighlightedDom(item.label, highlightFunc, cssMatchText)),
    getItemText: (item) => item.value,
    onClick: commitIfValid,
  };

  return cssEmailInputContainer(
    cssMailIcon('Mail'),
    emailInput = cssEmailInput(emailObs, {}, 
      {type: "email", placeholder: "Enter email address but smarter"},
      dom.on('input', acOpen),
      dom.on('focus', (ev, elem) => elem.select()),
      dom.on('blur', commitOrRevert),
      dom.on('input', acOpen),
      ...args
    ),
    dom.on('mousedown', onMouseDown),
  );
}
```

```ts
export class ACMemberEmail extends Disposable {
  public email = this.autoDispose(observable<string>(""));
  private _isValid = this.autoDispose(observable<boolean>(false));

  private _commit() {
    console.log('commit');
  }

  public buildDom(members: any) {
    const toto = members.map((member: IEditableMember) => ({value: member.email, label: member.email, cleanText: member.email}));
    const acIndex = new ACIndexImpl<ACUserItem>(toto);

    const enableAdd: Computed<boolean> = computed((use) => Boolean(use(this.email) && use(this._isValid)));
    return buildACMemberEmail(this,
      {acIndex, emailObs: this.email, save: (x, y) => (console.log(x, y))},
      inputMenu(() => [
        cssInputMenuItem(() => this._commit(),
          cssUserImagePlus('+',
            cssUserImage.cls('-large'),
            cssUserImagePlus.cls('-invalid', (use) => !use(enableAdd))
          ),
          cssMemberText(
            cssMemberPrimary('Invite new member'),
            cssMemberSecondary(
              dom.text((use) => `We'll email an invite to ${use(this.email)}`)
            )
          ),
          testId('um-add-email')
        )
      ], {
        // NOTE: An offset of -40px is used to center the input button across the
        // input container (including an envelope icon) rather than the input inside.
        modifiers: {
          offset: { enabled: true, offset: -40 }
        },
        stretchToSelector: `.${cssEmailInputContainer.className}`,
        attach: null,
        boundaries: 'document' as any, // TODO: Update weasel.js types to allow 'document'.
      }),
      cssEmailInputContainer.cls('-green', enableAdd),
      testId('um-member-new')
    );
  }
}
```

I have the following result and I don't have a good idea how to have my autocomplete result inside an `inputMenu` (since I have to put them inside the array).

Do you have an idea how to proceed ?

![Screenshot 2022-08-25 at 12 35 43](https://user-images.githubusercontent.com/11460746/186643122-ed6a1615-5fed-4ff7-80fe-4fbd26214280.png)

**Comment by dsagal** [comment]
I see a few things:
1. Drop `inputMenu` entirely. It's the poor-man's version of autocomplete, which the new way would completely replace.
2. The `renderItems` callback you provide in `acOptions` should build and return the nice little user card (with name/email/image)
3. The `search` callback needs to include an item for the special "add email" entry (and `renderItems` should know how to render that item). See how a similar thing is done for [Reference auto-complete](https://github.com/gristlabs/grist-core/blob/1c722014fa51352b35e44dc3d5261ac2c33190bb/app/client/widgets/ReferenceEditor.ts#L112) (see `_doSearch` and `renderACItem` functions). 

Also, regarding your points from previous message:

> 1. have the input autocomplete team members with an add email at the end

Yes

> 2. sort by access rights then name in the list of available team member

I don't think so -- in the autocomplete, the access rights for higher-level objects (workspace / team site) don't matter, so listing in order of name or email address seems best. In the list of users who do have access, same order would make sense (@anaisconce pointed out that the list today is essentially unsorted, which would certainly be nice to fix!) Between name and email, I think I'd prefer sorting by email, since that's how users are invited, and because it's a unique and more reliable identifier.

**Comment by LouisDelbosc** [comment]
I made some progress using @dsagal advices as you can see in the following screenshot.

<img width="566" alt="Screenshot 2022-08-30 at 18 10 02" src="https://user-images.githubusercontent.com/11460746/187487058-4449fd7d-5a33-4657-b3b1-9582ae6bc3fd.png">

However I have some trouble for the validation and adding existing users.

### Validation

In [MemberEmail Component](https://github.com/gristlabs/grist-core/blob/main/app/client/ui/UserManager.ts#L549) you seems to use an html input validation which is tracked with an observable.

In my [component](https://github.com/LouisDelbosc/grist-core/blob/improve-input-team-member/app/client/lib/ACUserManager.ts#L133) (inspired by ACSelect), the native input validation is not trigger. Do you have any idea how to solve it ? Or maybe you have a new way of doing it now.

### Adding existing users

In the current input, the callback is adding new users but how can I manage existing users ? Do we have a function to use ? I'm not sure how to do it.

Thanks for your work, i'm not too far from a good result (even if there is some css to fix).

**Comment by dsagal** [comment]
Sorry about the slow response. This looks amazing -- just what I have wished for!

Glad you figured out using the question with ObsArray.

Regarding validation, no we don't have a particular way of doing it -- I don't think there is other code that's doing input validation together with auto-completion. It looks like you may have figured out how to make it work too, judging by a recent commit. If so, nice work! If not, let me know -- the approach seems right, and I can look closer if I can help with some details.

**Comment by LouisDelbosc** [comment]
I submit a PR and some improvement need to be done for the matching color on selected item.

@anaisconce do you have any suggestion ?

Here a screenshot from @paulfitz where you can see the issue:

<img width="839" alt="Screenshot 2022-09-07 at 11 36 07" src="https://user-images.githubusercontent.com/118367/188889127-30dfd3aa-c54a-42c5-b416-52aedc487b26.png">

**Comment by LouisDelbosc** [comment]
@paulfitz @dsagal @yohanboniface Does this issue is still relevant since the PR has been merged ?

**Comment by yohanboniface** [comment]
We may think about a later step: allowing autocomplete when in the "Manage Team Users" context, for example by searching through users without any team or (I guess only for self-hosted) searching in all users.

At least we have a scenario here: people will create their account but will not be attached to our (unique at this time) team. So having autocomplete may help. Plus there will be a case where people will be added directly in a workspace or document without being added to the team.

I'd say anyway there is room for thinking before coding more! :)

**Comment by vviers** [comment]
Let's open another issue should we want to dig this topic further :)
