### ISSUE TITLE
Export table as XLSX

### ISSUE THREAD

**Issue by yohanboniface** [gristlabs/grist-core#256]
Hi,

We can currently export a "table view" to CSV, but this has some UX limitations for us:

- reading a CSV in Excel is not very friendly (a bit more in LibreOffice, but still not as smooth as loading a native format)
- some information is lost in CSV, mainly the type, which can create data issues, like losing "leading 0" in some administrative codes (yes, one can control the type when loading a CSV, but users may not do that, or forgot to do it, or miss one when there are 50 columns, etc.)

So we'd suggest to add a "Download as XLSX" just near the "Download as CSV". What do you think ?

This is something we can work on.

Thanks for your time and inputs!

Yohan

**Comment by dsagal** [comment]
I've heard this request from others too, I think it's a good idea.

**Comment by anaisconce** [comment]
That would be great!

**Comment by LouisDelbosc** [comment]
The PR has been merged, I think we can close the issue 🙂

**Comment by anaisconce** [comment]
Thank you, @LouisDelbosc ! I just played with it and am happy to have it. 🤩
