### ISSUE TITLE
Missing autocomplete in "Apply Formula to Data"

### ISSUE THREAD

**Issue by yohanboniface** [gristlabs/grist-core#269]
Hi,

When in the "Apply Formula to Data" input, I've not autocomplete:

![image](https://user-images.githubusercontent.com/146023/189067951-8f3a3716-6a27-4ea3-b914-98e6ca29e074.png)

So it's harder to type a column name without typo, etc.

cc @LouisDelbosc :)

**Comment by LouisDelbosc** [comment]
It seems it'd be better to have a span or div instead of a `readonly` attribute.

[Source](https://stackoverflow.com/a/22438511)

**Comment by yohanboniface** [comment]
@arnaudpeich @LouisDelbosc fixing this may help on a daily usage :)

**Comment by anaisconce** [comment]
@yohanboniface + team :) 

I'm curious, how do you use this feature? This feature predates trigger formulas. After we rolled out trigger formulas, I gravitated towards using that. In my case, every use case I can think of for "Apply Formula to Data" can be handled with trigger formulas, so I may be missing a cool edge case.

In particular, I am thinking of trigger formulas for data cleaning.

![image](https://user-images.githubusercontent.com/69366135/195668693-95d69fac-5ae5-47af-b022-2c81c7d53b62.png)

**Comment by yohanboniface** [comment]
I'm indeed using a lot "Apply Formula to Data" to clean data, or to extract some useful data from some raw values, of a whole column in a once, or to combine many column data in one with some logic inside.

What makes it very handy is the preview feature, which is incredibly helpful for catching exceptions in a glance.

I never thought about using the trigger formula for this, because I understand those as "triggered" by some user action, not by me all in once for the whole column. But I may be missing something about the trigger feature! :)

**Comment by yohanboniface** [comment]
@anaisconce one more thought from today's work: would be very very handy that "Apply Formula to Data" could only apply to current selection. When applying a filter to target some invalid data, for example, that would make our life much easier to be able to just apply to those rows.

Eg.: I've a reference column created from some string ids. When the reference is created, some of those ids are invalid and do not match: I'love to be able to apply a formula to only those (adding a leading zero that was missing, in my current example).

![image](https://user-images.githubusercontent.com/146023/198649308-1f960321-f715-48ae-8332-b7ff9bfacce9.png)


Makes sense ? :)

**Comment by yohanboniface** [comment]
One other example of how it could be handy to only target some invalid rows:

![image](https://user-images.githubusercontent.com/146023/198660538-1daa10f6-f631-49a6-b502-42a3d171c1f7.png)

Just to make it clearer: "Apply Formula to Data" is one of my favorite Grist features, one I use a lot, and one I showcase when I do a Grist workshop (doing a lot these days!). :)

**Comment by yohanboniface** [comment]
Also, something I would really really love is some sort of "history" of the formula I've typed, because I use very often the same base (adding missing leading zero, reversing a date, cleaning accents before a match…). :)

**Comment by vviers** [comment]
Thinking of grouping those into a single "Redesign Apply Formula to Data" issue

**Comment by vviers** [comment]
Closing this and opening https://github.com/gristlabs/grist-core/issues/817

**Comment by raph-topo** [comment]
Hi !

This feature is still missing in Grist. I expected the "Transform / Apply formula to data" input to have the same features as the "Trigger formula" input. 

I use this tool a lot with: one column with data to be cleaned + multiple other columns with data extracted from that (often like `$To_be_cleaned.split(" ")[2]`) and column name auto-completion would help much.

Currently, auto-complete only proposes one column (itself, which btw could be replace with `value` as in trigger formulas):
<img width="537" height="150" alt="Image" src="https://github.com/user-attachments/assets/14a1b9d5-7e2a-47d1-ab30-b176a6ba3c2c" />
