### ISSUE TITLE
env var for controling allowed origins ?

### ISSUE THREAD

**Issue by yohanboniface** [gristlabs/grist-core#271]
Hi,

We have a scenario were we want to use table data from within another application (a map) served from another domain than our Grist domain.

I've first tried to add CORS headers in the Treafik proxy, but then I hit a check in [grist-core](https://github.com/gristlabs/grist-core/blob/63683f98ccc9c1519843471347c90b13c5f23416/app/server/lib/FlexServer.ts#L1736). So I've discovered that there is a small CORS management in Grist, great! :)

I understand that the API keys are "full powered" at this time, so exposing them in an application may be quite risky. But it seems that if the document is "public access: on", we can get the data through the API without a key (not totally sure about this point, though).

So, a suggestion would be to add an (optional) env var `GRIST_ALLOWED_HOSTS` to allow more hosts.

Does that make sense ?

Thanks for your inputs,

Yohan

cc @LouisDelbosc

**Comment by dsagal** [comment]
It would be nice setting a list of allowed origins on a per-document basis.

It would allow things like adding a record to Grist (including hosted Grist) directly from a form on a webpage (using some Javascript). There is a risk that it would tempt people to put sensitive API keys into pages, which we should discourage as much as possible. But it would be legitimately useful for unauthenticated requests, since you could make a Grist document public and use granular access rules to limit what unauthenticated requests can do.

**Comment by yohanboniface** [comment]
> It would be nice setting a list of allowed origins on a per-document basis.

Where this setting should be controlled from the UI ? I see three options:

-  in the Document Settings form
- in the document's "Manage Users" modal (that could be named then "Manage Users and Access" (given there is already the "public access" control there)
- within the "Access Rule" tab 

Thoughts ? :)

**Comment by LouisDelbosc** [comment]
@dsagal @yohanboniface I think the verification should be done here in the [function allowHost](https://github.com/gristlabs/grist-core/blob/63683f98ccc9c1519843471347c90b13c5f23416/app/server/lib/requestUtils.ts#L98) where we can check if the host is in database of allowed host.

There are many ways to solve this issue and I'd like to have more guidance regarding where to implement this, what does the form look like ? Where should I put it ? Do we allow get/post/patch/... methods ? Or should we have some granular rights ?

However we have some needs to this feature for some of our users., so, maybe we can start with a quick-win (reading environment variable in `allowHost` function) and when the story is ready, we will do the full story.

**Comment by LouisDelbosc** [comment]
@dsagal @paulfitz I see there is a `DocumentSettings` form where you can configure local time or currency (did not found it before sorry)

To do a document based right, where should I modify the document model ? Is there a model to change ? Some migration to do ?

**Comment by paulfitz** [comment]
> To do a document based right, where should I modify the document model ? Is there a model to change ? Some migration to do ?

When processing a request, the decision about how to respond to a particular Origin is currently made early. For example, for `/api` endpoints there's middleware to apply it unconditionally to all endpoints here https://github.com/gristlabs/grist-core/blob/d55b5110ac4db568fd77d4e33415f83ad213b59c/app/server/lib/FlexServer.ts#L585

Some refactoring would be needed to make it possible to have distinct, document-aware logic.

On the question of where to store the list of hosts. It could be embedded in individual Grist documents, or in the home database (briefly described at https://support.getgrist.com/self-managed/#what-is-a-home-database). Either could be made to work in this case. If we imagine ever wanting to decorate document listings in bulk with information about allowed origins, then the home database would be the way to go. I'd lean towards the home database overall.

If in the home database, it would be adequate I think to place the hosts in `DocumentOptions` https://github.com/gristlabs/grist-core/blob/d55b5110ac4db568fd77d4e33415f83ad213b59c/app/common/UserAPI.ts#L117-L121

This can be done without a migration. Another option is to add a new column to the `docs` table, or possibly a new `docs_hosts` table, both of which would require migrations. You can see previous home database migrations in https://github.com/gristlabs/grist-core/tree/main/app/gen-server/migration.

If storing the hosts in individual documents, there's a `documentSettings` column in `_grist_DocInfo` table that could be used without a migration (the DocumentSettings dialog uses it for storing an engine setting). A new column is another option, with a document schema migration (I can give more details if you want them).

**Comment by paulfitz** [comment]
Closing this issue since the env variable was added in https://github.com/gristlabs/grist-core/pull/287
