### ISSUE TITLE
Missing CSS styles for Docker DIGEST 0302d402f617

### ISSUE THREAD

**Issue by Vladimir-Va** [gristlabs/grist-core#273]
`APP_STATIC_INCLUDE_CUSTOM_CSS=true`
After last update when try add widget:
![image](https://user-images.githubusercontent.com/52074398/189192118-ffe604f0-b086-4da3-b54e-dfbb2460947f.png)
And in profile settings we not see toggle for new dark theme.
If set
`APP_STATIC_INCLUDE_CUSTOM_CSS=false`
All ok and in profile settings we see toggle for new dark theme.

**Comment by paulfitz** [comment]
Sorry about this @Vladimir-Va, we're looking into it.

**Comment by Vladimir-Va** [comment]
Done. Thank you!
