### ISSUE TITLE
Display number of rows

### ISSUE THREAD

**Issue by yohanboniface** [gristlabs/grist-core#283]
Hi,

There is a common pattern I see among our users: apply a filter to data in order to know how many rows match this filter.

At this time, the way to know the number of rows we've found is to scroll down the table to see that last row number. When there is a few rows, this works, but when there are hundreds of rows, it's not very friendly. Is there a simple method ?

One idea may be to display this information in the table header, something like this (but nicer :p ):

![image](https://user-images.githubusercontent.com/146023/190619171-5d1d4ebd-0bda-447f-8bc7-048cd2769abe.png)

Thoughts ?

Thanks! :)

Yohan

**Comment by paulfitz** [comment]
Sounds like a useful addition. There's a feature in the works that will look like this (see table footer) that will show totals and counts for the current selection. Perhaps it would make sense to always show the row and column count?

<img width="482" alt="screen_shot_2022-08-26_at_11 16 52_am" src="https://user-images.githubusercontent.com/118367/190639441-1bbcce86-a69b-4509-8b88-bb09da42fa3f.png">

**Comment by yohanboniface** [comment]
> Sounds like a useful addition. There's a feature in the works that will look like this (see table footer) that will show totals and counts for the current selection. Perhaps it would make sense to always show the row and column count?

That would be perfect! And this new feature will be greatly appreciated :) We had this morning a case where this would have been useful in a workshop! Can't wait for it :)

**Comment by paulfitz** [comment]
@yohanboniface a first version of this was added in https://github.com/gristlabs/grist-core/commit/364610c69db6ef50b3381df7758941ee1a503a9b, which should be in the latest docker version. Sums and row/column counts are shown when there is a selection.

**Comment by yohanboniface** [comment]
Excellent, thanks! I'll update the image on our side :)

**Comment by LouisDelbosc** [comment]
I think we can close this issue isn't it ?
@paulfitz @yohanboniface
