### ISSUE TITLE
Table id displayed in table list

### ISSUE THREAD

**Issue by yohanboniface** [gristlabs/grist-core#309]
Hi,

When a column is set as `Reference` or `ReferenceList`, there is a drop down to select the destination table. This drop down displays the table id, while I'd expect the table name, which is what the user know.

Eg.:

![image](https://user-images.githubusercontent.com/146023/195318272-043e66d1-8f7e-4806-ae5a-4ecbc47c3666.png)
![image](https://user-images.githubusercontent.com/146023/195317560-dc1de59f-5e11-42b1-a617-59b88025a3ab.png)

Not sure if it's a bug or a feature (maybe in case two tables have the same name ?), but I've seen a user troubled by this (and thus thinking the table was not renamed and trying rename it again).

If you also think it's an issue, we can work on it. If you think it's on purpose, just close the issue :)

Thanks!

Yohan

**Comment by yohanboniface** [comment]
ping @paulfitz just to know if we should work on something or close :)

**Comment by paulfitz** [comment]
@yohanboniface we've been classifying cases like this as bugs and fixing them as we find them. If you have capacity to fix this one it would be great. Thanks for following up!

**Comment by yohanboniface** [comment]
ok! cc @LouisDelbosc quick one :)

**Comment by LouisDelbosc** [comment]
<img width="785" alt="Screenshot 2022-11-16 at 12 10 18" src="https://user-images.githubusercontent.com/11460746/202165290-b43032bf-0536-412d-9a57-27a26052fab0.png">

What does exactly correspond the names on the menu bar (left panel). Here I can see a différence between the *left panel label*, the *table name* @yohanboniface is seeing and the *tableId* we display.

In the [codebase](https://github.com/gristlabs/grist-core/blob/main/app/client/components/DataTables.ts#L104) we can see it is `table.rawViewSection`. Is it what we want to display ?

cc @yohanboniface @paulfitz

**Comment by paulfitz** [comment]
What you are seeing on the left panel is a list of Pages, which contain Page Widgets (≈ View Sections in the code), which render data from Tables. Pages and Tables are often in a 1:1 relationship for simple documents, but they don't have to be. Pages can have multiple Widgets drawing from multiple Tables. Multiple Pages could be showing material from the same Table, perhaps filtered or displayed differently. So Pages and Tables can be named differently. What counts as a table name is a little trickier than you might expect, for historic reasons, but what `Raw Data Tables` / `Données sources` shows as the name of a table is the logic we'd like to use consistently everywhere. Tagging @dsagal as the best person to speak to a grand unified theory of table names :)

**Comment by LouisDelbosc** [comment]
> What you are seeing on the left panel is a list of Pages, which contain Page Widgets (≈ View Sections in the code), which render data from Tables. Pages and Tables are often in a 1:1 relationship for simple documents, but they don't have to be. Pages can have multiple Widgets drawing from multiple Tables. Multiple Pages could be showing material from the same Table, perhaps filtered or displayed differently. So Pages and Tables can be named differently. What counts as a table name is a little trickier than you might expect, for historic reasons, but what `Raw Data Tables` / `Données sources` shows as the name of a table is the logic we'd like to use consistently everywhere. Tagging @dsagal as the best person to speak to a grand unified theory of table names :)

Ok thanks for the explanation, I have a better understanding now.
