### ISSUE TITLE
Cannot change destination table of Reference List

### ISSUE THREAD

**Issue by yohanboniface** [gristlabs/grist-core#314]
Hi,

I've a document with a Reference List pointing to some table, now I want it to point to another table (with different structure and data), but I can't: I select the other table in the dropdown, but then it goes back to the original table immediately.

![image](https://user-images.githubusercontent.com/146023/195832497-e07408e4-4667-41ee-9bdf-bf3b9b1f0970.png)

Here is a test case: 
[bug changing reference list.zip](https://github.com/gristlabs/grist-core/files/9785444/bug.changing.reference.list.zip)

Thanks for looking a it!

Yohan

cc @LouisDelbosc @arnaudpeich for next week if it's not fixed by then :)

**Comment by georgegevoian** [comment]
Thanks for reporting this @yohanboniface.

It looks like it's a problem with precedence in [this conditional](https://github.com/gristlabs/grist-core/blob/5f66a8f298de5bfc40d7e80361bb80cb72e589b3/app/client/components/TypeConversion.ts#L199). I'll open a PR shortly once I've confirmed that's the problem.

**Comment by paulfitz** [comment]
Addressed in https://github.com/gristlabs/grist-core/commit/7682b3c32052ada50509eb7bee0115eb210e1ad7 (thanks @georgegevoian!), fix should show up in docker containers and hosted service in due course.

**Comment by yohanboniface** [comment]
Fixed, thanks!
