### ISSUE TITLE
[DataViz] Bins for histograms

### ISSUE THREAD

**Issue by vviers** [gristlabs/grist-core#319]
Hey there 👋🏼 

A lot of our users are starting to use Grist for generating reports for cabinet members (yay Grist ! 🥳 )

However, a fairly standard dataviz capability that is currently missing when making a histogram widget is the ability to **define bins for the data to be grouped into before aggregating.**

As of now, a workaround is to define a new "group" formula column and then use this column when making the histogram but imo that is not satisfying for two reasons : 
1. this requires users to "code" which is not easy for some of them + feels hacky)
1. the order in which the bins are shown in the histogram is not easy to handle (for example, the following bins are sorted alphabetically but are not in the correct order : `"[10-500]", "[10,000-100,000]", "[500-10,000]"`)

WDYT ? 🤔

**Comment by anaisconce** [comment]
I like this idea. Do you have a particular UI in mind?

One ambiguous idea (not yet sure how the UI would look), is to include a step during summary table creation where it's easy to define bins for certain column types, such as numeric or date columns.

**Comment by vviers** [comment]
As for the UI, I was thinking of something under `Chart` > `Widget` > `x-axis` like another tickbox that says "Bin the data" and boxes that let you enter the upper and lower boundaries of each bin if that makes sense.
<img width="243" alt="Screenshot 2022-10-27 at 17 13 31" src="https://user-images.githubusercontent.com/30295971/198329496-063ebbf2-0777-4df1-b87e-122d69dfac7d.png">

I can synchronize with @LouisDelbosc and make you a proposition in a PR if that's a feature you're interested in ?

**Comment by anaisconce** [comment]
Interesting! Would it also be useful to see the bins as rows in the aggregated table from which chart is generated? 

That's why I started thinking of summary tables first. If I understood correctly with the "hacky" method, that's what the formula was essentially doing, right? Using a formula to categorize records into bins, then then aggregate the data by bin? Being able to do it from either the chart or the summary table UI makes sense, though the two are linked.

**Comment by vviers** [comment]
I agree, that would work well !

What I am missing here is a way to sort the bins by numerical order (I believe the default as of now is alphabetical order) when making a histogram (cf. caveat number 2 outlined in my post above).

Any pointers on how we could implement that ? or should we make you a proposition ? :)

**Comment by anaisconce** [comment]
Ah, yes! There is currently a way to do it with "natural sort." When sorting a text column, there's a "..." menu next to the column in the creator panel that has an option for natural sort. 

But even with that, I can see the issue your team is running into. Adding the comma separator in the number is producing the wrong result. I propose fixing how natural sort handles numbers with comma separators in text columns.  

I made a quick video re: what I mean for clarity.


https://user-images.githubusercontent.com/69366135/199968304-4cba50dd-b09b-4881-a633-356632049320.mp4

@berhalak may have some extra guidance about this?

**Comment by vviers** [comment]
@LouisDelbosc is rightfully pointing out that this might introduce confusion for languages (such as french) where the comma separator is used for decimal numbers (`1000,421` is the french equivalent of `1,000.421`)

I can totally live with writing large numbers without commas if that fixes how my bins are handled 🙂

Let me know if you would still like us to move forward with an implementation of binning at the histogram widget-level ? Else I believe we can just close this issue. 

I'm also happy to document the current way to make a binned histogram somewhere, any idea of where such doc would go ?

**Comment by vviers** [comment]
Closing this issue for now

**Comment by vnoel** [comment]
Sorry to comment a closed issue, but this is the only place I've found that discusses binning values in Grist histograms. Is there some guidance anywhere on how to proceed to achieve this result?

**Comment by vviers** [comment]
@vnoel here's my workaround, following 

> As of now, a workaround is to define a new "group" formula column and then use this column when making the histogram but imo that is not satisfying for two reasons :
> 
> - this requires users to "code" which is not easy for some of them + feels hacky)
> - the order in which the bins are shown in the histogram is not easy to handle (for example, the following bins are sorted alphabetically but are not in the correct order : "[10-500]", "[10,000-100,000]", "[500-10,000]")

define the bins with a leading letter so they are sorted correctly "A - [10-500]", "C - [10,000-100,000]", "B - [500-10,000]" and _voilà_
