### ISSUE TITLE
Issue with zebra lines and frozen column

### ISSUE THREAD

**Issue by yohanboniface** [gristlabs/grist-core#332]
The frozen column background becomes transparent.

Without:

![image](https://user-images.githubusercontent.com/146023/198675402-387f85e8-2c34-444c-8acb-85e594d2d572.png)

With:
![image](https://user-images.githubusercontent.com/146023/198675502-96bedb00-f642-4dce-9b68-f2d2bddf9678.png)

cc @LouisDelbosc @arnaudpeich 

Thanks!

**Comment by paulfitz** [comment]
Sorry about this, I think this has been fixed in https://github.com/gristlabs/grist-core/commit/d81bba625aec5f75f4595b61ce245266c940c49d (thanks @berhalak)

**Comment by yohanboniface** [comment]
Ah, great! :)

And sorry for the noise! I thought I was up to date on my local machine before checking, but I was not, my bad.

**Comment by paulfitz** [comment]
(The fix was made yesterday on a fork and hadn't actually reached `grist-core/main` until I saw your issue and pushed it.)
