### ISSUE TITLE
Hide check box from toggle in formula mode ?

### ISSUE THREAD

**Issue by yohanboniface** [gristlabs/grist-core#333]
Seems a bit confusing to have a check box when a toggle column is a formula, when the user has mouse over:

![image](https://user-images.githubusercontent.com/146023/198687414-19ff8ac6-359c-47b7-b872-2e693a426f4e.png)

What about hiding it ?

**Comment by paulfitz** [comment]
That would be very sensible @yohanboniface, I agree :-)

**Comment by vviers** [comment]
We can close this issue thanks to @CamilleLegeron :) ! :tada:
