### ISSUE TITLE
Thoughts on i18n workflow

### ISSUE THREAD

**Issue by yohanboniface** [gristlabs/grist-core#336]
Hey,

Sorry, I'm late to the party, but here are some thoughts about the i18n workflow.

Context: I'm working on preparing a Grist workspace for a new team, and I wanted them to have a French experience from the beginning. I've seen that quite a lot of string were still untranslated (eg. all [this folder](https://github.com/gristlabs/grist-core/tree/main/app/client/widgets)), so I decided to make them translatable and do the translation. But… it's a pain! :/

Let's me try to explain this is a positive and constructive way. :)

Basically, adding a new translation string means:
- adding a new boilerplate JS code in the top of the file if it's not already there, including hard coding the file name as context key
- replacing strings by a call to a function with a new key as argument, including saving the original string for later use
- adding a new object in the `en.client.json` file if it's not already there, otherwise find it the whole json
- add a property with the translation key, adding also the original value as English default
- if I also want to have the French translation, I need to repeat the json step in the `fr.client.json`

It's really painful, and I know it well because I was in the translation party last week (with all the team)! :)

I want to highlight the pain points:
- adding a boilerplate function in each file
- dealing with a translation key ("UserAttributes" for "User Attributes", "SomethingShort" for "A very long English sentence…")
- dealing manually with the json structures

I've two suggestions:
- use the English original string a the key; that's ok that we need to revalidate translations if that string changes
- use a script to build the `en.client.json`, by parsing the code base and the calls to the `t()` function

My typescript/javascript/nodejs skills are too terrible to be able to see how to deal with the boilerplate definition of a context key being equal to the file name (in python I'd play with `__file__` or such).

About parsing the code base to extract the keys, this is something I've done in a previous life (before my psychiatrist prohibited me to do JS ;) ): https://github.com/yohanboniface/Leaflet.i18n#generating-locales-files (yep, that's still JS made by a python dev).

I know this would means more work (that we could do if we agree on some plan), but I really think this should be arbitrated now, before adding more languages and translators in the process.

Thanks for your feedback!

cc @arnaudpeich @LouisDelbosc @paulfitz @dsagal @berhalak

**Comment by paulfitz** [comment]
@yohanboniface those proposed changes sound reasonable to me. We went back and forth on whether the English original string should be the key. We had questions about how that would work if there are interpolated values in it, for example. But in many cases it would be fine, and if your team (as the people on the front-line actually doing a translation) see that as an overall time-saver then I'd say go for it. And automating tedious steps makes total sense.

**Comment by LouisDelbosc** [comment]
Hello @paulfitz @dsagal @berhalak,

basically the need expressed by @yohanboniface is to have the file `en.client.json` automatically generated (since it was a real pain in the ass to do it manually).

To do so, keys will be english text, we will parse them and generate a json file. However, there are some edge-cases: `context` and `plural`.
We decided to remove the context variable and generate automatically `_one` and `_other` keys (to manage plural). The common key for both singular and plural would be the plural version. 

```js
// EXAMPLE
text =  t("Reset {{count}} entire columns", {count: numCols});

// INSIDE en.client.json
"Reset {{count}} entire columns_one": "Reset entire column",
"Reset {{count}} entire columns_other": "Reset {{count}} entire columns"
```

**Comment by paulfitz** [comment]
The presence or absence of a context variable is up to you as translators, if it seems easier overall without, then I'm fine with that.

For the `_one` and `_other` suffixes - that would apply only if a `count` is supplied? I'm also fine with that.

**Comment by paulfitz** [comment]
Thanks for your work on this @LouisDelbosc and @yohanboniface !
