### ISSUE TITLE
button misaligned in French

### ISSUE THREAD

**Issue by yohanboniface** [gristlabs/grist-core#339]
French words are longer than English ones, I'll guess we'll have more of this:

![image](https://user-images.githubusercontent.com/146023/199502225-471efda3-32ce-4aa3-8ee2-4a43771ae664.png)

cc @LouisDelbosc :)

**Comment by LouisDelbosc** [comment]
@paulfitz issue was fixed, this issue can be closed.

**Comment by paulfitz** [comment]
Thanks all!
