### ISSUE TITLE
Expanding/collapsing widgets

### ISSUE THREAD

**Issue by paulfitz** [gristlabs/grist-core#34]
In addition to laying out widgets side-by-side as is currently possible, it is sometimes useful to collapse some widgets, or to expand one to the full screen. Mobile views address this in a way. Something similar should be available on the desktop.

**Comment by lewisl** [comment]
I would love this. Along the same lines, allow manual sizing of widgets and a special widget called “button bar” to hold action buttons.

**Comment by jperon** [comment]
In the same vein (as I was pointed to here from [this thread](https://community.getgrist.com/t/folded-left-menu/1717)), it would be nice to be able to have the "menu" one gets after organizing the tables on the left folded by default.

**Comment by dsagal** [comment]
Similar request here: https://community.getgrist.com/t/maximize-widgets-pages-sections-like-z-index/1808

**Comment by jperon** [comment]
Isn’t it fixed by 1dafe4bae0791eb60714fc0069180c62039ee16c ?

**Comment by paulfitz** [comment]
You're right @jperon, that specific request is now handled. I'm not 100% sure if that user is self-hosting, and this improvement hasn't reached our hosted service yet, otherwise it'd be good to tell them. In any case, we'll be publicizing maximizing in newsletter and community posts at end of month.
