### ISSUE TITLE
Access rules: option to remove all invalid rules at the same time

### ISSUE THREAD

**Issue by jperon** [gristlabs/grist-core#344]
When working on a document, it’s quite common to remove obsolete tables, or to remove some columns. If access rules refer to such obsolete items, it prevents modifying other rules until all invalid rules are removed, which can be painful when one hasn’t checked rules for a while. It would be nice to have a button "Remove all invalid rules", to automate this process.

**Comment by paulfitz** [comment]
Hi @jperon thanks for the suggestion. The interaction of deleted tables and columns with access rules is on our mind, and we're working on making improvements here.

**Comment by jperon** [comment]
Thank you very much for the last update, that solves this issue !
