### ISSUE TITLE
How to make snapshots work on self-hosted ?

### ISSUE THREAD

**Issue by vviers** [gristlabs/grist-core#359]
Hey there 👋🏼 

@yohanboniface and I can't quite seem to figure out how to make snapshots work on our Grist instance 🤷🏼 

Every time we open the "Document History" tool, there is only one snapshot which is from a few seconds ago : 

<img width="244" alt="Screenshot 2022-11-17 at 16 33 50" src="https://user-images.githubusercontent.com/30295971/202489429-9ab75d07-d879-4c3d-b2ee-780640fe6c33.png">

That's obviously not super useful to us, as we'd like to have screenshots made at specific points in history (say, 5min ago, 1hour ago, a day ago, a week ago).

Are we missing something here ?

Thanks 🙏🏼

**Comment by paulfitz** [comment]
Hi @vviers, @yohanboniface, we don't have an implementation of snapshots that works directly on a plain file system, so snapshots don't do anything useful in grist-core.  For our SaaS, we have an implementation for managing document versions in AWS S3. Grist Enterprise includes that implementation, plus support for Azure Blob Storage https://support.getgrist.com/self-managed/#how-do-i-set-up-s3-or-azure-backups. We are committed to getting a snapshot solution to grist-core by the end of the year. We don't want to leave Grist tied to any particular storage service, so we have been looking for good options. The S3 API has become a de facto standard, implemented by many services and applications, including MinIO https://github.com/minio/minio, so support for S3 API compatible storage is what we plan to release. Would that work for you?

The amount of code to implement this isn't much. In our non-free grist-ee repo you can see AWS S3 code here https://github.com/gristlabs/grist-ee/blob/main/ext/app/server/lib/S3ExternalStorage.ts and Azure code here https://github.com/gristlabs/grist-ee/blob/main/ext/app/server/lib/AzureExternalStorage.ts - as you can see, they are short files. The task is mostly making decisions about what dependencies to take on, and setting up testing. Our existing tests rely on AWS infrastructure, I'd probably want to substitute MinIO.

**Comment by yohanboniface** [comment]
>  The S3 API has become a de facto standard, implemented by many services and applications, including MinIO https://github.com/minio/minio, so support for S3 API compatible storage is what we plan to release. Would that work for you?

Perfectly! We already have a minio running ;)


> The task is mostly making decisions about what dependencies to take on, and setting up testing. Our existing tests rely on AWS infrastructure, I'd probably want to substitute MinIO.

Okay, that may be something we'll work on. Let's communicate when one of us start working on it, so we don't duplicate the effort!

**Comment by paulfitz** [comment]
Hi @yohanboniface, we will be starting work on this shortly.

**Comment by paulfitz** [comment]
Update: the basic functionality has landed https://github.com/gristlabs/grist-core/commit/e564d31582f95d49f4886046c81af4f27e98c8e4; I'm working on setting up aws-free tests https://github.com/gristlabs/grist-core/compare/main...paulfitz:grist-core:minio.

**Comment by paulfitz** [comment]
(drafting documentation on how to use this)

Here's how to test this out locally. We'll use three containers: `minio`, `redis`, and `grist`. Redis is currently needed for snapshots, though I think this dependency could be dropped now with a bit of work - it is from the days when more parts of s3 were eventually consistent, so a separate transient but consistent store was needed for some tasks.

First, make a network to put the containers in:
```
docker network create grist
```

Start Redis:
```
docker run --rm --network grist --name redis redis
```

Start MinIO:
```
docker run --rm --network grist --name minio \
  -v /tmp/minio:/data \
  -p 9000:9000 -p 9001:9001 \
  -e MINIO_ROOT_USER=grist -e MINIO_ROOT_PASSWORD=admingrist \
   -it minio/minio server /data -console-address ":9001"
```

Use the MinIO interface at `http://localhost:9000` to create a bucket called `grist-docs`. Be sure to turn on versioning! Alternatively you can use the MinIO or AWS client to make the bucket.

Start Grist (make sure you are using an up-do-date image):
```
docker run --rm --network grist \
  -e GRIST_DOCS_MINIO_ACCESS_KEY=grist \
  -e GRIST_DOCS_MINIO_SECRET_KEY=admingrist \
  -e GRIST_DOCS_MINIO_USE_SSL=0 \
  -e GRIST_DOCS_MINIO_BUCKET=grist-docs \
  -e GRIST_DOCS_MINIO_ENDPOINT=minio \
  -e GRIST_DOCS_MINIO_PORT=9000 \
  -e REDIS_URL=redis://redis \
  -v /tmp/gristdata:/persist -p 8484:8484 -it gristlabs/grist
```

Snapshots will now work, and the bucket is now the canonical store for your documents. To see that, stop Grist, delete the `docs` subdirectory in its persistent directory, and start it again - your documents should open without trouble.

If along with Redis and MinIO you also use PostgreSQL as your home DB (https://support.getgrist.com/self-managed/#what-is-a-home-database) then all important Grist state is externalized.

**Comment by yohanboniface** [comment]
Awesome, thank you! :tada:

**Comment by almereyda** [comment]
Thinking out loud, and just as a side note: if this works with a "generic" HTTP CRUD API such as S3, Grist could run "backendless"  on other "generic" HTTP CRUD APIs (["zero" data](https://0data.app/) protocols), such as [Solid](https://solidproject.org/) or [remoteStorage](https://remotestorage.io/).

With using Minio's [Secure Token Service (STS)](https://min.io/docs/minio/linux/developers/security-token-service.html) it even appears within reach, that the Grist browser application talks to the object store directly.

Both options in return open up doors for #380, if state management within the service worker can be solved.

On another note I wonder, if this worked for you @yohanboniface, should we close here?

**Comment by paulfitz** [comment]
That error sounds very like https://github.com/minio/minio-js/issues/1038

@vviers it looks like the client library we use (minio.js) has a `region` option that could be added here https://github.com/gristlabs/grist-core/blob/9e009bbab99c8c48794fd87131592948fb409237/app/server/lib/MinIOExternalStorage.ts#L32-L40 Sorry for not including that as an option.

**Comment by LouisDelbosc** [comment]
Our ops team tried to put a dev instance with snapshot and it seems to work, however it also seems to delete all the documents on the instance. Is it a wanted behaviour ?

**Comment by paulfitz** [comment]
@LouisDelbosc once there is external storage, it becomes the "canonical" store of documents, with anything on any individual Grist instances becoming a cache. Deleting documents isn't wanted behavior, but the scenario of migrating an existing site is different from initially configuring a site. I thought I had tested what happens when migrating existing sites, but perhaps I muddled something, sorry. I'll dig in what I get a chance - in the meantime, if you have the capacity to look into it, I'd appreciate it, since I'm a bit backlogged. The core logic is in:
https://github.com/gristlabs/grist-core/blob/cbf925aa00bf3b2b314993a31b59707ddc3234d4/app/server/lib/HostedStorageManager.ts#L618-L633
A workaround if you're seeing deletion could be to try this migration procedure: (1) shut Grist down, (2) copy the `*.grist` files from the old local store to the external store, placing them in the location where new Grist documents would be placed, then (3) bring Grist up with new settings. I have not tested this workaround.

**Comment by LouisDelbosc** [comment]
I made an local environment with miniio and redis to be able to snapshot in local. The config seems to work but snapshots doesn't appear. Am i missing something ?

<img width="851" alt="Screenshot 2023-03-21 at 10 27 52" src="https://user-images.githubusercontent.com/11460746/226565318-f68e0ab1-b1da-4ce5-ab6c-d7756a1a748b.png">

Also, in my docker-compose, I create a document without miniio config and I could see and modify it. However when I open the snapshot panel, I have the following error.
`Error: Request to http://localhost:8484/o/docs/api/docs/w1hovDGx2eTD/snapshots?raw=undefined failed with status 500: Internal Server Error (MinIOExternalStorage.head did not get expected fields)`

<img width="436" alt="Screenshot 2023-03-21 at 10 29 55" src="https://user-images.githubusercontent.com/11460746/226565768-b5c3f78c-4033-415c-b930-ad82a6815286.png">

Should I watch the code you showed us in the previous comment to fix this issue ?

@paulfitz @dsagal

**Comment by paulfitz** [comment]
@vviers do things look healthy in your server logs? You should be seeing lines like:
```
2023-03-20 15:37:40.637 - info: ext doc upload: minio://..../docs/2456fae3-3ea3-4a51-a521-d4d30876a150/Hello.grist checksum 18e95a856443d62dea407a0ecfd06576 version 4d3f4d22-a69d-4f75-b03e-5c9b9d506398
...
```
And you should be seeing files appear in your minio bucket.

Oh, and can you check you have versioning turned on in your minio bucket? I see this is just a subtle gray comment on https://support.getgrist.com/self-managed/#how-do-i-set-up-snapshots but it is really important :)

**Comment by LouisDelbosc** [comment]
Thanks @paulfitz I managed to make it work locally using a remote s3.

The following question may be dumb but I cannot reproduce the issue. Did you make any change on how snapshot are made/used ?

I will tried an older version to see if there is some bugs.

**Comment by LouisDelbosc** [comment]
Thanks @paulfitz ! We have some inconsistencies. I thought everything was working fine, but sometime we have unexpected errors.

Here our servers logs:

<img width="1162" alt="Screenshot 2023-03-28 at 17 26 33" src="https://user-images.githubusercontent.com/11460746/228288716-9883df39-1096-4b4c-99ae-38557b64cbbd.png">
<img width="1171" alt="Screenshot 2023-03-28 at 17 27 14" src="https://user-images.githubusercontent.com/11460746/228288734-a7bf5d95-b1d6-48dd-b420-0d5cdf535cb5.png">

Did you have some of these errors ? Does it mean something to you ?

**Comment by almereyda** [comment]
It will be good to add to the Cloud Storage / Snapshot documentation that when using MinIO, a distributed deployment is required, as versioning is restricted to that use case.

- https://support.getgrist.com/install/cloud-storage/#s3-compatible-stores-via-minio-client
- https://support.getgrist.com/self-managed/#how-do-i-set-up-snapshots

I am unsure from reading their docs if a full Multi-Node Multi-Drive setup is required, or if a Singe-Node Multi-Drive setup would suffice (to enable Erasure Coding [EC] and with it Versioning).

Does anyone here have experiences with running Minio in the above two configurations, and could leave a little remark for clarification? The Minio documentation is also not very expressive, under which circumstances versioning will be enabled: They talk about distributed mode, and then immediately introduce two different ways of doing so.

- https://hub.docker.com/r/minio/minio/  
  Certain features such as versioning, object locking, and bucket replication require distributed deploying MinIO with Erasure Coding. For extended development and production, deploy MinIO with Erasure Coding enabled - specifically, with a *minimum* of **4 drives per MinIO server**. See [MinIO Erasure Code Quickstart Guide](https://docs.min.io/docs/minio-erasure-code-quickstart-guide.html) for more complete documentation.

* https://min.io/docs/minio/linux/operations/concepts.html#id2
* https://min.io/docs/minio/linux/operations/concepts/erasure-coding.html
* https://min.io/product/erasure-code-calculator

In the Minio console at https://console.datalake.example.com/buckets/add-bucket they explicitly reference *Distributed Mode* and link to the [Multi-Node Multi-Drive](https://min.io/docs/minio/linux/operations/install-deploy-manage/deploy-minio-multi-node-multi-drive.html) configuration.

Having these details available when reading through the Snapshot-Self-Host documentation from Grist will make it easier to evaluate, if this prerequisite is met by a chosen, local MinIO installation, or if a new one needs to be set up.

Which is interesting to reconsider when looking at https://support.getgrist.com/self-managed/#how-do-i-set-up-snapshots, where such an extended setup does not seem to be necessary.

**Comment by vviers** [comment]
Following up on Louis' last message : we discovered that bucket versioning wasn't turned on and that snapshots seem to work just fine now that we set up versioning

Will run some more tests on our dev instance but looks promising overall :)

**Comment by fflorent** [comment]
Hi!

I could manage to make the snapshot work using a local MinIO instance and everything works perfectly!

However while trying to connect to a S3 bucket from [Scaleway](https://www.scaleway.com/en/object-storage/), with the versioning feature enabled, we still have this issue:
> 2023-07-13 11:44:45.442 - error: operation failed to become consistent: versions - 214,not ready,3491,not ready,8960,not ready,17968,not ready

And the snapshots don't work anymore.

Do you have any clue of what's going on by chance?
We continue investigating but any help would be much appreciated :pray:.

**Comment by fflorent** [comment]
PR opened here with the context: https://github.com/gristlabs/grist-core/pull/577

**Comment by vviers** [comment]
It's been working for months now 🎉

**Comment by arladmin** [comment]
Hi @paulfitz ,

How to use DigitalOcean Spaces for the S3 Object storage, given that DO Spaces does not support versioned buckets?

**Comment by paulfitz** [comment]
Hi @arladmin, I haven't used DO Spaces. Reading up, I see this page: https://docs.digitalocean.com/products/spaces/how-to/enable-versioning/

That suggests that perhaps versioning could be turned on? If so, that's definitely the easiest solution, and MinIO should work just fine.

If not, there's no existing back-end I know of that will help. For our SaaS we use the AWS S3 library, for historical reasons, but MinIO works just as well. For an enterprise client, we added Azure Blob Storage support. But none of that would help with DO. Adding a new back-end is actually pretty achievable, I'm kind of expecting some day for someone to sit down and make one that works on a raw file system plus some cron scripts for lifecycle management. Just need to implement the methods in this interface https://github.com/gristlabs/grist-core/blob/001ac9ae0babe8137d212900298ddbbffc8866fb/app/server/lib/ExternalStorage.ts#L23

**Comment by arladmin** [comment]
Hi @paulfitz , thanks for your response and that link!

It does seem that DO provides the functionality to turn on versioning via their CLI. Will try it out now.

Btw, is there any particular reason why the option to use the AWS S3 client is not a part of the standard (core) offering? 
In my experience with dozens of tools (FOSS or otherwise), the standard has always been the AWS S3 client, and hence, this is the first time that i'm actually experiencing this sort of an issue.

**Comment by paulfitz** [comment]
> why the option to use the AWS S3 client is not a part of the standard (core) offering?

Given that we have minio.js support, adding the AWS dependency also felt a little heavy? Just in terms of the size of the packages. The minio.js client has been working fine for us against original AWS S3. But if it is giving you trouble of some kind I'd be interested in the details. Either library should handle versioning just fine, but maybe there's some other awkwardness?
