### ISSUE TITLE
Expose column description

### ISSUE THREAD

**Issue by yohanboniface** [gristlabs/grist-core#368]
Hi!

We sometimes need to have a column description, that make clearer what exactly should go inside the column.

For now, we use a "Markdown" widget will a list of column details, but that's not very user friendly, as either we'll consume some screen space to have the markdown widget displayed near to the table/form, either the use needs to change page to have the info they needs to fill in the cell.

What about exposing a column description (I remember starting something like this when working on column description for custom widget), and displaying the description with the small help text. Something like this:

![image](https://user-images.githubusercontent.com/146023/206723504-47a6ff99-7925-4e7f-a6ac-1087f7c44563.png)

Then:

![image](https://user-images.githubusercontent.com/146023/206722391-2160bd24-c08c-4a82-8696-288553b53cb8.png)

Thoughts ? :)

Yohan

**Comment by paulfitz** [comment]
@yohanboniface your proposal seems pretty sensible to me. Pinging @anaisconce who has recently been looking into a design for descriptions of columns, tables, pages etc.

**Comment by anaisconce** [comment]
@yohanboniface What do you think of exposing a column description near the column header? Here's a quick mock-up. This re-uses the UI we currently have for re-naming widgets. 

![image](https://user-images.githubusercontent.com/69366135/207372200-b957bed1-f02a-46cf-8086-160e00a9a14d.png)

In terms of behavior, I am imagining that double-clicking into the column header would open this column label + description dialog. The label could be auto-focused and highlighted, which is what happens now when you double-click a column header. (It would be nice if for users without schema permissions, the save button were disabled to make that clear. Either way, access rules will block those users from changing the label or description.)

If there is a description present, a simple notification dot could make that easy to see at a glance.

![image](https://user-images.githubusercontent.com/69366135/207372793-add8676d-d5c8-441a-abfb-e187b44e3ac7.png)

In terms of reading the description, hovering over the green notification dot opens the description in a read-only way (must click on notification dot on mobile). This re-uses the UI that shows labels on hover over certain buttons (e.g. the undo and redo buttons). Here's a mock-up of how it would look for short or long descriptions.

![image](https://user-images.githubusercontent.com/69366135/207376293-76183ceb-704c-4259-9372-aed11c40d60e.png)

![image](https://user-images.githubusercontent.com/69366135/207376547-d7c2503a-c3e7-4d94-a217-10d7be16d8f9.png)

What do you think?

**Comment by yohanboniface** [comment]
> Would you also expect to edit and read the column description in the creator panel on the right? It could exist in two places, if it adds utility.

One place is enough :)

I'm fine with this proposal! My only doubt is about the green dot, I'm not sure it's self explanatory. Maybe it's a cultural matter, but I'd expect something like a small `<i>` (as "info"), or a `?`. What do you think ?

**Comment by anaisconce** [comment]
An  `i` could work. How's this? 

![image](https://user-images.githubusercontent.com/69366135/207766801-6678a158-9b21-446f-a0e4-2c25ad526756.png)

If you like it, we can ready the icon.

**Comment by yohanboniface** [comment]
Nice!

How about the color ? Green seems giving a success notification  for me. I'd imagine something more neutral, but maybe it's just me. :)

> If you like it, we can ready the icon.

Yes, would be great, thanks :)

**Comment by yohanboniface** [comment]
Sounds perfect to me :)

**Comment by dsagal** [comment]
I'd like to propose a small addition to this idea.

The current proposal includes a popup that shows the column label and description, and would match a similar popup that's shown when you click the label above a widget.

I propose that inside this popup, right under the top textbox, we add a small grey line `TABLE ID: Table_1` (for widgets) and `COLUMN ID: $Col_1` (for columns), with the same styling as in Raw Data listing, and the same behavior (highlight ID on hover, click to copy-to-clipboard).

The motivation is that I often want to find out the ID of a column, and have to open the creator panel to find it; this will make it one click away.

**Comment by yohanboniface** [comment]
@dsagal as far as I've understood, in the current plan, the small <i> will only be displayed when a description as been set (correct me if I'm wrong @anaisconce ).

So, even if I feel the same need as you (quicker access to column id), I'm not sure this small popup is the way to go. :/

**Comment by anaisconce** [comment]
@yohanboniface I believe Dmitry is imagining something like this: 

![image](https://user-images.githubusercontent.com/69366135/209690496-ca80f03f-f031-48b3-88fd-bfa7f66141e4.png)

This is always available when renaming the header, so I think it makes sense and is a good idea. The click-to-copy functionality is nice (and we have it in the Raw Data page for table ids.)

**Comment by yohanboniface** [comment]
Ah ok, makes sense! I first understood the suggestion was to make this info appear in the popup that shows when hovering the small `<i>`! :)

**Comment by anaisconce** [comment]
@yohanboniface Is this something your team will implement, or should I fit it into our list? I don't have an estimate on when we'll get to it on our side, though the feature excites us too. 🙂

**Comment by yohanboniface** [comment]
It's on our list yet! :)

We'll tell you when we start working on it, and in case you do, just tell us :)

**Comment by yohanboniface** [comment]
Ah, but maybe you could make the small icon anyway ?

**Comment by anaisconce** [comment]
Ah, yes, will do! And thank you!

**Comment by LouisDelbosc** [comment]
@dsagal @paulfitz We're trying with @CamilleLegeron to add a field `description` field in the `ColumnRec` model/schema.

We modified those lines: https://github.com/gristlabs/grist-core/blob/main/app/common/schema.ts#L36 to add a description field (like the label one) but we as we save using this function
```ts
const saveDescription = (val: string) => origColumn.description.saveOnly(val)
```

we got the following error:
<img width="397" alt="Screenshot 2023-01-17 at 12 27 46" src="https://user-images.githubusercontent.com/11460746/212887712-b09ed09e-2b9b-463d-934b-425ed5d97efd.png">

Do you have any idea how to solve this issue ?

**Comment by paulfitz** [comment]
Hi @LouisDelbosc, that is an auto-generated file (there's a `THIS FILE IS AUTO-GENERATED BY core/sandbox/gen_js_schema.py` line at the top). When changing the schema of documents, you need to define a migration, so existing Grist documents can be upgraded. You can find all data engine migrations in 
[https://github.com/gristlabs/grist-core/blob/7dc49f3c850ea6cf7f7832d069088c36a200b93b/sandbox/grist/migrations.py](sandbox/grist/migrations.py). For example, here is a migration that added a single column and populated it with a default value for existing documents:
https://github.com/gristlabs/grist-core/blob/7dc49f3c850ea6cf7f7832d069088c36a200b93b/sandbox/grist/migrations.py#L801-L806
You can see that migration being added here:
https://github.com/gristlabs/grist-core/commit/a6e08883e013b777edc2521b2d99bc8f75518caa#diff-0e2536f0339c612dbea9e5fedd4f82c3cf178fd084f441c4faadff794a84a848
alongside a change in the schema (and a change in schema version):
https://github.com/gristlabs/grist-core/commit/a6e08883e013b777edc2521b2d99bc8f75518caa#diff-f03bb1e3b221762f51184f706b45776a8e88536dec61640a116e55685ed00eba
![Screenshot from 2023-01-17 09-08-01](https://user-images.githubusercontent.com/118367/212920041-c7ec5938-befa-44fd-8b18-e74e42e160ef.png)

**Comment by LouisDelbosc** [comment]
@paulfitz thanks ! We modified the `migration.py` file and add a migration 36, however we don't know how to migrate.

The commands from the comments are not working:

```py
# ./test/upgradeDocument public_samples/*.grist
# UPDATE_REGRESSION_DATA=1 GREP_TESTS=DocRegressionTests ./test/testrun.sh server
# ./test/upgradeDocument core/test/fixtures/docs/Hello.grist
```

We launch `gen_js_schema.py` however it only prints the new schema.

`yarn start` also doesn't seems to run the migration as the `schema.ts` file (the one autogenerated) is not modified.

How should we proceed ?

**Comment by paulfitz** [comment]
@LouisDelbosc d'oh, you are right, there is a small script needed for updating typescript schema information. I'm adding it  in https://github.com/gristlabs/grist-core/pull/403

The test-relates scripts mentioned in the comments also need adding, but are less urgent.

**Comment by CamilleLegeron** [comment]
[anaisconce](https://github.com/anaisconce)
thanks @paulfitz, waiting for this PR to be marked I start the front design. 
@anaisconce in the design you proposed I see 
in the design you proposed I have a doubt about how to manage the possible visual conflict with the button that opens the column main menu that appears on hover. A solution can be to put the point `i` on the left of the column label

**Comment by berhalak** [comment]
@CamilleLegeron What do you think about leaving the `i` icon for another PR. I think we should design it separately, as you are right, it conflicts with the menu button, and it also should be added to the Card/Card List widget.

**Comment by CamilleLegeron** [comment]
Hello @paulfitz, thanks for the PR validated rapidly. 

There is still one thing I don't understand about migration management. 
The command line `buildtools/update_schema.sh schema.ts sql.ts` create in sql.ts SQL strings for creating empty documents, but what about the migration of existing documents ? I want all docs have a `description` in the table `_grist_Tables_column`, is it possible ? 
If yes, how it is managed in production deployment ?

**Comment by CamilleLegeron** [comment]
> @CamilleLegeron What do you think about leaving the `i` icon for another PR. I think we should design it separately, as you are right, it conflicts with the menu button, and it also should be added to the Card/Card List widget.

Ok, It makes sense, we can wait for this part and in this PR keep only the description in the right panel. I started to code it a bit, so I will keep it aside

**Comment by CamilleLegeron** [comment]
> @CamilleLegeron What do you think about leaving the `i` icon for another PR. I think we should design it separately, as you are right, it conflicts with the menu button, and it also should be added to the Card/Card List widget.

Hey @berhalak (I accidently remove my previous comment). 
Yes It makes sense, we can keep only the right panel part for the moment. I started a bit to work on it, I keep it aside for the moment.

**Comment by CamilleLegeron** [comment]
> @LouisDelbosc d'oh, you are right, there is a small script needed for updating typescript schema information. I'm adding it in #403
> 
> The test-relates scripts mentioned in the comments also need adding, but are less urgent. I've included the ./test/upgradeDocument script in #403. "public_samples" is an old set of test documents that aren't relevant anymore, sorry for the out-of-date-documentation. The DocRegressionTests are useful but tricky tests I'll move across separately.

Thanks @paulfitz the migration works for us

**Comment by CamilleLegeron** [comment]
@berhalak and @anaisconce there is a interresant place where make appears the description : in a card.

Here a proposal : 
![image](https://user-images.githubusercontent.com/19594405/213428930-aecfcf56-d6b4-4be7-a934-a9c6dc14b89b.png)

There is a little visual problem: if two columns are displayed on the same line, one has a description and the other one doesn't, or if their description doesn't take the same number of lines, then the display shifts. What do you think about it ?

**Comment by yohanboniface** [comment]
Description can be very long (at least in our use cases), so I'm not sure we should have it always displayed (we want to keep the UI clean, while allowing to get more info about what a column is about), that's what we ended suggesting the small `i`.

**Comment by berhalak** [comment]
Yes, I also like @yohanboniface's idea better (to show the `(i)` icon next to the label on the card view). We can always tweak this behavior later. The card widget doesn't have any options in the creator panel yet :).

**Comment by CamilleLegeron** [comment]
@berhalak @anaisconce I raise the subject mentioned above

> @anaisconce in the design you proposed I have a doubt about how to manage the possible visual conflict with the button that opens the column main menu that appears on hover. A solution can be to put the point i on the left of the column label. What do you think about that ?

**Comment by anaisconce** [comment]
@CamilleLegeron To the left makes sense to me.

**Comment by vviers** [comment]
Closing this issue as this has been done 🎉
