### ISSUE TITLE
Issue with ChoiceList and quotes

### ISSUE THREAD

**Issue by yohanboniface** [gristlabs/grist-core#373]
Hi,

When transforming a text with comma to a ChoiceList, there will be an issue if the raw values contains quotes.

See:

![Screenshot from 2022-12-16 19-16-05](https://user-images.githubusercontent.com/146023/208163508-0db95ae4-6e4d-4097-958c-3d7120868d04.png)
![Screenshot from 2022-12-16 19-16-36](https://user-images.githubusercontent.com/146023/208163507-0f6eb507-0836-40f3-af11-84bf5d157f57.png)

The created choices still include the quotes:

![Screenshot from 2022-12-16 19-16-59](https://user-images.githubusercontent.com/146023/208163503-3f8010ff-9516-4110-b66a-bfbf0014f101.png)

Thanks in advance :)

Yohan

**Comment by paulfitz** [comment]
Closing after @CamilleLegeron's fix (thanks!)
