### ISSUE TITLE
Using "Apply formula to Data" in a ChoiceField will clear the choices list ?

### ISSUE THREAD

**Issue by yohanboniface** [gristlabs/grist-core#385]
Hi,

Strange behavior, here.

Situation before:
![image](https://user-images.githubusercontent.com/146023/209933674-c0fdfb7d-2416-40dd-880f-62d945427fc3.png)

Now I click on "Apply formula to Data", without even entering a formula or nothing, choices have been cleared:
![image](https://user-images.githubusercontent.com/146023/209933694-f0f04d09-c7c3-42ea-afdf-2324b7c638bc.png)

Now if I click "Apply" (without changing the default formula):
![image](https://user-images.githubusercontent.com/146023/209933736-70d7e618-7824-4e83-8f19-4651d4ef0529.png)

Any hint ? :)

Yohan

**Comment by yohanboniface** [comment]
Seems this will also remove configuration of a DateField, so it may be that any field configuration is lost. That's bit crippling.

cc @LouisDelbosc @CamilleLegeron in case it's an easy fix :)

**Comment by LouisDelbosc** [comment]
@paulfitz we can close this issue 👍
