### ISSUE TITLE
Not available: Theme & Language if APP_STATIC_INCLUDE_CUSTOM_CSS=true for Docker setup

### ISSUE THREAD

**Issue by Vladimir-Va** [gristlabs/grist-core#417]
Hello Gristr team!
January updates are good, I have already started a new translation.
But if we use APP_STATIC_INCLUDE_CUSTOM_CSS=true
We can see in **Account settings** only **Password & Security** and **API**
If you disable APP_STATIC_INCLUDE_CUSTOM_CSS we can see **Themes** and **Language Settings**

**Comment by paulfitz** [comment]
Oh, thanks for reporting that @Vladimir-Va (and thanks for the translation work!). @georgegevoian would you have a lead on why that might happen?
