### ISSUE TITLE
Incremental imports

### ISSUE THREAD

**Issue by paulfitz** [gristlabs/grist-core#42]
Grist has support for importing data, but could do a better job when re-importing updated data from the same source.

**Comment by Chris-ISN** [comment]
Hoping this can be implemented - for our use case (hardware asset management) we often have a need to re-import updated details into an existing table. Currently not sure how we are going to achieve this with Grist.

**Comment by Chris-ISN** [comment]
Forgot to say - for matching up/identifying existing records when importing you could ask the user to select the index field in the import options - this way if the value for this field in the import was the same as in the existing data then it would match with that row and update the existing data.

**Comment by georgegevoian** [comment]
Hi @Chris-ISN. We've started working on incremental imports, and the initial release will work exactly as you described, with an option to select one or more fields for matching. Hoping to have that available very soon.

We have a lot of other exciting improvements we plan on bringing to incremental imports as well beyond this.

**Comment by Chris-ISN** [comment]
@georgegevoian This is great news. Keep up the amazing work!

**Comment by georgegevoian** [comment]
Grist now has basic support for incremental imports. See [the documentation](https://support.getgrist.com/imports/#updating-existing-records) for more details.
