### ISSUE TITLE
Interoperability with table-schema / data-packages

### ISSUE THREAD

**Issue by vviers** [gristlabs/grist-core#423]
hey 👋🏼 

We are really pushing the use of the [table-schema](https://specs.frictionlessdata.io/table-schema/) and more generally of the frictionless family of [data-ressource / packages](https://specs.frictionlessdata.io/#data-package-specs-suite) standards within the french administration in order to describe metadata and make those datasets easily machine-digestable. As a result, we end up maintaining a lot of those data-packages ourselves.

Keeping those up-to-date with the source data is typically a very manual and error-prone process (especially when said source is a pesky, ever-changing excel file), and we think that one of the benefits of using Grist is that this process of writing and updating metadata description could be made much easier.

We've identified two approaches : 
1️⃣  develop a feature in Grist that lets it produce those metadata in the frictionless standards (table-schema for a single table, data-package for a full document). This could be an API-only feature hidden from regular UI users which would very conveniently allow us to download the data along with its metadata.
2️⃣  develop our own grist-to-tableschema service (either as a standalone app, or as some sort of grist extension) that would consume the Grist API and produce table-schemas.

Would you be interested in option 1️⃣  ? or should we start working on option 2️⃣ ? (obviously we can integrate what we end up developing to Grist further down the road)

Cheers ! 🙂

**Comment by paulfitz** [comment]
Hi @vviers, I'm personally a fan of the frictionless standards (and made a small contribution https://specs.frictionlessdata.io/tabular-diff/). Adding extra endpoints to Grist in the service of making datasets more machine-readable seems reasonable and generally useful, so option 1 sounds good to me. The endpoints could live alongside the endpoints for downloading in csv, excel, or native/sqlite format perhaps. If your team is up for developing those endpoints, we can help with pointers for where to get any needed information.

I do wonder if there'll be information desired for the outputs that isn't lying around in Grist, like for example a data license selection. Some UI work could be needed for that. We'd have an interest in that being done tastefully. If it is document-level material, that seems straightforward.

**Comment by CamilleLegeron** [comment]
Hi @paulfitz we started thinking about that feature. 
For a V1 we could extract the table-schema only from one widget (corresponding to the CSV that may be extracted from) and therefore not consider the foreign keys for `reference` fields. WDYT ?
What do we need to know about creating new endpoints before looking in the code ?

**Comment by LouisDelbosc** [comment]
@paulfitz for some columns, we would like to have the date format (or datetime format) and also if the text is hyperlink or not. Do you have any idea how to access this information in the backend ? Or where is the code I should look at ?

I successfully got the columns description, and type from the model `_grist_Tables_column` using the `exportTable` function. However I don't know how to get the format of some type.

**Comment by LouisDelbosc** [comment]
@vviers @paulfitz can we close this issue ?

**Comment by vviers** [comment]
Closing this issue following Louis and Camille's PRs
