### ISSUE TITLE
Authorize simple click to edit field when it already has the focus 

### ISSUE THREAD

**Issue by CamilleLegeron** [gristlabs/grist-core#430]
Hello,

Some users have no reflex to use the double click to edit a field. So, they make a lot of simple clicks without being able to change the field value. After understanding they have to double click, they double click sometimes on the formulas or on the toggle fields. 

![Peek 2023-02-15 09-33](https://user-images.githubusercontent.com/19594405/218974728-ba68601b-bfcf-4bcf-85fd-7423d8aa2ac2.gif)

Suggestion : 
- We could authorize to edit field on card when we click on a field that has already the focus, or maybe at the first simple click. 

What is your opinion ?

**Comment by paulfitz** [comment]
Entering edit mode if clicking on a field that already has focus could work - what do you think @anaisconce @dsagal ?

If this is specifically for card widgets, there's also been some discussion of having an explicit edit/draft button for them that lets you make a set of changes and then save them as a whole. One-click editing could be a benefit of such a mode.

**Comment by dsagal** [comment]
It was a tiny change to try a simple single-click to edit (even on a field that's not selected), so I put up a preview here: https://grist-detail-view-single-click.fly.dev/8t9BkLQbwCx7/Lightweight-CRM. Got a few points of feedback already for this approach:

- Single-click feels nice.
- Can't click and copy the whole text.
- In particular, makes it harder to select a formula field to copy it.
- Can't click in the URL without triggering the edit.
- Maybe it should be only on Card View (single card). With Card List, there is no way to switch a record without clicking on some field. Especially important on mobile view.

It might indeed be better, as you suggested, to enter edit mode on a single-click of a field that already has the cursor. I haven't had a chance to try that.

**Comment by CamilleLegeron** [comment]
I try your preview and in fact the single-click of a field that already has the cursor can be better. 
Can we authorize the single-click only on certain field types ? A lambda user may want to change easily a text or number field but not a formula.

**Comment by anaisconce** [comment]
I agree, @CamilleLegeron.  A single-click in the already selected field is better. Protecting formula fields in this way makes sense too. 

Would this be only for card widgets, or also for tables?

**Comment by CamilleLegeron** [comment]
Ok nice, I will work on it
@anaisconce  The issue is only about card widgets
