### ISSUE TITLE
Expose Widget Description

### ISSUE THREAD

**Issue by CamilleLegeron** [gristlabs/grist-core#431]
Hi,

As the Column description we could make possible to create widget descriptions to make their reason for living clearer and sometimes particular indications of use. The idea is to have all the informations closest to its place of use and not in a separate markdown widget.

We could maybe add here
![image](https://user-images.githubusercontent.com/19594405/218977329-43afd767-028e-49da-b748-d64cbbaf4540.png)

and here
![image](https://user-images.githubusercontent.com/19594405/218977428-6c9e003c-7042-43bd-b8cf-e158edece1ea.png)

Does this seem relevant to you  ?

**Comment by paulfitz** [comment]
Yes, we're interested in having optional descriptions for columns (as you're doing in https://github.com/gristlabs/grist-core/pull/406), for widgets (as you propose here), and for tables. I don't know if there are already design ideas, cc @anaisconce. For widgets, the places you suggest seem plausible. In the first one, some care would be needed to avoid an ambiguity about whether the table or the widget is being described.

**Comment by CamilleLegeron** [comment]
I was also thinking of doing the same presentation of column descriptions with the `i` icon. If the `i` is only on the right of the widget title and not on the left panel you think it may be an ambiguity ?
