### ISSUE TITLE
Internationalization and localization set up

### ISSUE THREAD

**Issue by paulfitz** [gristlabs/grist-core#46]
It is a big planet and Grist belongs everywhere.

**Comment by paulfitz** [comment]
We've started work on currency formatting #78

**Comment by anaisconce** [comment]
Making a note to support right-to-left text direction for languages like Arabic and Hebrew.

**Comment by paulfitz** [comment]
Currency formatting was implemented and documented https://github.com/gristlabs/grist-core/issues/78

**Comment by paulfitz** [comment]
There is some support now for adding translations of Grist https://github.com/gristlabs/grist-core/blob/main/documentation/translations.md although no translations have yet been done.

**Comment by paulfitz** [comment]
There's been a lot of progress on translations, thanks in large part to a *lot* of volunteer work.
 * https://community.getgrist.com/t/translating-grist/2086
 * https://hosted.weblate.org/projects/grist/client/
