### ISSUE TITLE
Unable to access documents since using nginx reverse proxy

### ISSUE THREAD

**Issue by asitemade4u** [gristlabs/grist-core#469]
Hi Paul,
Since I updated to latest version in docker, I get a blocking error accessing EVERY document from Grist dashboard.
The error is:
```
Error accessing document
You can try reloading the document, or using recovery mode. Recovery mode opens the document to be fully accessible to owners, and inaccessible to others. It also disables formulas. [Loading chunk 282 failed. (error: https:&#x2F;&#x2F;grist.qtpl.net&#x2F;v&#x2F;unknown&#x2F;282.bundle.js)]
```

When I try the **Recovery mode** I get into a loop and nothing gets repaired.

For the record:
- I am using an nginx reverse proxy in front of Grist (but it worked well until now)
- I host Grist's data on a Postgres database equally hosted in a docker container

Please help.
Best,
Stephen

**Comment by asitemade4u** [comment]
UH-OH,
I reverted to previous version before `latest`, which is the `1.0.8` and I still get the error accessing documents.

**Comment by asitemade4u** [comment]
OK, things got real weird here (and I asssume you may well close the bug report altogether).

1. I noticed I was still able to access all the documents using Firefox instead of Brave (my default Web browser)
2. So I reset Brave flags
3. Then I deleted all history in Brave
> Now I am able to access all documents in Grist.
Probably a case of corrupted cache?

**Comment by asitemade4u** [comment]
Probably corrupted Web browser cache

**Comment by paulfitz** [comment]
Hi @asitemade4u, yes we've seen users report `Loading chunk ...` failures very occasionally, and they seem to always be cache problems - some scenario like internet goes down briefly, browser loads a chunk as say an empty file but is convinced it got that right, and then can't really be persuaded to load Grist without resetting browser cache.
