### ISSUE TITLE
Postgres version still <= 11?

### ISSUE THREAD

**Issue by asitemade4u** [gristlabs/grist-core#475]
Hi, and thank you for this awesome product!
We are self hosting Grist with a Postgres database.
Is the recommended version is still Postgres 11 or earlier?
We are using Postgres 13 for all other projects and would happily normalize Grist to Postgres 13 too...

**Comment by paulfitz** [comment]
Hi @asitemade4u, the blocker on using more recent postgres was removed some time back. 13 should be fine, and we are ourselves using 14 for docs.getgrist.com

I see that https://support.getgrist.com/self-managed/#what-is-a-home-database hasn't been updated, sorry about that!
