### ISSUE TITLE
Document tours

### ISSUE THREAD

**Issue by paulfitz** [gristlabs/grist-core#48]
Added on-boarding features for built-in instruction.

**Comment by paulfitz** [comment]
Document tours were implemented, and are used in many examples in https://templates.getgrist.com/

The implementation wasn't polished to the point where it became a feature that users could apply to their own documents in a friendly, documented way. Leave a comment on this thread if you're interested in that.

**Comment by MHOOO** [comment]
Would love to know more about this feature, or other ways of helping people "use" the table(s) that I have created for them (i.e. tooltips or similar)

**Comment by anaisconce** [comment]
You can definitely use this feature! As Paul said, it isn't polished yet, but it works! Here's the fastest way to learn how to build one:

1. Visit a template with a doc tour and edit the URL to add `/p/GristDocTour`  after the document's name. E.G. https://templates.getgrist.com/gtzQwTXkgzFG/Meme-Generator/p/GristDocTour

This reveals a special, hidden table named GristDocTour. It is only visible when you modify the url as described above. 

It has 4 columns. 
* Title - the pop-up header; this is a text column
* Body - the pop-up body; this is a text column
* Placement - a text column that places the pop-up in relation to a cell with words like right, top, bottom. https://popper.js.org/ has an interactive tool that shows how this works.
* Location - a text, formula column with the formula `SELF_HYPERLINK()+$Location_Cell` SELF_HYPERLINK adds the URL through to the end of the document's title.
* Location Cell - another text column. This is where you copy and past a cell's anchor link from `/p` onwards. E.G. /p/3#a1.s3.r3.c3

2. Create a table named GristDocTour in your document with the columns described above. 

Finding anchor links in a row:
![image](https://user-images.githubusercontent.com/69366135/155166439-23f8550e-02d9-4b1e-aafd-c4f64aa1cf3d.png)

Finding anchor links in a card:
![image](https://user-images.githubusercontent.com/69366135/155166625-ff85c8f9-661f-4a43-849c-0fe4038218b9.png)


Finding anchor links in a card list:

![image](https://user-images.githubusercontent.com/69366135/155166574-5a2bf4cc-00eb-446b-84bc-4cfaeb28e604.png)

**Comment by MHOOO** [comment]
Thanks, that is actually quite simple!

**Comment by anaisconce** [comment]
FYI, there's three more optional columns you may add to a doc tour. Here's the full explanation in our forum: https://community.getgrist.com/t/creating-document-tours/688
