### ISSUE TITLE
lookupOne / lookupRecords for ReferenceList columns

### ISSUE THREAD

**Issue by vviers** [gristlabs/grist-core#481]
On the wishlist side of things for now as I hacked a workaround, but it would be nice if we could use the `lookupOne` / `lookupRecords` methods to lookup data based on a ReferenceList columns.

If "Cities" is a ReferenceList columns, and there's another table called "MyOtherTable" with a "city" column referencing the same reference data, `MyOtherTable.lookupOne(city=$Cities)` never returns a match even though both references point to the same thing (which makes sense since one is a Reference and the other is a ReferenceList). 

What I ended up doing was `MyOtherTable.lookupOne(city=list($Cities)[0])` but this only return matches for the first reference in the ReferenceList (which is good enough for my use-case). I guess some kind of list comprehension like `[MyOtherTable.lookupOne(city=list($Cities)[i]) for i in range(len($Cities))]` would work too but this feels cumbersome.

Maybe introducing a new keyword like ANYOF() which would let users do `lookupOne(City=ANYOF($Cities))` would work ? wdyt ?

**Comment by paulfitz** [comment]
I think I have good news for you, try `lookupOne(City=CONTAINS($Cities))`
Documentation at https://support.getgrist.com/functions/#contains
If it works for you, I think we need to talk it up in more places, it is hard to discover...

**Comment by vviers** [comment]
It works perfectly ! thanks ! 💯 
I'm not sure how I missed it while looking over the documentation... definitely worth knowing about !
