### ISSUE TITLE
New translated string not taken into account

### ISSUE THREAD

**Issue by CamilleLegeron** [gristlabs/grist-core#487]
Hello
We validated several string translation two months ago, in https://hosted.weblate.org/ it validate and in the main branch in file `fr.client.json` it is present but in the getgrist main instance the string are not translated.

An exemple : 
![image](https://user-images.githubusercontent.com/19594405/231093140-3909584e-fa98-4724-80ef-9720140017ac.png)

Do we forgot a step ?

**Comment by CamilleLegeron** [comment]
I think there is something else because all of the 50 strings we translated 2 months ago are ignored, whether or not they have a space at the end (we translated all the welcomeTour strings, and none are taken into account)

**Comment by georgegevoian** [comment]
It looks like *.client.json is using `welcomeTour` as the key, but `WelcomeTour.ts` is expecting `WelcomeTour`.

**Comment by paulfitz** [comment]
Ah, good point, it looks like the makeT call uses `WelcomeTour` https://github.com/gristlabs/grist-core/blob/5730262c699bf823cd9faef3b445917ed8a6c182/app/client/ui/welcomeTour.ts#L11 while the filename is `welcomeTour`.

**Comment by CamilleLegeron** [comment]
ooooh yes, well seen
It seems that the cleanest way is the rename the file, I let you check my PR
