### ISSUE TITLE
SandboxError: [Sandbox] KeyError 'Budget (millions)

### ISSUE THREAD

**Issue by LouisDelbosc** [gristlabs/grist-core#492]
I tried uploading some data using the API to a document called `Favorite Films` (the one you're using in your tests).
However I encounter an error I'm not sure how to solve. 

```js
// JSON object I'm sending
{
  "records": [
    {
      "fields": {
        "Title": "Forest gump",
        "Budget (millions)": "1000000"
      }
    }
  ]
}

// Error I received
{
  error: "Error manipulating data: [Sandbox] KeyError 'Budget (millions)'"
}
```

To make the request, I used the documentation here: https://support.getgrist.com/api/#tag/records/paths/~1docs~1%7BdocId%7D~1tables~1%7BtableId%7D~1records/post

_The error on my grist instance_
<img width="1180" alt="Screenshot 2023-04-13 at 17 59 40" src="https://user-images.githubusercontent.com/11460746/231817645-1d57acaa-eb15-49d3-88f4-ca7348c6ce2b.png">

@paulfitz @dsagal Do you have any idea how to solve this ? I have the same issue for the field `Société` or `Favorite Film`

cc @CamilleLegeron

**Comment by georgegevoian** [comment]
You need to use the column id for the key (e.g. `Budget_millions`). Sorry for any confusion - I think the documentation needs to be updated to be more clear.

**Comment by LouisDelbosc** [comment]
Thanks @georgegevoian. So I have to query the columns like here `https://support.getgrist.com/api/#tag/columns/paths/~1docs~1%7BdocId%7D~1tables~1%7BtableId%7D~1columns/get` and do the proper mapping ?

**Comment by georgegevoian** [comment]
That's correct.
