### ISSUE TITLE
Row duplication does not trigger trigger formula "on new records" event

### ISSUE THREAD

**Issue by Vinschni** [gristlabs/grist-core#496]
I noticed that trigger formulas are not executed for rows created through duplication.
This is conterintuitive to me as duplication is creating a new record. 
Would you classifiy this as a bug or is it intended behavior?
![Animation](https://user-images.githubusercontent.com/340731/232779694-80b3158e-7d1d-455f-bec5-6a3e70b0d7fd.gif)

**Comment by berhalak** [comment]
This is intended behavior, as this also works the same way when you manually copy the entire row and paste it onto a new row. The formula that is triggered only for new records is meant to provide some default values only, and here the value is already present in the source row.
As a workaround, you can also set the trigger on the column itself (and create a so-called data cleanup formula). This will recalculate it for a new row as well, and every time you manually update this cell.

![image](https://user-images.githubusercontent.com/11277225/232846769-f7346a20-a531-4493-a444-be2739959ec6.png)

**Comment by Vinschni** [comment]
Great. Solves the problem.
