### ISSUE TITLE
conditional formatting per widget

### ISSUE THREAD

**Issue by wunter8** [gristlabs/grist-core#500]
I set up conditional formatting for rows of data in a widget on a page. Then I looked at the same data on another page and saw the same conditional formatting being applied.

I considered just adding something to the conditional formatting formula like `$Due_Date < TODAY() AND widget == "NAME"`, but I didn't see any built-in feature to identify the current widget like you can for the current UserTable or current Record.

Is it possible to apply different conditional formatting to the same data in different widgets?

**Comment by dsagal** [comment]
This is possible using a little known option in the Column tab of the Creator Panel: towards the bottom you'll find a grey bit that says something like "Field in 3 views: [Common ▾]":

<img width="242" alt="Screenshot 2023-04-24 at 7 50 18 PM" src="https://user-images.githubusercontent.com/1091143/234139347-dd47ccbf-5c21-4e34-9adb-ef0e8298e8eb.png">

In Grist, the same data (and the same columns) can be shown in different views. By default a column use common settings across all views it appears in. This is the setting that lets you make an exception.

If you click into the dropdown, you'll see the option to "Use separate settings":

<img width="241" alt="Screenshot 2023-04-24 at 7 52 34 PM" src="https://user-images.githubusercontent.com/1091143/234139536-248efb4a-4057-4e9c-93aa-4e6a600f43a1.png">

Now, changes to this column, including conditional formatting formulas, will apply only to the field in this particular view, and will not affect other views.

By the way, if you later want to revert, or to replace the common settings with the customized ones, the same dropdown offers those options:

<img width="238" alt="Screenshot 2023-04-24 at 7 54 59 PM" src="https://user-images.githubusercontent.com/1091143/234139822-24a91746-0f7f-46bb-92a2-92ac58deba8c.png">

Here is an example of a page that shows the same table with the same data in two widgets, with separately-configured conditional styles:

<img width="941" alt="Screenshot 2023-04-24 at 7 56 51 PM" src="https://user-images.githubusercontent.com/1091143/234140043-a99ef7f2-4e35-4a8c-a9eb-560387c4b9c2.png">

**Comment by wunter8** [comment]
Oh, great! Thank you for the quick response.

This only works for column conditional formatting then? Not for row conditional formatting? (I know I can make it appear as "row" conditional formatting by setting the same formula for each column of the particular widget, but I want to make sure there's not another hidden feature I missed)

**Comment by dsagal** [comment]
Ah, good question. You are right, what I described is a feature specific to columns and doesn't apply to row conditional formatting. Cc'ing @berhalak who would know if there is a hidden feature that I don't know about 🙂

**Comment by wunter8** [comment]
I'll go ahead and close this for now. Setting the conditional column formatting per widget is sufficient. Thanks!
