### ISSUE TITLE
Bug: In ACL : It is no longer possible to check that a reference from another table matches the current record

### ISSUE THREAD

**Issue by CamilleLegeron** [gristlabs/grist-core#502]
Hi,

Until now, to check that a reference from another table matches the current record we use the expression `rec.id` in permissions. It worked very well. 
But recently it considered it as an error and the permission can't be changed or saved with that expression.

In this exemple we create a rule that say the user can only see the regions to which it is connected. The rule has been validated few weeks ago. But we recently found that this rule was considered invalid, even though it is taken into account in the data display for users. 
![image](https://user-images.githubusercontent.com/19594405/234342089-54cdff9b-dc41-49fd-8963-066fc59369c4.png)

Thanks for help

**Comment by georgegevoian** [comment]
Fixed in [this commit](https://github.com/gristlabs/grist-core/commit/8bedaedab6696e4c949a7e3f33de90287661246d).
