### ISSUE TITLE
Upgrade wrapt to support Python 3.11 and Debian Bookworm

### ISSUE THREAD

**Issue by fflorent** [gristlabs/grist-core#534]
Debian Bookworm has been released this month.

With Bookworm, the [packaged Python3 runtime](https://packages.debian.org/bookworm/python3) version is 3.11

But due to the `wrapt` dependency (version 1.12.1 as described [in requirements](https://github.com/gristlabs/grist-core/blob/3d808f67f1b03dfbbd17f87bce538a6ec4815cab/sandbox/requirements3.txt#L33)), the Python sandbox is broken (the majority of the `yarn test:python` tests fail)

The issue has been documented and solved since version 1.14.0 of wrapt: https://github.com/GrahamDumpleton/wrapt/issues/196

I don't know whether that's safe to just upgrade wrapt to the latest version. What do you think?

**Comment by paulfitz** [comment]
Any objections @alexmojaki, @dsagal? It looks likely to be benign to me, plus `wrapt` appears to still support python2.7 (we have some users who still depend on this).

**Comment by alexmojaki** [comment]
Probably fine. 3.11 support would be good.

**Comment by alexmojaki** [comment]
Huh, I didn't expect that to work immediately. https://github.blog/2013-03-18-closing-issues-across-repositories/
