### ISSUE TITLE
Is it possible for a Grist spreadsheet to be publically viewable (Viewer mode only), like a Google Sheet?

### ISSUE THREAD

**Issue by sbutler-gh** [gristlabs/grist-core#574]

**Comment by dsagal** [comment]
Absolutely! This is documented here: https://support.getgrist.com/sharing/#public-access-and-link-sharing.

In a self-hosted setup, there are a few of environment variables available to adjust this and related behaviors: GRIST_FORCE_LOGIN, GRIST_SUPPORT_ANON, GRIST_LIST_PUBLIC_SITES, documented at https://github.com/gristlabs/grist-core#environment-variables.
