### ISSUE TITLE
Fix count for boolean columns

### ISSUE THREAD

**Issue by vviers** [gristlabs/grist-core#578]
Hey there 👋🏼 

When selecting a `text` column, only the non-empty values are counted by `count` which is very logical (to me at least!)

<img width="551" alt="Screenshot 2023-07-19 at 17 07 50" src="https://github.com/gristlabs/grist-core/assets/30295971/cfd280a6-65bb-45b7-b354-23d591c37a82">

However, `bool` values are counted regardless of whether they are `true` or `false` which is not the behaviour I am expecting 

<img width="554" alt="Screenshot 2023-07-19 at 17 08 16" src="https://github.com/gristlabs/grist-core/assets/30295971/410f3c4a-9c4d-4fed-9c39-8b67a2ac6fcd">

I can probably fix that fairly easily, are you OK with this ?

**Comment by dsagal** [comment]
Makes sense, absolutely!

**Comment by fflorent** [comment]
@vviers I guess this issue can be closed now your patch has been merged?
