### ISSUE TITLE
Download behaviour for widgets with SelectBy

### ISSUE THREAD

**Issue by vviers** [gristlabs/grist-core#628]
Hey there 👋🏼 

When downloading (as xlsx or csv) a widget that is "selected by" the content of another widget, I would expect to only get the line(s) that I actually see instead of the full data, much like when downloading a filtered table.

Is there a good reason to consider the SelectBy of a widget as a different thing than a filter when it comes to downloading the content of a widget ?

As always, more than happy to implement a fix if you think that's worth it :)

**Comment by alexmojaki** [comment]
I implemented this recently in https://github.com/gristlabs/grist-core/commit/bc54a6646e863f393de6d2b12a5bc4d4ac910c54 and it seems to be working in production. Are you maybe on a slightly outdated Docker image?

**Comment by vviers** [comment]
> Are you maybe on a slightly outdated Docker image?

Woops ! yes, probably ! thanks for the fix and sorry for the noise :)

**Comment by alexmojaki** [comment]
No worries :+1:
