### ISSUE TITLE
Currently, when a column is created, it is a formula by default

### ISSUE THREAD

**Issue by CamilleLegeron** [gristlabs/grist-core#634]
When we create a new column, the parameter `isFormula` is True by default. Until a formula is not written `isFormula` could be False, right? 
That causes problem in our now app grist form because formula column are ignored, so all new columns are ignored. We have to press the button `Make into data column` on all now columns when they were never formulas.

**Comment by dsagal** [comment]
There is a concept of an "Empty Column", which is identified by `isFormula` of `True`, and `formula` that's empty. An empty column has some special behavior in that the UI allows entering either data or a formula (if one starts typing with an `=` sign) without the user having to do an extra action to decide which one they want.

(This is somewhat controversial, and we've been mulling over whether we can do something better.)

For now, the thing to keep in mind is that there are data, formula, and empty columns. To distinguish them, see [isEmpty](https://github.com/gristlabs/grist-core/blob/fe12562ad7043606bc139ae98b2f0462168681ce/app/client/models/entities/ColumnRec.ts#L104) and [isRealFormula](https://github.com/gristlabs/grist-core/blob/fe12562ad7043606bc139ae98b2f0462168681ce/app/client/models/entities/ColumnRec.ts#L107) helpers. So in your logic to ignore formula columns, you may want to adjust it to ignore only the "real formula" columns.

**Comment by CamilleLegeron** [comment]
Thanks @dsagal for your explanation. I think with this information it will be no more worries.
