### ISSUE TITLE
API enhancement : upload a new document in a workspace 

### ISSUE THREAD

**Issue by xadorfr** [gristlabs/grist-core#635]
Hello everyone,

This issue follows a discussion in the community forum : https://community.getgrist.com/t/new-api-feature-request-post-grist-file/3042/2

At now the Grist API allows to download a document in its grist format (sqlite) : `GET /{docId}/download`

We would also like to be able to POST a new grist document in a workspace.

Our use case : we have a template file (with specific views, access rules etc) that we want to use as a base file when we create a new document.

As suggested by @paulfitz, a trail that may be followed could be the completion of the `POST /api/docs` endpoint to allow a workspaceId as parameter to create a regular document, as described in the TODO comment.

https://github.com/gristlabs/grist-core/blob/1774d0314fd33d8a97151f428249398878a17c0e/app/server/lib/DocApi.ts#L1170-L1192

**Comment by xadorfr** [comment]
Do this small changes would be enough ? 

```
+      let workspaceId: number|null;
       let parameters: {[key: string]: any};
       if (req.is('multipart/form-data')) {
         const formResult = await handleOptionalUpload(req, res);
@@ -1199,18 +1200,19 @@ export class DocWorkerApi {
       } else {
         parameters = req.body;
       }
-      if (parameters.workspaceId) { throw new Error('workspaceId not supported'); }
+      workspaceId = parameters.workspaceId || null;
       const browserSettings: BrowserSettings = {};
       if (parameters.timezone) { browserSettings.timezone = parameters.timezone; }
       browserSettings.locale = localeFromRequest(req);
       if (uploadId !== undefined) {
-        const result = await this._docManager.importDocToWorkspace(userId, uploadId, null,
+        const result = await this._docManager.importDocToWorkspace(userId, uploadId, workspaceId,
                                                                    browserSettings);
       }
```

**Comment by paulfitz** [comment]
@xadorfr a fleshed-out version of this change landed in https://github.com/gristlabs/grist-core/pull/655 and should now be in the `latest` docker image.

**Comment by xadorfr** [comment]
That's very good news ! Thanks a lot for this quick improvement, this is very appreciated !
