### ISSUE TITLE
Distinguish Update and Read permissions on permissions

### ISSUE THREAD

**Issue by CamilleLegeron** [gristlabs/grist-core#647]
For know we can decide who can see the permission rights with 
![image](https://github.com/gristlabs/grist-core/assets/19594405/f76f20e3-4f08-4423-960b-7c37e7bf242d)

But when we give access with the `R` to some users, they can update the permissions ..
I want to give access to the "View as" option to some users to help them perform support but without giving the possibility to edit the permissions.

**Comment by dsagal** [comment]
I think this option is working as intended at the security level, but has an issue in the user interface. Access Rules can only be edited by someone who has an OWNER-level access to the document. For anyone else (Editors or Viewers), if you give them the `R` (read) permission, they will be able to see the rules, but if they try to change them and save the changes, they'd see an error like this:

<img width="363" alt="Screenshot 2023-08-28 at 8 12 45 AM" src="https://github.com/gristlabs/grist-core/assets/1091143/ecf32cf6-bf06-40e8-a70a-62a7505260a8">

Do you see the same thing? If yes, then the confusing part is that the user interface makes it seem like rules can be edited -- users can make changes and click the "Save" button -- even though any changes are guaranteed to lead to an error. That would be good to fix.

**Comment by CamilleLegeron** [comment]
Thanks @dsagal 
In fact I did not try to save. It's working fine

**Comment by dsagal** [comment]
If you have an interest in fixing the UI, so that a non-owner sees a view-only interface, that would be a worthwhile improvement.
