### ISSUE TITLE
Monitoring Grist using Prometheus or OpenTelemetry?

### ISSUE THREAD

**Issue by fflorent** [gristlabs/grist-core#671]
At the ANCT, we faced a Ouf Of Memory crash of Grist. The problem was somehow solved but we'd like to monitor Grist a bit more, beyond logs.

To do so, we think of either implementing a Prometheus exporter or maybe sending metrics using the OpenTelemetry API.

I'd like to know your feelings about it, whether that's something that would interest you, and whether you have a preference regarding the implementation :).

**Comment by paulfitz** [comment]
No particular preferences. Ourselves, for our SaaS, we ingest the grist logs into elasticsearch (along with some aws-y metrics) and have various alerting and dashboards set up off of that and a few other aws-y services.

I'd be ok with you adding something tasteful for monitoring, though we at Grist Labs would be unlikely to use any plumbing parts of it (as opposed to new metrics - I'd say we'd happily use+maintain those all right, even if they overlap with numbers we have from aws-y sources).

Ideally, solution would be not to heavy in terms of new dependencies, optional, and cross-platform.

**Comment by fflorent** [comment]
We are currently trying to serve Prometheus data, using [prom-client](https://www.npmjs.com/package/prom-client). This library seems to not have many dependencies (I saw it has the following dependency tree: `prom-client → tdigest → bintrees`, which seems fair).

And I would probably propose it as an [optional peer dependency](https://yarnpkg.com/configuration/manifest#peerDependenciesMeta).

Also I would propose to use an environment variable, like `GRIST_PROMETHEUS_EXPORTER_PORT`, which if set to a certain value, would install `prom-client` and run a special server so Prometheus can query the metrics. I would take care of documenting so it would be highly recommended to use a port not exposed to the internet. This server code will appear in a separate module, using the [`--require`](https://nodejs.org/api/cli.html#-r---require-module) or the [`--import`](https://nodejs.org/api/cli.html#--importmodule) option of nodejs as invoked in `sandbox/run.sh`. So that code would be separated from the rest of the codebase.

First we'll see if it works as expected in our case and propose it as a PR in a second place, if that's OK for you.

**Comment by paulfitz** [comment]
That could work @fflorent, will be interested to see how it goes.

**Comment by fflorent** [comment]
I preferred to add prom-client as a regular dependency, with the hope it's OK (it adds 3/4 Mb to the `node_modules` folder), because we noticed that calling `yarn add` on a fresh install may slow down the startup (± 2 minutes of overhead). In our case, when the application crashes, it penalizes us a bit.

**Comment by paulfitz** [comment]
> I preferred to add prom-client as a regular dependency, with the hope it's OK (it adds 3/4 Mb to the `node_modules` folder), because we noticed that calling `yarn add` on a fresh install may slow down the startup (± 2 minutes of overhead). In our case, when the application crashes, it penalizes us a bit.

One trick that can be handy is installing optional dependencies one level up the directory hierarchy from Grist - node will still find them there. If you build a docker image, the Dockerfile will pick up any extra dependencies in `ext` and add them this way. That said, I'm not dead set against adding prom-client as a regular dependency, and 3/4 Mb isn't too bad.
