### ISSUE TITLE
Feature Request: Hover over the column name

### ISSUE THREAD

**Issue by gmouawad** [gristlabs/grist-core#680]
In the document table view, have a tooltip once a mouse hovers over the column's header.

The reason behind that, is sometimes we need to have a header that contains many characters

**Comment by anirudhsudhir** [comment]
I'd like to work on this issue. Could you assign it and give me a better idea?

**Comment by anirudhsudhir** [comment]
I'd like to work on this issue. Could you assign it and give me a better idea?

**Comment by fflorent** [comment]
Hi @gmouawad!

I think your request is covered by this issue: https://github.com/gristlabs/grist-core/issues/543

If you agree, I can close this one and let you subscribe the other one, and maybe react and write additional feedback / ideas :).

Cheers!
Florent

**Comment by gmouawad** [comment]
> Hi @gmouawad!
> 
> I think your request is covered by this issue: #543
> 
> If you agree, I propose to close this one and let you subscribe the other one, and maybe react and write additional feedback / ideas :).
> 
> Cheers! Florent

Hello @fflorent yes similar request, I have subscribed to the other one, and I will close this issue with this comment.

Thanks
