### ISSUE TITLE
Widgets not working with release v1.1.5 

### ISSUE THREAD

**Issue by alfredo-ardito** [gristlabs/grist-core#698]
Hello, since a few days I've been using widgets with Grist Core release 1.1.4 and everything worked perfectly. As soon as I upgraded Grist Core to release 1.1.5 widgets stopped working or misbehaved without showing any error messages. I then went back to Grist Core release 1.1.4 and widgets worked perfectly as before. I assume Grist Core 1.1.5 is somehow buggy. 
Has anyone experienced widgets issues with Grist Core 1.1.5. Do I need to setup something specific to make widgets work with Grist 1.1.5?

**Comment by georgegevoian** [comment]
Hi @alfredo-ardito.

By widgets, you're referring to custom widgets? Can you try the image with the `latest` tag and see if there's any improvement?

**Comment by alfredo-ardito** [comment]
Yes. I forgot to mention custom widgets. I'll try the image and let u know

**Comment by alfredo-ardito** [comment]
I tried 1.1.6 and custom widgets are working as expected.
