### ISSUE TITLE
Opening a referenced record easily

### ISSUE THREAD

**Issue by anaisconce** [gristlabs/grist-core#704]
It would be convenient if referenced records in Reference and Reference List columns could be easily opened with a click. Currently, users must add a widget to the page, linked to the reference column, to show referenced records. This takes up precious page space. 

Requests:

- https://community.getgrist.com/t/navigate-to-referenced-row-from-reference-cell/2355
- https://github.com/gristlabs/grist-core/issues/673

Explanation of the solution we're working on here: https://github.com/gristlabs/grist-core/issues/673#issuecomment-1757763542
> * Every table has a default card view.
> * By default, all referenced records in Reference and Reference List columns can be opened in this default card view in a lightbox (no need to configure or add any more widgets to pages, just works).
> * In addition, any row in a table can be opened in this default card view.
> * That default card view can be configured per table, by document editors with schema permissions. Each table's default card configuration is global for the doc, which means that opening records in the default card (rows or referenced records) from any page/widget applies the table's configured card widget. If you need something different, you can always add a card using the current method.
> * Default card view can be disabled for specific tables. There's sometimes helper tables in documents that would be confusing if opened in a card.

**Comment by newturok** [comment]
Maybe just start with this one?
https://community.getgrist.com/t/redirect-to-reference-record-by-click/1734

**Comment by dsagal** [comment]
This was released a while ago! Announced here: https://support.getgrist.com/newsletters/2023-11/#record-cards
