### ISSUE TITLE
Support OIDC directly

### ISSUE THREAD

**Issue by fflorent** [gristlabs/grist-core#707]
It would simplify our architecture if Grist could support OIDC directly, just like it supports SAML.

There seem to be many people also wishing to use OIDC in this issue: https://github.com/gristlabs/grist-core/issues/44

What do you think?

**Comment by paulfitz** [comment]
Was just talking about this yesterday with @anaisconce. I agree it would be very useful, and that a lot of people have asked for it, and I think it is very achievable with a new implementation of the `GristLoginSystem` interface.

**Comment by helmut72** [comment]
Even if I have a working Grist SAML configuration, native OIDC would be fantastic. Make my environment so much easier and lean (dropping Keycloak). Grist is the one and only app that I use, that requires SAML.

**Comment by helmut72** [comment]
From:
https://github.com/gristlabs/grist-core/pull/717#pullrequestreview-1723296676

> I think it'll be a popular configuration!

The `closed` label will feel like xmas, easter and birthday on the same day. Rarely follow pull requests, but this is an exception ;)

**Comment by helmut72** [comment]
Thanks a lot!!

Some feedback here...
https://github.com/gristlabs/grist-core/issues/740
https://github.com/gristlabs/grist-core/issues/739
