### ISSUE TITLE
v1.1.7: Uncaught ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by jperon** [gristlabs/grist-core#731]
When accessing the root of my self-hosted instance with Docker image `gristlabs/grist:1.1.7` or `gristlabs/grist:latest`, I get a blank page, with `Uncaught ReferenceError: jQuery is not defined` in the console. I don’t get the error:

 - with `gristlabs/grist:1.1.6`;
 - when directly accessing a document url.

**Comment by paulfitz** [comment]
Looking, thanks for reporting...

**Comment by paulfitz** [comment]
Not able to replicate yet. @jperon are there any hints from dev console, particularly the network tab? Do you see this in multiple browsers or a particular browser?

**Comment by jperon** [comment]
I get this error on both Firefox and Chromium. On the network tab, they only get `main.bundle.js`. You have the logs below:

Chromium:

![image](https://github.com/gristlabs/grist-core/assets/4775231/27393be2-bbb4-429f-acdf-84e6fc65534c)

```
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'run-ad-auction'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'join-ad-interest-group'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'browsing-topics'.
external var "jQuery":1 Uncaught ReferenceError: jQuery is not defined
    at 65311 (external var "jQuery":1:18)
    at __webpack_require__ (bootstrap:19:32)
    at 86277 (backbone.js:17:27)
    at __webpack_require__ (bootstrap:19:32)
    at 96502 (BehavioralPromptsManager.ts:183:3)
    at __webpack_require__ (bootstrap:19:32)
    at 7632 (ClientScope.ts:54:3)
    at __webpack_require__ (bootstrap:19:32)
    at app.js:13:15
    at app.js:59:1
65311 @ external var "jQuery":1
__webpack_require__ @ bootstrap:19
86277 @ backbone.js:17
__webpack_require__ @ bootstrap:19
96502 @ BehavioralPromptsManager.ts:183
__webpack_require__ @ bootstrap:19
7632 @ ClientScope.ts:54
__webpack_require__ @ bootstrap:19
(anonymous) @ app.js:13
(anonymous) @ app.js:59
(anonymous) @ app.js:59
```

Firefox:

![image](https://github.com/gristlabs/grist-core/assets/4775231/ffede81a-c124-4d10-a570-7edd48851a1f)

```
Uncaught ReferenceError: jQuery is not defined
    65311 index.js:55
    Webpack 10
        __webpack_require__
        86277
        __webpack_require__
        96502
        __webpack_require__
        7632
        __webpack_require__
        <anonymous>
        <anonymous>
        <anonymous>
[index.js:55](https://db.stemarie.dynv6.net/node_modules/which-typed-array/index.js)
    65311 index.js:55
    Webpack 10
        __webpack_require__
        86277
        __webpack_require__
        96502
        __webpack_require__
        7632
        __webpack_require__
        <anonyme>
        <anonyme>
        <anonyme>
GET
https://db.stemarie.dynv6.net/favicon.ico
```

**Comment by jperon** [comment]
In case this helps, here is the command I use to launch grist:

```sh
docker run --rm --name=grist \
  -p 127.0.0.1:8484:8484 \
  -e DEBUG=1 \
  -e APP_DOC_INTERNAL_URL=http://localhost:8484 \
  -e APP_DOC_URL=https://db.<<<DOMAIN>>>.dynv6.net \
  -e APP_HOME_URL=https://db.<<<DOMAIN>>>.dynv6.net \
  -e GRIST_ADAPT_DOMAIN=true \
  -e COMMENTS=true \
  -e GRIST_PROXY_AUTH_HEADER=x-forwarded-user \
  -e GRIST_SINGLE_ORG="<<<MY_ORG>>>" \
  -e GRIST_DEFAULT_LOCALE=fr-FR \
  -e GRIST_EXPERIMENTAL_PLUGINS=true \
  -e GRIST_BACKUP_DELAY_SECS=120 \
  -e GRIST_DEFAULT_EMAIL=guest \
  -e GRIST_NEW_COLUMN_MENU=true \
  -e GRIST_SUPPORT_ANON=true \
  -e GRIST_SERVE_SAME_ORIGIN=true \
  -e GRIST_USER_ROOT="/" \
  -e GRIST_WIDGET_LIST_URL="" \
  -e GRIST_TRUST_PLUGINS=true \
  -e NODE_TLS_REJECT_UNAUTHORIZED="0" \
  -e PERMITTED_CUSTOM_WIDGETS=calendar \
  $* \
  -v $PWD/persist:/persist \
  -v $PWD/widgets:/plugins/widgets \
  -v $PWD/widgets_perso:/plugins/perso \
  gristlabs/grist:latest
```

**Comment by paulfitz** [comment]
Ah, thank you, there's a lead in there. @georgegevoian I see BehavioralPromptsManager mentioned.
Suspecting a race of some kind.

**Comment by georgegevoian** [comment]
@jperon is the body of the response to `/` the following:

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf8">
  </head>
  <body>
    <script src='/main.bundle.js'></script>
  </body>
</html>
```

**Comment by georgegevoian** [comment]
It looks like there's an `index.html` file in Grist's root that has the contents above. It's missing a few libraries like jQuery; if that's the file being served, it would explain why you're having trouble loading Grist and getting those errors.

I'm honestly not entirely sure what the purpose of the file is, or why it is being served instead of `app.html` (from the same directory), which is what should be served on `/`. Is it possible some recent change to web server configuration is causing it to pick up `index.html` instead of `app.html`? (I'd have expected `1.1.6` to also fail if that's the case, which makes it all the more puzzling.)

**Comment by dsagal** [comment]
To clarify, the webserver in front of Grist should forward all requests (including to `/` and to `/index.html`) to the Grist server (`http://localhost:8484` in your configuration). I.e. the correct behavior for fetching `/index.html` or `/app.html` should be a Grist error page that shows the Grist logo and says "page not found", since those files are used internally, and aren't intended to be served as files.

**Comment by jperon** [comment]
That’s weird, as I don’t see anything in my nginx config that would prevent that behaviour. And the fact is that, when I fetch `/` from the browser or `wget`, I get those entries in grist log:

```
nov. 08 20:59:22 servus grist.sh[2296033]: 2023-11-08 19:59:22.732 db.stemarie.dynv6.net GET / 200 5.825 ms - 139
nov. 08 20:59:22 servus grist.sh[2296033]: 2023-11-08 19:59:22.848 db.stemarie.dynv6.net GET /main.bundle.js 200 1.176 ms - 1261054
nov. 08 20:59:23 servus grist.sh[2296033]: 2023-11-08 19:59:23.393 db.stemarie.dynv6.net GET /main.bundle.js.map 200 1.203 ms - 4799571
```

The only file I see with the content @georgegevoian mentions [here](https://github.com/gristlabs/grist-core/issues/731#issuecomment-1802363961) is `/grist/static/index.html`, which is present in the Docker image both for `v1.1.6` and `latest`. But when I use `latest`, I get [this](https://github.com/gristlabs/grist-core/issues/731#issuecomment-1802363961); when I use `1.1.6`, I get that (with no change to nginx config):

```html
<!doctype html>
<html>
<head>
<meta charset="utf8">


<base href="/v/unknown/">

<link rel="icon" type="image/x-icon" href="icons/favicon.png" />

<link rel="stylesheet" href="jqueryui/themes/smoothness/jquery-ui.css">
<link rel="stylesheet" href="bootstrap/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="hljs.default.css">
<link rel="stylesheet" href="bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css">
<link rel="stylesheet" href="bundle.css">
<link rel="stylesheet" href="icons/icons.css">
<link rel="preload" href="locales/en.client.json" as="fetch" type="application/json" crossorigin>
<link rel="preload" href="locales/en.server.json" as="fetch" type="application/json" crossorigin>
<script>window.gristConfig = {"homeUrl":"https://db.stemarie.dynv6.net/","org":"ecolesaintemarie","baseDomain":"db.stemarie.dynv6.net","singleOrg":"ecolesaintemarie","helpCenterUrl":"https://support.getgrist.com","pathOnly":true,"supportAnon":true,"enableAnonPlayground":true,"supportEngines":["python2","python3"],"features":["helpCenter","billing","templates","multiSite","multiAccounts","sendToDrive"],"pageTitleSuffix":null,"pluginUrl":"http://plugins.invalid","stripeAPIKey":null,"googleClientId":null,"googleDriveScope":null,"helpScoutBeaconId":null,"maxUploadSizeImport":null,"maxUploadSizeAttachment":null,"timestampMs":1699474166968,"enableWidgetRepository":false,"survey":false,"tagManagerId":null,"activation":{"isManager":false},"enableCustomCss":false,"supportedLngs":["de","en","es","fr","it","nb-NO","pl","pt","pt-BR","ru","sl","uk","zh-Hans"],"namespaces":["client","server"],"featureComments":true,"featureFormulaAssistant":false,"assistantService":null,"permittedCustomWidgets":["custom.calendar"],"gristNewColumnMenu":true,"supportEmail":"support@getgrist.com","userLocale":null,"telemetry":{"telemetryLevel":"off"},"deploymentType":"core","templateOrg":null,"canCloseAccount":false,"plugins":[{"path":"/grist/plugins/core","id":"builtIn/core","manifest":{"name":"core","version":"0.0.0","description":"Grist core features","components":{"safePython":"sandbox/main.py"},"contributions":{"fileParsers":[{"fileExtensions":["csv","tsv","txt"],"parseFile":{"component":"safePython","name":"csv_parser"}},{"fileExtensions":["xlsx","xlsm"],"parseFile":{"component":"safePython","name":"xls_parser"}},{"fileExtensions":["json"],"parseFile":{"component":"safePython","name":"json_parser"}}]},"scripts":{"build":null,"test":null}}}]};</script>

<script>
try {
  if (localStorage.getItem('appearance') === 'dark' && !window.gristConfig.enableCustomCss) {
    const style = document.createElement('style');
    style.setAttribute('id', 'grist-theme');
    style.textContent = ':root {\n' +
      '  --grist-theme-bg: url("img/prismpattern.png");\n' +
      '  --grist-theme-bg-color: #333333;\n' +
      '}';
    document.head.append(style);
  }
} catch {
  /* Do nothing. */
}
</script>


<title>Loading... - Grist</title>
</head>
<body>
  
  <div id='grist-logo-wrapper'>
    <div class='grist-logo'>
      <div class='grist-logo-head'>
        <div class='grist-logo-grain grain-empty'></div>
        <div class='grist-logo-grain grain-col grain-flip grain-2'></div>
        <div class='grist-logo-grain grain-col grain-3'></div>
      </div>
      <div class='grist-logo-row'>
        <div class='grist-logo-grain grain-row grain-flip grain-4'></div>
        <div class='grist-logo-grain grain-cell grain-flip grain-5'></div>
        <div class='grist-logo-grain grain-cell grain-6'></div>
      </div>
      <div class='grist-logo-row'>
        <div class='grist-logo-grain grain-row grain-flip grain-7'></div>
        <div class='grist-logo-grain grain-cell grain-flip grain-8'></div>
        <div class='grist-logo-grain grain-cell grain-9'></div>
      </div>
    </div>
  </div>

  <div id="browser-check-problem" style="display: none;">
    <table class="browser-check-wrapper"><tr>
      <td class="browser-check-message">
        <span class="browser-check-desktop">
          Grist works best on modern Firefox or Chrome.
        </span>
        <span class="browser-check-mobile">
          Grist mobile works best on modern Firefox, Chrome, or Safari.
        </span>
        <a href="https://support.getgrist.com/browser-support" target="_blank">Learn more</a>
      </td>
      <td>
        <div class="browser-check-close" id="browser-check-problem-dismiss">Dismiss</div>
      </td>
    </tr></table>
  </div>

  <script src="jquery/dist/jquery.min.js" crossorigin="anonymous"></script>
  <script src="jqueryui/jquery-ui.min.js" crossorigin="anonymous"></script>
  <script src="bootstrap/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>
  <script src="bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js" crossorigin="anonymous"></script>
  <script src="main.bundle.js" crossorigin="anonymous"></script>
  <script type="application/javascript" src="browser-check.js" crossorigin="anonymous"></script>

</body>
</html>
```

**Comment by paulfitz** [comment]
Would you be able to try it without `GRIST_TRUST_PLUGINS`? I can't replicate your problem, but there could be a path to sadness there somewhere. Grist usually serves static assets with a prefix, but I remember something old in the plugin system that may serve a copy of them without prefix - and index.html is a static asset.

**Comment by jperon** [comment]
You got it: by disabling `GRIST_TRUST_PLUGINS`, it works.

**Comment by paulfitz** [comment]
Ah-hah. Still haven't managed to replicate, but I suspect the basic problem is this:
https://github.com/gristlabs/grist-core/blob/1831620c1986a7c7302705924096312f4bbf7a3c/app/server/lib/FlexServer.ts#L604-L606
That first line could serve `index.html` on your main port, when `GRIST_TRUST_PLUGINS` is set to put all plugin material there. Will look into it.

**Comment by rtgoodwin** [comment]
I also made this happen, and pretty sure it had to do with TRUST_PLUGINS or similar. Perhaps the UNTRUSTED url? 

Come to think of it the widget repo does provide the bare index.html in the root of it... I switched to serving them on a separate port via simple http and using the widget list, which I'm making progress on but had totally forgotten about this issue.

**Comment by paulfitz** [comment]
Working on a fix.

**Comment by paulfitz** [comment]
Made a change in https://github.com/gristlabs/grist-core/commit/12317097f748de057b43f5ee0fb41ea3a7819a55, included now in `latest` docker image, would be interested if it affects anything @jperon @rtgoodwin. Can't promise anything since don't have a replication, just a guess.

**Comment by jperon** [comment]
@paulfitz Just tested with `latest` image, and I get `Access denied`. I’m using header-based authentication, and it works with `stable`. My command to launch Grist is [here](https://github.com/gristlabs/grist-core/issues/731#issuecomment-1802208122).

![image](https://github.com/gristlabs/grist-core/assets/4775231/d79b7f06-d767-4d8e-b332-d14e20e25a0d)

**Comment by paulfitz** [comment]
@jperon there is some chance you are hitting an unrelated change in behavior made for security reasons https://github.com/gristlabs/grist-core/issues/750 (cc @dsagal)

**Comment by jperon** [comment]
Thank you very much for pointing to it. After setting `GRIST_IGNORE_SESSION=1`, it works, and this issue is fixed: I get the homepage when accessing the root of my instance with `latest`.

**Comment by paulfitz** [comment]
Thanks for reporting and testing!
