### ISSUE TITLE
OIDC use username instead of display name for Grists name field

### ISSUE THREAD

**Issue by helmut72** [gristlabs/grist-core#739]
Thanks a lot for OIDC! Works great in my limited tests yesterday. Public Sharing, Teams site ... all works, fantastic! Only found two minor issues.

One of them:

With SAML the Display Name is used and shown in Grists "Name" field in user preferences. For example "Foo Bar". OIDC use the username. But a username can be some kind of a technical name like fbar, foo.bar, foo_bar, bfoo .. and so on.

Would be cool if the Display Name is used instead of the username, that is also send to Grist. Have tested it with Authelia and Keycloak.

Thanks!

**Comment by fflorent** [comment]
I attempted to reproduce the issue. I don't see any `Display Name` field in Keycloak but instead the First Name and the Last Name.

If I setup a user with these fields:
![user profile in keycloak](https://github.com/gristlabs/grist-core/assets/371705/0e795835-cb1b-4935-80f4-fa8dfe53cb5d)

I see this user profile in Grist:
![user profile in Grist, where the first and last name are displayed](https://github.com/gristlabs/grist-core/assets/371705/d6ebe3bf-b4b3-47c2-acce-49f7680bb25b)

I may be missing something, but that's not the username which is used here. Is there something wrong with these screenshot (while setuping the user or in the information displayed in Grist)?

Thanks in advance!

**Comment by helmut72** [comment]
You are right regarding Keycloak. I have just switched from Authelia to Keycloak and I guess it was in the cache of Grist. Started Grist from scratch and it's now ok with Keycloak.

Need to investigate more why preferred_username if Authelia is used and why it's ok if Keycloak is used.

**Comment by fflorent** [comment]
I could not use Authelia while developing the feature.
If you find the reason of this behavior, would you be interested to propose a fix?

You would probably change this part of the code:
https://github.com/gristlabs/grist-core/blob/5f0c3bd8545256b4d3310ace197aace284ce8633/app/server/lib/OIDCConfig.ts#L158-L166

**Comment by helmut72** [comment]
Thanks for the hint. It looks like Authelia only send the `name` attribute (which contains the full name/display name), but not the `given_name` and `family_name` attributes.

https://github.com/authelia/authelia/issues/4338
https://github.com/authelia/authelia/issues/2868

Will close this issue it because it's a limitation of Authelia.

**Comment by fflorent** [comment]
@helmut72 Despite being a limitation of Authelia, it may be acceptable to add some workaround in the code. What do you think?

**Comment by helmut72** [comment]
Yes, most of the time `given_name` and `family_name` is a combination of `name` attribute. When I saw your code I also thought about splitting `name` attribute to both attributes. But it would be just a workaround. It's only done right if there is an ENV variable that enables the workaround or not.

All at all the behavior in your code is valid. Therefore it's not an issue and I have closed the issue.

**Comment by helmut72** [comment]
Sorry to hijack this issue, but what logout url do you have set in Keycloak? I've added `https://docs.example.com/signed-out`, but doesn't work.

In my browser I see this:
```
https://keycloak.example.com/realms/grist/protocol/openid-connect/logout?post_logout_redirect_uri=https%3A%2F%2Fdocs.example.com%2Fsigned-out&client_id=web-client
```

But Keycloak shows no valid redirect URI

**Comment by fflorent** [comment]
I'll make a proper documentation next week to show how to configure that.
I think you can use wildcard for the path if you're unsure. But IIRC the path looks like what you wrote (assuming you set `GRIST_ORG_IN_PATH` to some falsy value).

I'll let you know once the documentation is done to get your feedback.

**Comment by fflorent** [comment]
@helmut72 This PR may interest you: https://github.com/gristlabs/grist-core/pull/746

**Comment by helmut72** [comment]
Thanks, will follow it ;) Also Authelia can't handle logout like Keycloak. You mention in #746 Gitlab only. Btw, I have now logout working in Keycloak, but logout doesn't work from a team site.

**Comment by helmut72** [comment]
Update:
> but logout doesn't work from a team site.

I now moved from team sites with subdomains (eg. team1.grist.example.com) to path based style (eg. grist.example.com/o/team1) and logout works (with Keycloak), because it isn't a different subdomain. I will use this style because handling is also easier.
