### ISSUE TITLE
Package Grist on AWS Marketplace

### ISSUE THREAD

**Issue by anaisconce** [gristlabs/grist-core#744]
Make it easier to set-up a Grist installation on your AWS infrastructure with solid options for:
 * Login/authentication.
 * Initial site and team configuration.
 * Database storage and caching.
 * Email delivery.
 * Document snapshots.

**Comment by paulfitz** [comment]
There is a listing now at https://aws.amazon.com/marketplace/pp/prodview-kkchmamumozhq but it is a very limited subset of what we were aiming for. It has a login mechanism and not much else. Basically a foothold/placeholder.

**Comment by dsagal** [comment]
This is now available on AWS Marketplace as "Grist Builder Edition", with everything you need to run a self-hosted Grist instance with minimal setup. Instructions are available at https://support.getgrist.com/install/aws-marketplace/.
