### ISSUE TITLE
Guest access with GRIST_FORWARD_AUTH_HEADER in new version

### ISSUE THREAD

**Issue by Jipok** [gristlabs/grist-core#750]
My env:
```
GRIST_FORWARD_AUTH_HEADER=Remote-User
GRIST_FORWARD_AUTH_LOGOUT_PATH=/jauth-logout
APP_HOME_URL=https://somesite
```
Start with:
`podman run -p 127.0.0.1:8484:8484 --env-file env -v $PWD:/persist -it docker.io/gristlabs/grist`
Version:
`latest 14ed094b4fcd CREATED 13 hours ago`

For quite a long time I used the old version (most likely 1.0.8) along with my authenticator - [jauth](https://github.com/Jipok/Jauth). It worked great. After the update, the user logs in as a guest (after authorization via jauth) and grist ignores the `Remote-User` header. You need to click “Login” in the top right for grist to see the user. This is unexpected for the user and not convenient. Is there any way to return the old behavior? Why does grist ignore a header that explicitly defines a user?

**Comment by paulfitz** [comment]
Hi @Jipok, this may be from changes in https://github.com/gristlabs/grist-core/commit/3210eee24f72dd9e975a40316a175e1de6e18090 (cc @dsagal). You may be able to get the behavior you liked by setting also `GRIST_IGNORE_SESSION=1` so that the headers are respected on all paths. Sorry for the change of behavior.

**Comment by dsagal** [comment]
@paulfitz is correct: `GRIST_IGNORE_SESSION=1` is now needed to keep previous behavior.

The reason for the change is that previous behavior can cause security problems for users who don't control the `Remote-User` header on all  endpoints. With `GRIST_IGNORE_SESSION=1`, it is your responsibility to ensure that all Grist endpoints receive `Remote-User` header from your trusted server, i.e. your server should not pass through this header (if present in the original request) to any Grist endpoint, but should set its own value.
