### ISSUE TITLE
Better handling for removing unavailable workers

### ISSUE THREAD

**Issue by ohemelaar** [gristlabs/grist-core#785]
I recently migrated a test single instance grist deployment to a deployment with separate home and doc workers. After migrating, I had trouble accessing documents because of a 404 error.

The logs showed me that the home worker tried to contact the "old doc worker" which is itself, but because it's not a doc worker anymore it answers with a 404. This can be seen by the values inside redis:
```
redis-master.grist.svc.cluster.local:6379> smembers workers
1) "testDocWorkerId_8484"
2) "dw-2"
3) "dw-0"
4) "dw-1"
redis-master.grist.svc.cluster.local:6379> smembers workers-available
1) "testDocWorkerId_8484"
2) "dw-2"
3) "dw-0"
4) "dw-1"
redis-master.grist.svc.cluster.local:6379> hgetall doc-kgbz1qqUHn8zbVXWGwqZfW
1) "docWorker"
2) "{\"id\":\"testDocWorkerId_8484\",\"publicUrl\":\"http://0.0.0.0:8484/v/unknown/\",\"internalUrl\":\"http://0.0.0.0:8484/v/unknown/\"}"
3) "isActive"
4) "true"
```

I expected grist to evict a doc worker if it doesn't behave well, and indeed there is a function call for this: https://github.com/gristlabs/grist-core/blob/d28c993b86da1c037f83ea16aadbe5b6c5c69809/app/server/lib/DocWorkerUtils.ts#L150

But in my case, it never got to there because of this condition: https://github.com/gristlabs/grist-core/blob/d28c993b86da1c037f83ea16aadbe5b6c5c69809/app/server/lib/DocWorkerUtils.ts#L145

I'm not too familiar with the reasons some errors should cause the worker to be removed and other should raise the error. But from what I understand from the comment above, a condition like this seems to fix that behaviour:
```javascript
            if ((workersAreManaged && e.status === 404) || e.type === 'system') {
                // continue
            } else {
                throw e;
            }
```

I tried this patch for my deployment and indeed it fixed it by finally removing the faulty worker. However, I'll be glad to have your input on whether this would be the right way to handle this.

**Comment by fflorent** [comment]
Flagged as ANCT, I work with Oscar on horizontal scaling

**Comment by fflorent** [comment]
My understanding of the code is that if `GRIST_MANAGED_WORKERS` is set, *only* 404 errors triggers removal of the doc worker. If it is not set, we accept more errors (403, malformed JSON returned, ...).

https://github.com/gristlabs/grist-core/blob/d28c993b86da1c037f83ea16aadbe5b6c5c69809/app/server/lib/DocWorkerUtils.ts#L71-L78

This I would patch the code as below:
```ts
if ((workersAreManaged && e.status !== 404) || e.type !== 'system') {
  throw e;
}
```

**Comment by ohemelaar** [comment]
From what I saw by dumping all the variables I could in logs, when this problem happens `e.type` is `undefined`, so the second part of the condition is true and the error gets thrown

**Comment by fflorent** [comment]
`e.type` is set to `system` when node-fetch gets, for example, a `ECONNREFUSED` error.

That being said, you're right, if I am right, this should be:
```ts
 if (workersAreManaged && e.status !== 404 && e.type !== 'system') {
  throw e;
}
```

Assuming that:
 - if `GRIST_MANAGED_WORKERS` is not set, any error would remove the worker (not sure about whether that's the intention here);
 - if `GRIST_MANAGED_WORKERS` is set, either a 404 or a `ECONN...` error would remove the worker;

**Comment by paulfitz** [comment]
In case it helps, in our SaaS, if an attempt is made to access a URL associated with a worker that is no longer present, we give a fallback response that is a combination of a 404 status and a particular payload that this code is checking for:

![Screenshot from 2023-12-11 15-43-23](https://github.com/gristlabs/grist-core/assets/118367/20eadea1-c710-47dc-8f07-da1abc08d828)

That's this piece of logic here:
https://github.com/gristlabs/grist-core/blob/a3161f64997e7dc7a217b9bceb0bf24771ba4057/app/server/lib/DocWorkerUtils.ts#L129-L132

In a multi-worker production system, I'd say `GRIST_MANAGED_WORKERS` should be set, and arrangement made to give the 404 / special payload response when an attempt is made to access a non-existent worker. The risk of being less fussy is that some temporary problem could snowball into worse problems.

**Comment by ohemelaar** [comment]
Thanks for this insight. Reflecting on all this, I want to emphasize that this issue is only a one-off when migrating from a single container grist deployment to a multi worker deployment. I tracked the behaviour to these lines of code thinking it was a bug, but maybe there's another workaround that can be thought of during the migration. Is there another recommended way to reset all worker assignments? Would you recommend resetting all data inside the redis instance for example?

**Comment by paulfitz** [comment]
@ohemelaar yes, I think wiping the redis storage with a `FLUSHDB` or similar in this case would make sense. We don't test this kind of reconfiguration, and I expect stale worker information could create a muddle. Wiping redis would best be done while Grist is offline. If redis is used for session storage, users may have to log in again.
