### ISSUE TITLE
Unable to create team site

### ISSUE THREAD

**Issue by fflorent** [gristlabs/grist-core#786]
When using self-hosted instances, we are not able to create team sites: when trying to do so, we are redirected to the billing page of getgrist.com

https://github.com/gristlabs/grist-core/assets/371705/9a414b23-89e4-4ccb-9693-373e6b77f4d6

**Comment by paulfitz** [comment]
We'd be very happy to have this fixed. It has been in our backlog for some time now, fighting for priority.

**Comment by fflorent** [comment]
Sure, sorry if my issue made you feel hurried, I should be vigilant about that.

Here is a way to create through the API a team site, with the hope it can help other people:
```bash
$ curl -X POST -H "content-type:application/json" -d '{"name": "foo"}' -H "Authorization: Bearer $BEARER" http://localhost:8484/api/orgs
```

**Comment by paulfitz** [comment]
@Hermitter by any chance is `<org_url>` something like `o-NNN` for you? Is so, maybe when creating a team site, set a `domain` (basically the team site name) along with the human-readable `name`, so in the curl above that would be:

```
... -d '{"name": "foo", "domain": "foo"} ...
```

.... ah I see you found the problem :)

**Comment by vviers** [comment]
As a temporary solution, we're thinking of adding `createWorkspace` to the `GRIST_HIDE_UI_ELEMENTS` environment variable to hide the button, is that cool with you @paulfitz ?

**Comment by paulfitz** [comment]
I think adding something to `GRIST_HIDE_UI_ELEMENTS` is ok @vviers, if the existing `multiSite` is too broad.

Careful about the name. For Grist in English, `workspace` maps to what is called `dossier` in the French translation - groups of documents, but not the top level entity called `team site` or `espace d'équipe`. `createSite` would be an ok name.

**Comment by CamilleLegeron** [comment]
Proposition of a simple popup by @kbizien

![Image](https://github.com/gristlabs/grist-core/assets/19594405/7e92f0aa-6011-4b38-927e-06e13d3253f5)

**Comment by CamilleLegeron** [comment]
Hi,
What it would be the best technique for having a "default version" if not using SAAS or pro version ? 
- Maybe having a code that open a popup like as above, and activate this code with a variable `FREE_CREATING_TEAM_SITE`. This variable will be set to `true` in our instance and `false` to the SAAS version
- Other proposal ?  
Wdyt @paulfitz ?

**Comment by CamilleLegeron** [comment]
In the draft PR just above I made an unfinished proposal : have a simple modal that call the POST call API that @fflorent mentioned. Maybe add a env variable that we could use in `stubs/app/client/ui/ProductUpgrades.ts` to import the right files if self hosted or is it not
