### ISSUE TITLE
Deadlock with webhooks?

### ISSUE THREAD

**Issue by fflorent** [gristlabs/grist-core#799]
Some of our users have their document *stuck* (i.e. the users wait forever until someone `force-reload`s it) after working a bit on it. 

I could reproduce the issue locally, and I could nearly reproduce the issue: the document is stuck immediately at the load. It's 100% satisfying (I would expect the production to behave the same), but it appears that the webhook are guilty here, even when all of them are disabled.

My understanding of the issue is the following (do not hesitate to challenge or correct me):
1. At the document initialization, the webhooks are triggered (we trigger a [calculate formula](https://github.com/gristlabs/grist-core/blob/main/app/server/lib/ActiveDoc.ts#L2344) which [triggers the webhooks](https://github.com/gristlabs/grist-core/blob/65757854eae163720a585aecb2e1ee0074f237c4/app/server/lib/Sharing.ts#L339)) and waits until that's done;
2. In order to trigger the webhooks, [the documents are loaded](https://github.com/gristlabs/grist-core/blob/65757854eae163720a585aecb2e1ee0074f237c4/app/server/lib/Triggers.ts#L212), waiting for the formulas (the meaning of the boolean flag for the `fetchQuery` method);
3. Waiting for the formulas involves waiting for the document initialization(cf [`wantsFull`](https://github.com/gristlabs/grist-core/blob/main/app/server/lib/ActiveDoc.ts#L999-L1000) and the call to [`waitForInitialization()`](https://github.com/gristlabs/grist-core/blob/65757854eae163720a585aecb2e1ee0074f237c4/app/server/lib/ActiveDoc.ts#L1008C18-L1008C39)) ⇒ deadlock;

I cannot share yet a document to reproduce the issue. I wonder if just creating a simple table with formulas in it and a webhook wouldn't be enough for that. If you request it, I can attempt to create one.

PS: Also maybe worth to mention: our production use GVisor, but the python engine is Pyodide when  running locally. I wonder if that's not the explanation of the slight difference between what I got and what happens to our users. Still not 100% satisfied by my analysis.

**Comment by alexmojaki** [comment]
This makes sense. I think to reproduce (and to write an automated test) you'd just need a formula using `NOW()` or `UUID()` or something like that so that the value changes when the document is loaded.

I think there should just be an exception that prevents sending webhooks for the calculate action. That should easily solve this issue and might be for the best anyway. Any setup which relies on sending webhooks at that point sounds broken, because it implies that there are notifications which should be sent out just because time has passed, and they won't work if no one opens the document.

**Comment by fflorent** [comment]
You're right! I could reproduce the issue easily using these steps:
 - import [Hello.grist](https://github.com/gristlabs/grist-core/blob/main/test/fixtures/docs/Hello.grist);
 - Configure the webhook to some endpoint with `add, update` events;
 - Add a new column with `=NOW()` formula (it does not work with the `=UUID()` formula);
 - Force-reload the document (using the `/api/docs/:docId/force-reload` endpoint);
 - Try to add a new line or to update a cell ⇒ :boom: the bug with the `Still working` message happens;

The Hello.grist's Table1 table has a E column with a formula, but it's not enough to trigger the bug, just as you stated here:
> you'd just need a formula using NOW() or UUID() or something like that so that the value changes when the document is loaded.

Also I could manage to fix the issue as you suggested, by ignoring the Calculate action.

**Comment by alexmojaki** [comment]
> (it does not work with the `=UUID()` formula)

Does the UUID not change when you reload the document? Is this with a regular formula column, not a trigger formula?
