### ISSUE TITLE
OIDCConfig: email not verified for xxxxxxx

### ISSUE THREAD

**Issue by Tristan0430** [gristlabs/grist-core#808]
How to solve this error: `OIDCConfig: email not verified for`
I want to integrate OIDC application such as Casdoor, but this error holds me off and I don't have a clue……
What should I do?

**Comment by fflorent** [comment]
OIDCConfig by default rejects with the message you mention accounts which don't have their email verified or if the identity provider does not tell whether that's the case.


You might set the `GRIST_OIDC_SP_IGNORE_EMAIL_VERIFIED` env variable to `true`. But I would rather recommend to configure Casdoor so it provides the `emailVerified` claim for production, and it looks like this can be done: https://github.com/casbin/casdoor/blob/v1.485.0/object/user.go#L200-L212

**Comment by fflorent** [comment]
Without any further feedback, I close this issue
