### ISSUE TITLE
Migration from v1.1.7 to v1.1.9 causes snapshots page not found`--> URL layout changed?

### ISSUE THREAD

**Issue by Vinschni** [gristlabs/grist-core#810]
Hello together,
i migrated from v1.1.7 to v1.1.9 and this causes opening any snapshot to result in a page not found
 ![image](https://github.com/gristlabs/grist-core/assets/340731/4fb2f334-f59a-4f8c-9ea2-5288a27530d3)

I noticed the URLs when clicking "Open Snapshot" look different in layout comparing v1.1.7 and v1.1.9
![image](https://github.com/gristlabs/grist-core/assets/340731/5b57b33e-7f71-477a-90a2-f83c47c45dd2)

For v1.1.7:
https://ourdomain/o/ourteamname/doc/ewWNuxN8dr5p~v=188c8d1d-aa78-4bbf-a29a-3b8649f857ef

and for v1.1.9:
https://ourdomain/mSqyTDqoxDsp5ERR7F2GrX~v%3De675c249-0488-4f73-8332-5066f90d4799/Untitled-document

If i do not click "Open Snapshot" in v1.1.9 but call the link generated by "Open Snapshot" button from v1.1.7 it works with the new server instance running.

Is the generation of the link by those Snapshot buttons broken in v1.1.9?

**Comment by fflorent** [comment]
Hello @Vinschni!

It works fine in our Grist instance.

Based on the links you provide, I guess the `GRIST_ORG_IN_PATH` env variable should be set to `true`. Is it the case? 
Or do you have changed the value of some env variable by chance?

**Comment by Vinschni** [comment]
Hi @fflorent,
env variables were not touched, just docker container was replaced.

I added `GRIST_ORG_IN_PATH` with `true` as parameter but it did not change.

<details>
  <summary>Log output of environment variables on startup of container</summary>

 ```javascript
LOGOUT_REDIRECT=https://ourdomain/signed-out
GRIST_DATA_DIR=/persist/docs
TEAM=ourteamname
APP_HOST=ourdomain
GRIST_ORG_IN_PATH=true
GVISOR_FLAGS=-unprivileged -ignore-cgroups
NODE_VERSION=14.21.3
WHOAMI_PORT=17102
URL=https://ourdomain
YARN_VERSION=1.22.19
HOSTNAME=my_hostname
HOME=/root
APP_HOME_URL=https://ourdomain
GRIST_FORCE_LOGIN=true
GRIST_DOCS_MINIO_PORT=9000
GRIST_TELEMETRY_URL=dummy
EXT_PORT=9999
container=podman
GRIST_HIDE_UI_ELEMENTS=helpCenter,billing,templates,multiSite,multiAccounts,sendToDrive
GRIST_DOCS_MINIO_BUCKET=grist-docs
GRIST_SANDBOX_FLAVOR=unsandboxed
NODE_TLS_REJECT_UNAUTHORIZED=0
GRIST_FORWARD_AUTH_LOGOUT_PATH=_oauth/logout
GRIST_DOCS_MINIO_ACCESS_KEY=grist
GRIST_WIDGET_LIST_URL=https://ourdomain:8443/widgets/manifest.json
DEX_PORT=9999
GRIST_SESSION_COOKIE=grist_core
TERM=xterm
DEFAULT_PROVIDER=oidc
GRIST_DOCS_MINIO_ENDPOINT=minio
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
EMAIL=my_email
GRIST_DEFAULT_EMAIL=my_email
GRIST_SINGLE_ORG=ourteamname
PROVIDERS_OIDC_CLIENT_ID=XXXXXXXXXXXXXXX
GRIST_DOCS_MINIO_USE_SSL=0
PROVIDERS_OIDC_CLIENT_SECRET=XXXXXXXXXXXXXXX
GRIST_TELEMETRY_LEVEL=off
SECRET=XXXXXXXXXXXXXXX
TLS=true
GRIST_SERVE_SAME_ORIGIN=true
USE_HTTPS=true
TYPEORM_DATABASE=/persist/home.sqlite3
GRIST_SESSION_SECRET=XXXXXXXXXXXXXXX
GRIST_HOST=0.0.0.0
PWD=/grist
TFA_PORT=17101
HTTPS=manual
PASSWORD=XXXXXXXXXXXXXXX
PROVIDERS_OIDC_ISSUER_URL=https://ourdomain/dex
GRIST_DOCS_MINIO_SECRET_KEY=XXXXXXXXXXXXXXX
PYTHON_VERSION_ON_CREATION=3
REDIS_URL=redis://redis
GRIST_FORWARD_AUTH_HEADER=X-Forwarded-User
GRIST_INST_DIR=/persist
GRIST_SINGLE_PORT=true
GRIST_PORT=17100
  ```
</details>

Could you post an anonymized version of your for comparison or see another way for me to dig into that?

How safe is it to downgrade on grist versions with same minio bucket? Is there a strategy to keep that data scheme stable?

**Comment by tegs** [comment]
Hi @Vinschni, in my case snapshot leads to "page not found" error on version 1.1.10. Snapshots seem to work fine in versions 1.1.7, 1.1.8, 1.1.9.

The difference in the path generated going from 1.1.9 to 1.1.10 seems to be the missing "doc/" part, whether org is in path or not.

So, using your example:
`https://ourdomain/mSqyTDqoxDsp5ERR7F2GrX~v%3De675c249-0488-4f73-8332-5066f90d4799/Untitled-document`
insert `doc/`
`https://ourdomain/doc/mSqyTDqoxDsp5ERR7F2GrX~v%3De675c249-0488-4f73-8332-5066f90d4799/Untitled-document`
should do the trick.

Manually inserting "doc/" in the path allows me to access the snapshot. Is this misconfiguration on my part or a bug introduced in 1.1.10 I am not sure.

If I am not mistaken, as long as new features introduced in newer versions are not used in the particular grist doc, then going down versions should work fine for that grist doc.

**Comment by paulfitz** [comment]
Thanks for this ^ @tegs. Smells like a bug.

**Comment by fflorent** [comment]
I think I have found the issue and understood why we don't encounter it, thanks to bisection.

In this commit (bcb9740d89b0a59911a58eadea822b3ee7bef37d), hyphens are disallowed to load documents. In our case, we don't encounter the bug as we store documents on scaleway and versions are just integers. In case of MinIO, versions are UUIDs with hyphens, hence the problem when we try to load this URL: `doc/someDocId~v=some-uuid-whatever`

**Comment by fflorent** [comment]
I have opened this PR, though I am far of being convinced of my approach: https://github.com/gristlabs/grist-core/pull/860

If you have any advice to share, it would be highly welcome. Otherwise I'll try to improve my patch later.

I have also proposed an alternative solution, which could be relevant depending on some questions I raised with it.
