### ISSUE TITLE
Conditionnal Choice Liste

### ISSUE THREAD

**Issue by nicolas-imbert** [gristlabs/grist-core#815]
Hi, 

This feature is a feedback / wish from several users I talked to. 

The idea is to have Columns that are interdependant for Choice list. 
Meaning, a Choice list with values that depends on another value from another column. 

Let me give an example :  
First column is "Month" and Second one is "Week"
What the feature would do is : based on the Month you choose on the first colonne, it will show you on the list only the Weeks (in column Week) that belongs to the selected Month, and not the whole 52 weeks in the list. 

Here are some visuals : 
What we have atm 
![image](https://github.com/gristlabs/grist-core/assets/155563823/f810f655-0a7e-42d1-b185-0c256c2695e1)

What the feature would do with the same data :
![image](https://github.com/gristlabs/grist-core/assets/155563823/807120c2-3580-4526-a00d-d30f1bafde9e)

And this applies to many other examples, like first column you choose the "Category" and second columns you can only choose / see the values that depends on that Category.  

I hope its clear enough !

Nicolas

**Comment by vviers** [comment]
(Related to #249)

**Comment by vviers** [comment]
Solved in 1.1.14
