### ISSUE TITLE
Add a publiccode.yml file

### ISSUE THREAD

**Issue by fflorent** [gristlabs/grist-core#822]
Quoting the [website of this standard](https://yml.publiccode.tools/)

> publiccode.yml is a metadata standard for repositories containing software developed or acquired by the Public Administration, aimed at making them easily discoverable and thus reusable by other entities.

Some crawlers exist and we can take advantage of it to promote Grist to administrations (especially in Europe).

**Comment by fflorent** [comment]
My progress is on this branch: https://github.com/incubateur-territoires/grist-core/tree/public-code-yml

The diff:
https://github.com/gristlabs/grist-core/compare/main...incubateur-territoires:grist-core:public-code-yml

**Comment by vviers** [comment]
LGTM @fflorent ! Could you open the PR on this repo so I can review and suggest a couple of edits ? :)
