### ISSUE TITLE
how to ... postgres

### ISSUE THREAD

**Issue by j2l** [gristlabs/grist-core#87]
Hello,
I noticed that postgres is an option, which is fantastic!
For the container, I added the typeorms for postgres and got an error at the `npm install pg --save` step about missing python for gyp.
Do you have a dockerfile for this option?

**Comment by paulfitz** [comment]
We don't, but could talk you through it. I'd just like to clarify, postgres is an option for the database containing metadata about documents, workspaces, users, etc. Individual documents themselves are currently always stored as sqlite. If you're still interested in the postgres setup, let me know and I'll write it up.

**Comment by b42thomas** [comment]
Hi,

I would also like to know how to setup grist with postgres.  @paulfitz you said its for the metadatabase, so are there two databases that run then? sorry if thats a dumb question lol

**Comment by paulfitz** [comment]
@b42thomas each individual document is itself a database (stored in individual sqlite files). The organization of documents into collections (workspaces and sites) is stored in a database called the "home" database (which can be sqlite or postgres). There is also a store for session information, which can be in a (trivial) sqlite database, or in redis.

To use Grist with Postgres:

 * Follow the instructions for building Grist in the top-level README.
 * Add the node package for postgres: `yarn add pg`
 * Create an empty database in your postgres instance (hopefully you have one, if not there are a lot of tutorials out there for this part).
 * set the following environment variables pointing to that empty database:

Variable | Purpose
-------- | -------
TYPEORM_TYPE     | set to 'postgres'
TYPEORM_DATABASE | database name
TYPEORM_HOST     | host for db
TYPEORM_PASSWORD | password to use
TYPEORM_PORT     | port number for db if not the default for that db type
TYPEORM_USERNAME | username to connect as
TYPEORM_LOGGING  | set to 'true' to see all sql queries

 * run `yarn start` as usual.
 * Grist should come up as always, and you should see over a dozen tables appear in the database.

**Comment by j2l** [comment]
Thank you @paulfitz for these details.
As explained the Dockerfile doesn't include python, so the `add pg` step fails.

Never mind, I'm looking for data to be using postgres.

Do you have plans to support data and metadata on postgres?

**Comment by j2l** [comment]
@paulfitz I agree that sqlite is great to take away and it makes sense that grist focuses on this.

Personally, I have sqilte files and various spreadsheets that have many to many relationships (so not really spreadsheets) and I need them to become tables in a database that can scale and be shared as single point of truth, but the data will continue to evolve greatly.

So my use case is simple: Getting a grist-like spreadsheet for postgres (not speaking about functions here, simply a way to fill, manipulate data as in a spreadsheet), because the one-record only (card or line by line) approach of databases is sometimes not useful at all. Especially when you select a column or multiple cells to be changed at once.
Hope my explanation makes sense :)

I think Airtable nailed the point here, but your data is barely yours anymore since you can't GET and aggregate linked records or even export them as is (csv are flatten, no more links).

If you know of other solutions to manage postgres data like a spreadsheet, please let me know.

I think we can close this one for now.
Please, if you know changes of `app/server/lib/DocStorage.t` for postgres, please let me know here :)

**Comment by asitemade4u** [comment]
May I bring my 2 cents to the discussion?

We should IMO distinguish between:

1. the database which is used as a native backend to Grist
2. the ability for Grist to serve any data hosted on any major database platform (eg Postgres or MYSql)

- There are LOTS of self-hosted tools that allow #2 but they do it quite wrong, at least until now: they add tables, they are barely relational. I have chosen to stick with a fairly old tool to publish the database we host, PHP Generator for Postgresql, which is by far the most comprehensive tool I have found. IMO, it would be an error for Grist to get into that competition: Grist is more of a **method** to display relational data than a mere interface builder. Its simplicity and streamlined interface are its main asset.
- As per #1 I guess it would not be too much of a hassle for Grist's developers. However @paulfitz is correct when writing that SQLite is a great tool -- which has saved my work while I was testing Grist in docker: I could easily back up my data then re-inject them into Grist, on another platform (self hosted docker, Grist's  website, etc.)

**Comment by skamensky** [comment]
@paulfitz 

I'd have loved to use grist for our company! 

Use case to add support for postgres:

We already have a lot of legacy procedures and triggers to automate data writted in plpgsql (postgres' procedural language) and I've been on the hunt for a stellar frontend. We'd primarily be using the data entry features for its combined ease-of-use and respect of data types, and less for the formula and computations.

Ideally we'd do some sort of migration to fit the data to however grist wants to see it and keep out triggers/procedures.

I'm not sure it's reasonable for us to migrate to sqlite.

**Comment by paulfitz** [comment]
@skamensky your use-case totally makes sense. I'm sure someone will generalize the backend eventually. I've recently been using other flavors of SQLite support with Grist (better-sqlite3 and sql.js vs the existing node-sqlite3 code) and those changes were fairly straightforward. Postgres changes would be deeper, but not a quagmire I think. Still, for now it'll have to wait for the stars to align, when someone with both the need, the time, and the capacity comes along...

Thanks for chiming in, appreciate your perspective.

**Comment by reidlai** [comment]
> @b42thomas each individual document is itself a database (stored in individual sqlite files). The organization of documents into collections (workspaces and sites) is stored in a database called the "home" database (which can be sqlite or postgres). There is also a store for session information, which can be in a (trivial) sqlite database, or in redis.
> 
> To use Grist with Postgres:
> 
> * Follow the instructions for building Grist in the top-level README.
> * Add the node package for postgres: `yarn add pg`
> * Create an empty database in your postgres instance (hopefully you have one, if not there are a lot of tutorials out there for this part).
> * set the following environment variables pointing to that empty database:
> 
> Variable	Purpose
> TYPEORM_TYPE	set to 'postgres'
> TYPEORM_DATABASE	database name
> TYPEORM_HOST	host for db
> TYPEORM_PASSWORD	password to use
> TYPEORM_PORT	port number for db if not the default for that db type
> TYPEORM_USERNAME	username to connect as
> TYPEORM_LOGGING	set to 'true' to see all sql queries
> * run `yarn start` as usual.
> * Grist should come up as always, and you should see over a dozen tables appear in the database.

Can I use the same way to use mysql?

**Comment by paulfitz** [comment]
@reidlai mysql will likely need some code changes, for example in https://github.com/gristlabs/grist-core/blob/9ff8893e416810075b947407cbe38c1dbafed39d/app/gen-server/sqlUtils.ts#L117-L126
