### ISSUE TITLE
Wrong error message when trying to delete a table that is still linked with references

### ISSUE THREAD

**Issue by nicolas-imbert** [gristlabs/grist-core#873]
I wanted to delete a table that (I did not know at that time) was still linked through reference to another table.
I could not delete the table and the error message I got was the following : 
![image](https://github.com/gristlabs/grist-core/assets/155563823/272d1f5e-f167-4c72-acea-6a4f76a05f55)

If we could have a more understandable message that leads us to references, that would be nice !

Thanks,
Nicolas

**Comment by fflorent** [comment]
@nicolas-imbert I attempted to reproduce the issue with no success, do you?

**Comment by nicolas-imbert** [comment]
I just tried to reproduce as well. 
No more error messages and table could be deleted without any trouble.
The reference column using the deleted table has changed now into a text type. 

Seems fine to me!
We can close the issue I guess.
