### ISSUE TITLE
How to download a template to use?

### ISSUE THREAD

**Issue by tifDev** [gristlabs/grist-core#885]
Hello,

I'm new to grist and I'm giving a try because it seems a great app! 
I want to use a template to make more familiar with the code part but I'm not being able to make it.
Can you help me on how to [download this template](https://templates.getgrist.com/9mWWYLe5PCZK/Personal-Budget/p/5)?

Thank you!

**Comment by dsagal** [comment]
Hi @tifDev ! There is a "Download" option in the Share menu (the one next to the "Save Copy" button):

<img width="414" alt="Screenshot 2024-03-06 at 9 28 44 PM" src="https://github.com/gristlabs/grist-core/assets/1091143/00b5c8f6-4bcb-4516-9416-c73ab3d1e933">

**Comment by tifDev** [comment]
Ok I had to login... I was missing this part.
Thanks!
