### ISSUE TITLE
Unable to connect to the docker-based container 

### ISSUE THREAD

**Issue by asitemade4u** [gristlabs/grist-core#89]
1. I deploy the docker container on our server as per the documentation
2. I can connect to the address/port but Grist issues an error

![Screenshot-20211119-172525](https://user-images.githubusercontent.com/11460106/142699771-ca82c1a2-7bc4-4a96-a0b3-f85200a1cab1.png)

3. I then tried to sign in using the upper right button but I arrived on a blank page.

Please help,
Best,
Stephen

**Comment by dsagal** [comment]
Hi Steven,

The instructions in the README currently only work for a local installation, when you access Grist from the same machine as the one it runs on, using localhost URLs. It's possible to run it as a server, to access from other machines, but various tweaks are needed to the environment variables. This [thread goes into the details](https://github.com/gristlabs/grist-core/issues/70), which should be sufficient to get it working.

**Comment by asitemade4u** [comment]
Thanks for the procedure, which worked.
