### ISSUE TITLE
Form bug - Can't see the "Publish" button even when being an Owner

### ISSUE THREAD

**Issue by RaywanS** [gristlabs/grist-core#905]
Hi team,

I'm facing a super strange bug here with Grist Forms.

User Benoit Mangenot is the owner of his document. While creating a form on it, he can't see the Publish button : 
![image](https://github.com/gristlabs/grist-core/assets/131388510/f1062d44-9722-4945-9b8f-071062d9cbdd)

Two weird things here : 
1. when i connect to the form, I do see the publish button (i am Owner as well, as an ANCT member).

<img width="1215" alt="image" src="https://github.com/gristlabs/grist-core/assets/131388510/71aca206-d05a-42b5-8ccf-7db89acb5646">

2. when i look in "seen as ... Benoit Mangenot", i do see the button, but he can't.

![image](https://github.com/gristlabs/grist-core/assets/131388510/5d9525e8-c966-41ab-a3d5-8b872871a0f0)

It seems to happen for all forms - owners who are not ANCT members can't see their publish boutton.

Any idea / help here ? Poke @berhalak :)

**Comment by RaywanS** [comment]
Hi @paulfitz , thank you for your quick answer. Glad to see it has been spotted, i'll check with my tech team to see which version we are currently working on - or if we wait for the formal release.

Thanks!

**Comment by vviers** [comment]
Closing this issue as it has been fixed !
