### ISSUE TITLE
gvisor check fails on containers under RHEL host

### ISSUE THREAD

**Issue by gabriel-v** [gristlabs/grist-core#914]
We've set up grist using the `gvisor` sandbox and it works great in our debian/ubuntu testing servers. But when installing container to a RHEL host with default settings and permissions, we get the `gvisor check failed` error and no additional info.

We've looked at [XSAVE processor flag](https://community.getgrist.com/t/how-to-get-sandbox-working-in-grist-core/2952) (we have XSAVE), and also [limit amount of processes](https://groups.google.com/g/gvisor-users/c/1NLhf1R8HVk/m/f3dhGoSABAAJ) (for us it's 20_000)

Any suggestions to further continue debugging this non-standard gvisor+docker setup? Maybe some explicit docker `cap` or `--priviledged` ?

Thanks!

**Comment by paulfitz** [comment]
Hmm, do you know if you have the `SYS_PTRACE` capability?

One option for debugging is to run /bin/bash on the container, and then try running `runsc` in various ways, outside of Grist. `runsc` can be set up to do extensive logging.

For example, for me this command succeeds and shows a directory listing:
```
paulfitz@entwash:~/cvs/grist-core$ docker run -it gristlabs/grist /bin/bash
root@203def292848:/grist# runsc --network none -unprivileged -ignore-cgroups do ls
...
```
If it fails for you, then maybe you could enable logging on it (I forget the details but runsc documentation should be clear) and see what is up?

**Comment by gabriel-v** [comment]
> runsc can be set up to do extensive logging

Found [docs](https://gvisor.dev/docs/user_guide/debugging/) - works like this

        runsc --network none -unprivileged -ignore-cgroups --debug --debug-log=/dev/stderr do ls


which spams a stack trace and also says

        panic: unable to attach: operation not permitted

which [means ptrace](https://stackoverflow.com/questions/19215177/how-to-solve-ptrace-operation-not-permitted-when-trying-to-attach-gdb-to-a-pro/46676868#46676868) - which you also said.


Adding ptrace cap fixes the issue:

        docker run -it --cap-add=SYS_PTRACE gristlabs/grist /bin/bash


Maybe add `SYS_PTRACE` to the [docs page faq section](https://support.getgrist.com/self-managed/#how-do-i-sandbox-documents) as well as the XSAVE processor flag?

Thanks!

**Comment by paulfitz** [comment]
@gabriel-v there was a documentation update based in part on your suggestion, thanks.
