### ISSUE TITLE
Updating to the last (home built) self hosted Grist

### ISSUE THREAD

**Issue by asitemade4u** [gristlabs/grist-core#92]
I have built grist-core using the `dockerfile` in the repo. It went well.
But then I tried to use the new image with my pre-existing documents, on a local docker install.

I encountered the following issues:
1. no document was displayed on the home page
2. so I **Signed in** using the button at the top right handside
3. then the documents appearead in the Home Page
4. but I cannot access any of them: initialization error
5. So I tried to **import** them from their existing files > got an Initialization error
6. When I tried to **create a new document**, I also got an initialization error

I am happy I had backups. I reverted to the current version on DockerHub and will wait for you to issue a new one.

**Comment by paulfitz** [comment]
Hi @asitemade4u, can you try rerunning Grist with `--env DEBUG=1` and seeing if there are any useful error messages logged? Are you using the same configuration as in https://github.com/gristlabs/grist-core/issues/90?

**Comment by asitemade4u** [comment]
Hi @paulfitz and thanks for the quick response.

## New image and container
So, I have:

1. built the image from the latest source, called it `grist-nxt`
2. duplicated the existing Grist documents to another directory to be sure I do not ruin them
3. c reated a new `docker-compose.yml` file, with the new image, another container name, anther connection port :+1: 

``` bash
version: "3"

services:
  gristnext:
    image: grist-nxt
    container_name: gstnxt
    restart: unless-stopped
    environment:
      - DEBUG=1
    ports:
      - "8585:8484"
    volumes:
      - /home/stsinc/dkr/gst-nxt/dta:/persist
````

## Test results
1. I am able to connect to the container locally
2. the home page shows all documents and kept their pin status
3. when I click on a document it says access is denied
4. I check my account profile in the upper right side and it is me indeed
5. I log out and sign in again and my documents are accessible > YAY !!!!

> So, **all good with the preexisting documents**

Now I try to **create a new document**.
I get a **Page not found : Please check the URL and try again.** error.

**Comment by asitemade4u** [comment]
## Tests with preexisting documents
### Column Type Conversions
- I get a `#TypeError` when I try to transform a **Reference** column into a **Reference List** column. Unfortunately, I cannot revert to the previous **Reference** type and the column seems unreadable now. 
- However if I **Clear the values** in the converted column and change **Show Column** value, then the columns becomes reusable again, but has been wiped out in the meantime -- not ideal
- I create a **new column**, then try to convert it into a **data** column. I get an error: `Sandbox KeyError: recalcDeps`
- I create a **new column** , then try to set it as a **Choice List** column: I get an error `Attribute Error: Module has no attribute` error nbut eventually the process gets through and the column is created and usable

 
--

**Comment by paulfitz** [comment]
I think there may be some port confusion going on, especially if you have two versions of Grist running side by side. Currently, to change Grist to a different port (like 8585), you'll need to set a few environment variables:
  * APP_HOME_URL=http://localhost:8585
  * APP_DOC_URL=http://localhost:8585
  * PORT=8585
For a self-hosted single-instance install this is kind of silly, but that's how it is currently. I suspect your browser is viewing non-doc pages for one of your Grist copies, and doc pages from another of your Grist copies.

**Comment by asitemade4u** [comment]
I tried and rewrote the docker-compose file as per your instructions:
```ỳaml
version: "3"

services:
  gristnext:
    image: grist-nxt
    container_name: gstnxt
    restart: unless-stopped
    environment:
      - DEBUG=1
      - APP_HOME_URL=http://localhost:8585
      - APP_DOC_URL=http://localhost:8585
      - PORT=8585
    ports:
      - "8585:8484"
    volumes:
      - /home/stsinc/dkr/gst-nxt/dta:/persist
```
 I cannot connect to Grist from any of my browsers.
 I also trield replacing `localhost`by the actauil IP address of my machine and it did the same.

Here is the log:
```
yarn run v1.22.15
$ NODE_PATH=_build:_build/stubs node _build/stubs/app/server/server.js
Welcome to Grist.
2021-11-23 19:56:14.922 - info: == Grist version is 0.1.1 (commit unknown)
2021-11-23 19:56:14.926 - info: Loading empty config because /config.json missing
2021-11-23 19:56:14.952 - warn: did not find an appropriately named example workspace in deployment
2021-11-23 19:56:14.954 - info: No plugins directory: ENOENT: no such file or directory, scandir '/.grist/plugins'
2021-11-23 19:56:14.954 - info: No plugins directory: ENOENT: no such file or directory, scandir '/plugins'
2021-11-23 19:56:14.954 - info: Found 0 valid plugins on the system
2021-11-23 19:56:14.959 - info: Server timeouts: keepAliveTimeout 305000 headersTimeout 306000
2021-11-23 19:56:14.963 - info: server(home,docs,static) available at 0.0.0.0:8585
2021-11-23 19:56:14.984 - info: activity docCount=29, orgCount=0, orgInGoodStandingCount=0, userCount=5, userWithLoginCount=5
2021-11-23 19:56:14.987 - warn: Failed to create GoogleAuth endpoint: GOOGLE_CLIENT_SECRET is not defined
2021-11-23 19:56:14.991 - info: == appRoot: /
2021-11-23 19:56:14.991 - info: == docsRoot: /persist/docs
2021-11-23 19:56:14.991 - info: == defaultBaseDomain: .168.1.5
2021-11-23 19:56:14.991 - info: == pluginUrl: undefined
2021-11-23 19:56:14.991 - info: == instanceRoot: /
2021-11-23 19:56:14.991 - info: == tag: unknown
2021-11-23 19:56:14.991 - info: == database: sqlite:///persist/home.sqlite3
2021-11-23 19:56:14.991 - info: == userRoot: /.grist
2021-11-23 19:56:14.991 - info: == loginMiddlewareComment: no-logins
2021-11-23 19:56:14.992 - info: == s3: disabled
2021-11-23 19:56:14.992 - info: == docWorkerId: testDocWorkerId_8585
```

**Comment by asitemade4u** [comment]
As noted before, the worrying line here is:
```
2021-11-23 19:56:14.991 - info: == defaultBaseDomain: .168.1.5
```

**Comment by paulfitz** [comment]
You'll need to update `8585:8484` to be `8585:8585` since Grist will now be running on port 8585 inside the container.

Yes, the "base domain" logic doesn't make sense for a single-instance install, and is confused by ip addresses, but it also shouldn't do harm (if `APP_HOME_URL` and `APP_DOC_URL` are set).

**Comment by asitemade4u** [comment]
Yes of course.
1. I could enter the home page 
2. it asked me to authenticate
3. but when I select Sign In I get this error:
4. 
![Screenshot-20211123-150539](https://user-images.githubusercontent.com/11460106/143096134-63e8239f-c04b-4ca4-b176-ae37049a12a2.png)

**Comment by asitemade4u** [comment]
And YES, you were right about the two Grist stacks competing for the same version: I can't open my documents on the older version (but I have backups).

**Comment by asitemade4u** [comment]
Or more precisely: the documenTI had been doing my tests on in grist-next is now unreadable on grist-classic.
