### ISSUE TITLE
Allow adding a "Terms of use" link in the home page

### ISSUE THREAD

**Issue by fflorent** [gristlabs/grist-core#925]
For the ANCT self-hosted instance, we need to add a link to our "Terms of use" agreements.

We'd suggest for that to add an environment variable that would contain a link, and when defined, would just add a button `Term of use` near to the `Help Center` one and redirect to the page of the link.

**Comment by fflorent** [comment]
My proposal would look like this, though I have not much idea for the icon (I used `--icon-Memo` FWIW):

![mockup of the proposal](https://github.com/gristlabs/grist-core/assets/371705/3e9fa946-4106-4102-9e3b-993560fd6e70)

**Comment by CamilleLegeron** [comment]
@anaisconce tag you here as you wanted to think about this issue

**Comment by fflorent** [comment]
@hexaltation with your PR merged, shouldn't we consider this enhancement as being implemented, and thus close this issue?
