### ISSUE TITLE
Add support for 2-factor authentication (2FA) for Grist accounts

### ISSUE THREAD

**Issue by dsagal** [gristlabs/grist-core#93]
Multi-factor authentication adds a layer of security that's important for many businesses, and generally recommended. It is currently possibly to use it when signing in to Grist using Google Sign-In (if enabled on Google side), but we should support it for people who sign in using email and password too.

**Comment by georgegevoian** [comment]
Grist now supports enabling two-factor authentication for added account security.

The [account page](https://docs.getgrist.com/account) has a new section for managing your 2FA settings.
