### ISSUE TITLE
Clarification for `GRIST_DATA_DIR` needed. Overrides `/persist/docs`

### ISSUE THREAD

**Issue by cgalo5758** [gristlabs/grist-core#931]
After losing all of our grist docs in our self-hosted instance, we found out that setting `GRIST_DATA_DIR` overrides what may be the default data directory `/persist`. The `GRIST_DATA_DIR` variable name may be self-explanatory, but I guess what tripped us up was its description:

> directory in which to store document **caches**.

Thinking this was for caching, we just set it to `/var/grist/` and deployed, while only persisting `/persist`. I think this doesn't store caches, it stores the grist files themselves... correct?

https://support.getgrist.com/self-managed/ should perhaps reference GRIST_DATA_DIR instead of `/persist` or the relationship between both should be mentioned.

**Comment by paulfitz** [comment]
@cgalo5758 I'm very sorry you lost your docs!

I can see how the cache language is confusing. If you have external document snapshots set up, then the definitive version of the document is what is stored in S3 (or an S3-compatible store), and we think of the document on the file system as a cache. But without snapshots it is the definitive version, and the language is confusing.

I would welcome an improvement to that language that works for you at https://github.com/gristlabs/grist-help

**Comment by jordigh** [comment]
@cgalo5758 I think `GRIST_DATA_DIR` is a bit of an advanced setting that should mostly be left alone. I opted to document it better in #945 but I don't think it even deserves mention in [the self-managed docs](https://support.getgrist.com/self-managed/).

Frankly, I'm of half a mind to just completely deprecate this variable. I can't think of a good situation in which you would want to store the Grist document files in a completely different location than general Grist persistent storage.

**Comment by cgalo5758** [comment]
@jordigh Agreed! No need to add it to the self-hosting docs.

I gotta say, it would be nice if default values were added to the environment variables table. This may have prevented me from doing this mistake 😅.

> Frankly, I'm of half a mind to just completely deprecate this variable. I can't think of a good situation in which you would want to store the Grist document files in a completely different location than general Grist persistent storage.

Yeah. I can't think of anything either, but I believe it is common practice with self-hosted software. Not sure if somebody in the future would open up an issue or a PR to add the data dir option again if you were to remove it 🤷
