### ISSUE TITLE
OIDCConfig: email not verified for

### ISSUE THREAD

**Issue by gautierrog** [gristlabs/grist-core#943]
Hello,

I configured grist to use OIDC, however, I have alors of user which email is not verified and I would want them to be able to login.
Here is the error log:

```
error: OIDC callback failed: Error: OIDCConfig: email not verified for xxxxxxxxxx
nocode_grist.1.ynax8db7b8f4@xxxxxxxxx    |     at OIDCConfig.handleCallback (/grist/_build/app/server/lib/OIDCConfig.js:134:23)
nocode_grist.1.ynax8db7b8f4@xxxxxxxxx    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Is there a way to allow user to login ?

**Comment by fflorent** [comment]
Hi @gautierrog,

`GRIST_OIDC_SP_IGNORE_EMAIL_VERIFIED=1` is meant for that, I forgot to document that in this page: https://support.getgrist.com/install/oidc/

Will do that soon! In the meantime (I keep this issue open until then), can you tell me if that solves your issue?

**Comment by gautierrog** [comment]
Thank you very much. Yes it solved my issue.
