### ISSUE TITLE
Sharing form triggers authentication

### ISSUE THREAD

**Issue by gautierrog** [gristlabs/grist-core#944]
Hello,

Self hosting grist with OIDC integration here. When sharing a form, accessing the link triggers authentication although it should not. 
Furthermore, the authentication process loops indefinitely.

Attached a screenshot illustration which link:
![image](https://github.com/gristlabs/grist-core/assets/110091547/53fc5838-8861-4388-aca8-be15d6518e3f)

I can provide more details if needed.

**Comment by fflorent** [comment]
By chance, have you set the `GRIST_FORCE_LOGIN` env variable? This is the only cause of this issue I may know

**Comment by fflorent** [comment]
@gautierrog Right, you may rather consider setting `GRIST_ANON_PLAYGROUND=false` instead (and stop using `GRIST_FORCE_LOGIN`), if your need is to disallow anonymous users to create temporary documents.

**Comment by gautierrog** [comment]
Thank you for the advice. It will do the job for our case.
