### ISSUE TITLE
Import document to the website > nested tables are not displayed and nowhere to be found

### ISSUE THREAD

**Issue by asitemade4u** [gristlabs/grist-core#95]
1. As per #94 I have imported a pre-existing document to the [website](getgrist.com)
2. The table `wrk` in that document was nested under `all` in the left sidebar
3. When imported into the website, the document does not display the `wrk` table any longer in the left sidebar
4. However, the table is still active as it is referenced in other tables

**Question**: How do I display the table `wrk` again?

**Comment by asitemade4u** [comment]
Not really: `wrk` is not displayed any longer. In fact, what happens is that all **first quotations** of each table were transferred but not the subsequent ones.
In my case (if you wish I can privately provide the original document):
- the first quotation of the `wrk` table, in a page where it was compounded with a linked table
- but the other (plain) quotation of `wrk` has disappeared

I think it is a recurrent behavior as it also happened with yet another table in the same document.

**Comment by paulfitz** [comment]
That sounds strange, I don't understand it yet. I'm `paul@getgrist.com` if you're willing to grant access; or alternatively screenshots could help.

**Comment by asitemade4u** [comment]
I just sent you the zipped original document on your email address.
When you have time, import the document on the website and you'll no doubt withness the weird behavior.

**Comment by paulfitz** [comment]
Thank you! For that document, I see:
 * Two tables, `All` and `ByContext`. 
 * A column called `wrk` in the table `All` that is a reference column, referring to the `dsc` column of the `ByContext` table.
 * Two pages, called `all` and `byContext`.

I think I see some page nesting that didn't survive. You can nest the `byContext` page within the `all` page by grabbing the `||` handle to the right of the `byContext` page when hovering over it, and then dropping it on the `all` page https://support.getgrist.com/page-widgets/#pages

I don't see a `wrk` table in the .grist file. You can list tables in a .grist files without using Grist itself, if you have the `sqlite3` utility - just list tables with `.tables` and ignore all the `_grist` ones:
```
$ sqlite3 tp*.grist .tables
All                            _grist_TableViews            
ByContext                      _grist_Tables                
_grist_ACLMemberships          _grist_Tables_column         
_grist_ACLPrincipals           _grist_Validations           
_grist_ACLResources            _grist_Views                 
_grist_ACLRules                _grist_Views_section         
_grist_Attachments             _grist_Views_section_field   
_grist_DocInfo                 _gristsys_Action             
_grist_External_database       _gristsys_ActionHistory      
_grist_External_table          _gristsys_ActionHistoryBranch
_grist_Imports                 _gristsys_Action_step        
_grist_Pages                   _gristsys_FileInfo           
_grist_REPL_Hist               _gristsys_Files              
_grist_TabBar                  _gristsys_PluginData         
_grist_TabItems              
```
I feel like we might be using terminology differently. Could you tell me more about `the other (plain) quotation of wrk has disappeared`?

**Comment by asitemade4u** [comment]
Hi Paul, thanks for the answer.
As a general rule when creating a new document on Grist, here is what I do:

1. I create the main table -- in this case: `tdo` (it is a debugging todo list), which is now `all`
2. I create all secondary reference tables and nest them under the main table -- here there was only one, `wrk`
3. then I create one or more dashboards linking the tables together -- in this case there was only one which is `byContext`: it allows me to visualize the tasks for each work plan.

Frankly this is not a big deal as the tables still exist.
I must admit being more worried about the docker images...

**Comment by paulfitz** [comment]
I'm not sure if it is related to your issue, but the relationship between pages and tables is currently confusing, with the first page created for a table playing a special, non-intuitive role. There's a task on our roadmap to disentangle that https://github.com/gristlabs/grist-core/issues/39. We're just starting to work on it now as it happens. It may not help you, but it should simplify the relationship between pages and tables.

**Comment by asitemade4u** [comment]
I had indeed noticed that. For database newbies, this could however make sense: you begin by the most important/numerous records in what you have to manage...
