### ISSUE TITLE
Download data with column ID instead of label as header

### ISSUE THREAD

**Issue by pajachiet** [gristlabs/grist-core#954]
Thanks a lot for this great tool !

We would like to use explicit column labels in Grist, to improve readability for users.

But this adds special characters such as spaces, accented letters or apostrophes, which makes it harder when we want to export data and use it for downstream analysis.

Would it be possible to choose to use column IDs instead of column headers when exporting data as CSV or xlsx files?

**Comment by fflorent** [comment]
Hi @pajachiet!

Have you tried adding `?header=coldId` to the download URL?

See https://github.com/gristlabs/grist-core/pull/692

**Comment by pajachiet** [comment]
Hi, 

thanks for this very fast answer !

This work indeed, without the typo (`colId` not `coldId`). Sorry I did not search for closed issues.

But :
- I get "gristHelper_Display" as a header for Reference or Formula fields
- a button to configure the download would be great, to discover the possibility and for less experienced users

**Comment by vviers** [comment]
> I get "gristHelper_Display" as a header for Reference or Formula fields

@pajachiet do you mind closing this issue and opening a new one if you believe this is a bug ? It will be easier to track

Same for you second bullet point :)
