### ISSUE TITLE
Import from .grist file from the website does not work on the docker version

### ISSUE THREAD

**Issue by asitemade4u** [gristlabs/grist-core#96]
1. I have installed the last version of Grist on the server using the newest docker image. Everything works fine
2. I download a document I have been working on in the interim from the getgrist.com website. It generates a `.grist` document on disk
3. In the server-hosted version of Grist, I do : Home Page : Add New : Import from file and select the file on the disk
4. I get an error : `Import failed: File format is not supported.`

**Comment by asitemade4u** [comment]
The weird thing is that:

- the bug occurs when the document originates from the website
- import from my backup files do not generate an error

**Comment by asitemade4u** [comment]
I just sent you on your email address the document coming from the website which I can't import into the docker-based version.

**Comment by paulfitz** [comment]
@asitemade4u I think the issue may be where exactly you do the import. Make sure you are not currently in a document, but rather in the site home page. You can't currently merge two documents.

<img width="821" alt="Screen Shot 2021-11-30 at 6 23 46 PM" src="https://user-images.githubusercontent.com/118367/144144081-13efc627-bba5-48aa-af23-d65e45bcfe9a.png">

**Comment by asitemade4u** [comment]
Yes you are right, apologies for waisting your time.
However there is a "mirror effect" in the interface which can be a bit confusing -- I have now worked quite a bitg with Grist and got confused...
