### ISSUE TITLE
Grist Forms - Redirecting loop error

### ISSUE THREAD

**Issue by s-karrer** [gristlabs/grist-core#966]
Hello, i am working with Grist Forms and found a bug when i want to access a published form.

### Problem
I get a redirecting loop error accessing the forms link :  `http://localhost:9999/forms/47QFRwq6wLjhGTYaUAckWG/4`

![image](https://github.com/gristlabs/grist-core/assets/33320179/252a93cb-8c8b-4ac5-a99d-784099ee538e)

This bug came up when using Grist Omnibus with email/password authentication and you have a logged in session.
(Grist Version 1.1.13)

The log output:
```
2024-05-06 07:20:27.067 - debug: Authorizer: redirecting to log in
2024-05-06 07:20:27.095 - debug: Authorizer: redirecting to log in
2024-05-06 07:20:27.119 - debug: Authorizer: redirecting to log in
2024-05-06 07:20:27.155 - debug: Authorizer: redirecting to log in
2024-05-06 07:20:27.209 - debug: Authorizer: redirecting to log in
2024-05-06 07:20:27.251 - debug: Authorizer: redirecting to log in
2024-05-06 07:20:27.288 - debug: Authorizer: redirecting to log in
2024-05-06 07:20:27.319 - debug: Authorizer: redirecting to log in
2024-05-06 07:20:27.350 - debug: Authorizer: redirecting to log in
2024-05-06 07:20:27.378 - debug: Authorizer: redirecting to log in
```

### Solution
I figured out that the formMiddleware is missing some redirects as you can see here:

https://github.com/gristlabs/grist-core/blob/51ec221a1972a94cd3a545d563bcfe48a675cf5d/app/server/lib/FlexServer.ts?plain=1#L1121-L1123

When adding the redirects used for docMiddleware, it is working fine:
```
formMiddleware: [
        this._redirectToHostMiddleware,
        this._userIdMiddleware,
        forcedLoginMiddleware,
        this._redirectToOrgMiddleware,
        welcomeNewUser
      ],
```

If I use Grist only instead of Grist Omnibus it is working but I dont know why maybe because no authentication and redirect is happening. Also the form access link is different: `http://localhost:8484/o/docs/forms/5jzQzr3NL8tYwALbBcJkBz/4`

I am not into that code base so maybe someone can have a closer look.
Is this fix valid or do i miss something and the fix should be in my Omnibus setup?

**Comment by thinkbig1979** [comment]
Having a similar issue with forms. I'm using zitadel OIDC SSO, which is working with Grist otherwise, only forms seem to have a problem. Here's the console output: 
![image](https://github.com/gristlabs/grist-core/assets/18327273/18571191-9482-463e-898c-8dd87d2f7c89)

**Comment by fflorent** [comment]
Do you really need `GRIST_FORCE_LOGIN` to be set? Quoting the documentation:

> Much like `GRIST_ANON_PLAYGROUND` but don't support anonymous access at all (features like sharing docs publicly requires authentication)

Or would  `GRIST_ANON_PLAYGROUND` fit your need? 
AFAICT, with this option, the forms work.

**Comment by thinkbig1979** [comment]
Thanks @fflorent, thanks for your comment, but I do not want the forms to be publicly accessible, and this problem occurs both when users are logged in prior to trying to access the form or when they go to the form url and are sent to the login page. As soon as they are logged in, this error occurs.
The docs say this about FORCE_LOGIN, and that is what I want to happen, as I do not want anonymous users in the system at all. So as far as I can tell, that setting is correct.

    GRIST_FORCE_LOGIN: (optional) when set to true this will instruct Grist to redirect anonymous users to a login page.

**Comment by paulfitz** [comment]
This turns out to be easy to replicate in grist-omnibus, local setup, default example in `README`. Parallel thread in forms here: https://community.getgrist.com/t/forms-not-working-on-self-hosted-grist/5212

**Comment by paulfitz** [comment]
@georgegevoian and @berhalak I'd appreciate your eyes on this issue [when you're available obviously, otherwise enjoy your respective vacations :-)].

**Comment by georgegevoian** [comment]
A fix has now landed in grist-omnibus. It's also in the `latest` grist-core image, and will be included in the next versioned release (`1.1.15`).

Let us know if you run into any issues. Thanks!

**Comment by s-karrer** [comment]
> @s-karrer thanks for digging into the problem. Can you confirm that adding just `this._userIdMiddleware` to `formMiddleware` addresses your issue? (That fix should be landing shortly.)

Yes just adding `this._userIdMiddleware` is working fine. Thank you!

**Comment by fflorent** [comment]
Is this problem solved then? :)
