### ISSUE TITLE
Forms created from a Summary Table are bugged 

### ISSUE THREAD

**Issue by nicolas-imbert** [gristlabs/grist-core#967]
Hey, 

Yesterday we experienced errors with a form in Grist. 
The user could not change any parameters in the form because... it was created from a Summary Table. 

Here is the error we had.
![image (2)](https://github.com/gristlabs/grist-core/assets/155563823/4efab270-64cd-4383-b9d4-5ca551ab8338)
And all form parameters were blocked (can't change the name of a field, column type, field rules, etc.)

In my opinion, it makes no sense to create a form from a Summary Table. 
So shouldnt we just remove the option?

The quick solution that comes to my mind could be : At creation, as soon as we select Form in the View panel, the "Sum" sign should not appear in the Raw Data panel. That would avoid the mistake of creating Form from a Summary Table. 

What do you think? 
Thanks !

**Comment by dsagal** [comment]
I agree, it doesn't make sense to create a Form from a summary table. It would make sense to me if in the "Add Widget" panel, "Sum" icon were disabled when Form widget is chosen, and if "Form" option were greyed out when "Sum" is selected.
