### ISSUE TITLE
Transform a Column type from Reference to Text

### ISSUE THREAD

**Issue by asitemade4u** [gristlabs/grist-core#97]
1. I have a column which is of Reference type
2. I change it to Text
3. The empty cells are now populated with `Lin[0]` which makes sense on a development standpoint but probably not for average users

**Comment by asitemade4u** [comment]
Generally speaking, I think you should test (or forbid, for that matter) conversions of Columns from one type to another:
- Reference List > Text > Reference generates weird control codes in each cell

**Comment by paulfitz** [comment]
Thanks @asitemade4u. Good points. The `u` in `[u'tst']` will be gone soon at least, it is a Python2 unicode support thing.

**Comment by alexmojaki** [comment]
I have been working hard on this for weeks now and have drastically overhauled the type conversion system in https://github.com/gristlabs/grist-core/commit/5d671bf0b30760d40b424035ab8afb6722cdd583 ! You should be able to take advantage of this immediately, but the changes will only appear in https://docs.getgrist.com/ next week.

Both your examples have been fixed, several other cases of type conversion have been improved and made more consistent with other parts of Grist, and extensive tests have been added for many combinations of types!
