### ISSUE TITLE
Simple login

### ISSUE THREAD

**Issue by AmsellemJoseph** [gristlabs/grist-core#998]
Hey,

I would like to know if there is a way to have a simple registration and login page so that I can simply log in and not need to use a third party like keycloak or authentik and not just basic auth, so to be able to have several different users.

Thank you very much for your answers and your work.

**Comment by jperon** [comment]
It is possible if using a reverse proxy like nginx or traefik, following the guidelines [found here](https://support.getgrist.com/install/forwarded-headers/).

In my case, I use openresty with custom pages for authentication and registration of new users. I could share my `compose.yaml` and `nginx.conf` if you like, but not before next week-end, as my personal settings are quite "hardcoded" within them for now.

**Comment by AmsellemJoseph** [comment]
hey @jperon, thx a lot my friend for your link.
I'm using grist-omnibus, and its work like a charm.
